# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'add_data_specimen.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QComboBox,
    QDateTimeEdit, QFrame, QLabel, QLineEdit,
    QMainWindow, QPushButton, QRadioButton, QSizePolicy,
    QStatusBar, QTextEdit, QWidget)

class Ui_add_data_specimen(object):
    def setupUi(self, add_data_specimen):
        if not add_data_specimen.objectName():
            add_data_specimen.setObjectName(u"add_data_specimen")
        add_data_specimen.resize(1400, 900)
        add_data_specimen.setMinimumSize(QSize(1400, 900))
        add_data_specimen.setMaximumSize(QSize(1400, 900))
        self.centralwidget = QWidget(add_data_specimen)
        self.centralwidget.setObjectName(u"centralwidget")
        self.info_sample_specimen_frame1 = QFrame(self.centralwidget)
        self.info_sample_specimen_frame1.setObjectName(u"info_sample_specimen_frame1")
        self.info_sample_specimen_frame1.setGeometry(QRect(9, 9, 1381, 471))
        self.info_sample_specimen_frame1.setStyleSheet(u"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(197, 255, 225, 255), stop:0.55 rgba(224, 235, 188, 255), stop:0.98 rgba(204, 200, 127, 255), stop:1 rgba(0, 0, 0, 0))")
        self.info_sample_specimen_frame1.setFrameShape(QFrame.Box)
        self.info_sample_specimen_frame1.setFrameShadow(QFrame.Plain)
        self.info_sample_specimen_frame1.setLineWidth(2)
        self.info_sample_specimen_frame2 = QFrame(self.info_sample_specimen_frame1)
        self.info_sample_specimen_frame2.setObjectName(u"info_sample_specimen_frame2")
        self.info_sample_specimen_frame2.setGeometry(QRect(9, 9, 1363, 454))
        self.info_sample_specimen_frame2.setStyleSheet(u"background:rgb(239, 239, 239)")
        self.info_sample_specimen_frame2.setFrameShape(QFrame.Box)
        self.info_sample_specimen_frame2.setFrameShadow(QFrame.Plain)
        self.info_sample_specimen_frame2.setLineWidth(2)
        self.info_specimen_label = QLabel(self.info_sample_specimen_frame2)
        self.info_specimen_label.setObjectName(u"info_specimen_label")
        self.info_specimen_label.setGeometry(QRect(10, 10, 181, 31))
        font = QFont()
        font.setFamilies([u"TH Niramit AS"])
        font.setPointSize(18)
        font.setBold(True)
        self.info_specimen_label.setFont(font)
        self.name_animal_label = QLabel(self.info_sample_specimen_frame2)
        self.name_animal_label.setObjectName(u"name_animal_label")
        self.name_animal_label.setGeometry(QRect(10, 50, 61, 31))
        self.name_animal_label.setFont(font)
        self.number_id_opd_label = QLabel(self.info_sample_specimen_frame2)
        self.number_id_opd_label.setObjectName(u"number_id_opd_label")
        self.number_id_opd_label.setGeometry(QRect(10, 95, 151, 31))
        self.number_id_opd_label.setFont(font)
        self.animal_type_frame = QFrame(self.info_sample_specimen_frame2)
        self.animal_type_frame.setObjectName(u"animal_type_frame")
        self.animal_type_frame.setGeometry(QRect(10, 140, 991, 81))
        self.animal_type_frame.setFrameShape(QFrame.Box)
        self.animal_type_frame.setFrameShadow(QFrame.Plain)
        self.animal_type_label = QLabel(self.animal_type_frame)
        self.animal_type_label.setObjectName(u"animal_type_label")
        self.animal_type_label.setGeometry(QRect(10, 10, 71, 31))
        self.animal_type_label.setFont(font)
        self.swine_radioButton = QRadioButton(self.animal_type_frame)
        self.swine_radioButton.setObjectName(u"swine_radioButton")
        self.swine_radioButton.setGeometry(QRect(100, 7, 111, 31))
        self.swine_radioButton.setFont(font)
        self.avian_radioButton = QRadioButton(self.animal_type_frame)
        self.avian_radioButton.setObjectName(u"avian_radioButton")
        self.avian_radioButton.setGeometry(QRect(240, 7, 141, 31))
        self.avian_radioButton.setFont(font)
        self.bovine_radioButton = QRadioButton(self.animal_type_frame)
        self.bovine_radioButton.setObjectName(u"bovine_radioButton")
        self.bovine_radioButton.setGeometry(QRect(410, 7, 141, 31))
        self.bovine_radioButton.setFont(font)
        self.equine_radioButton = QRadioButton(self.animal_type_frame)
        self.equine_radioButton.setObjectName(u"equine_radioButton")
        self.equine_radioButton.setGeometry(QRect(550, 7, 141, 31))
        self.equine_radioButton.setFont(font)
        self.canine_radioButton = QRadioButton(self.animal_type_frame)
        self.canine_radioButton.setObjectName(u"canine_radioButton")
        self.canine_radioButton.setGeometry(QRect(690, 7, 141, 31))
        self.canine_radioButton.setFont(font)
        self.feline_radioButton = QRadioButton(self.animal_type_frame)
        self.feline_radioButton.setObjectName(u"feline_radioButton")
        self.feline_radioButton.setGeometry(QRect(850, 7, 131, 31))
        self.feline_radioButton.setFont(font)
        self.elephant_radioButton = QRadioButton(self.animal_type_frame)
        self.elephant_radioButton.setObjectName(u"elephant_radioButton")
        self.elephant_radioButton.setGeometry(QRect(100, 40, 141, 31))
        self.elephant_radioButton.setFont(font)
        self.anthor_radioButton = QRadioButton(self.animal_type_frame)
        self.anthor_radioButton.setObjectName(u"anthor_radioButton")
        self.anthor_radioButton.setGeometry(QRect(240, 40, 141, 31))
        self.anthor_radioButton.setFont(font)
        self.another_type_animal_entry = QLineEdit(self.animal_type_frame)
        self.another_type_animal_entry.setObjectName(u"another_type_animal_entry")
        self.another_type_animal_entry.setGeometry(QRect(300, 40, 211, 31))
        font1 = QFont()
        font1.setFamilies([u"TH Niramit AS"])
        font1.setPointSize(12)
        font1.setBold(True)
        self.another_type_animal_entry.setFont(font1)
        self.another_type_animal_entry.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.unknow_radioButton = QRadioButton(self.animal_type_frame)
        self.unknow_radioButton.setObjectName(u"unknow_radioButton")
        self.unknow_radioButton.setGeometry(QRect(550, 40, 141, 31))
        self.unknow_radioButton.setFont(font)
        self.breed_label = QLabel(self.info_sample_specimen_frame2)
        self.breed_label.setObjectName(u"breed_label")
        self.breed_label.setGeometry(QRect(10, 235, 101, 31))
        self.breed_label.setFont(font)
        self.day_of_death_label = QLabel(self.info_sample_specimen_frame2)
        self.day_of_death_label.setObjectName(u"day_of_death_label")
        self.day_of_death_label.setGeometry(QRect(10, 290, 101, 31))
        self.day_of_death_label.setFont(font)
        self.day_keep_sample_label = QLabel(self.info_sample_specimen_frame2)
        self.day_keep_sample_label.setObjectName(u"day_keep_sample_label")
        self.day_keep_sample_label.setGeometry(QRect(10, 340, 131, 31))
        self.day_keep_sample_label.setFont(font)
        self.record_heal_label = QLabel(self.info_sample_specimen_frame2)
        self.record_heal_label.setObjectName(u"record_heal_label")
        self.record_heal_label.setGeometry(QRect(10, 380, 131, 31))
        self.record_heal_label.setFont(font)
        self.name_animal_entry = QLineEdit(self.info_sample_specimen_frame2)
        self.name_animal_entry.setObjectName(u"name_animal_entry")
        self.name_animal_entry.setGeometry(QRect(160, 40, 421, 41))
        self.name_animal_entry.setFont(font)
        self.name_animal_entry.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.number_id_opd_entry = QLineEdit(self.info_sample_specimen_frame2)
        self.number_id_opd_entry.setObjectName(u"number_id_opd_entry")
        self.number_id_opd_entry.setGeometry(QRect(160, 90, 421, 41))
        self.number_id_opd_entry.setFont(font)
        self.number_id_opd_entry.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.breed_entry = QLineEdit(self.info_sample_specimen_frame2)
        self.breed_entry.setObjectName(u"breed_entry")
        self.breed_entry.setGeometry(QRect(160, 230, 421, 41))
        self.breed_entry.setFont(font)
        self.breed_entry.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.day_of_death_dateTime = QDateTimeEdit(self.info_sample_specimen_frame2)
        self.day_of_death_dateTime.setObjectName(u"day_of_death_dateTime")
        self.day_of_death_dateTime.setGeometry(QRect(160, 280, 281, 41))
        font2 = QFont()
        font2.setFamilies([u"Times New Roman"])
        font2.setPointSize(16)
        font2.setBold(False)
        self.day_of_death_dateTime.setFont(font2)
        self.day_of_death_dateTime.setLayoutDirection(Qt.LeftToRight)
        self.day_of_death_dateTime.setAutoFillBackground(False)
        self.day_of_death_dateTime.setStyleSheet(u"background:rgb(192, 207, 255)")
        self.day_of_death_dateTime.setLocale(QLocale(QLocale.Thai, QLocale.Thailand))
        self.day_of_death_dateTime.setWrapping(False)
        self.day_of_death_dateTime.setReadOnly(False)
        self.day_of_death_dateTime.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.day_of_death_dateTime.setMaximumTime(QTime(23, 59, 59))
        self.day_of_death_dateTime.setCurrentSection(QDateTimeEdit.DaySection)
        self.day_of_death_dateTime.setCalendarPopup(True)
        self.day_of_death_dateTime.setCurrentSectionIndex(0)
        self.day_of_death_dateTime.setTimeSpec(Qt.LocalTime)
        self.day_keep_sample_dateTime = QDateTimeEdit(self.info_sample_specimen_frame2)
        self.day_keep_sample_dateTime.setObjectName(u"day_keep_sample_dateTime")
        self.day_keep_sample_dateTime.setGeometry(QRect(160, 330, 281, 41))
        self.day_keep_sample_dateTime.setFont(font2)
        self.day_keep_sample_dateTime.setLayoutDirection(Qt.LeftToRight)
        self.day_keep_sample_dateTime.setAutoFillBackground(False)
        self.day_keep_sample_dateTime.setStyleSheet(u"background:rgb(192, 207, 255)")
        self.day_keep_sample_dateTime.setLocale(QLocale(QLocale.Thai, QLocale.Thailand))
        self.day_keep_sample_dateTime.setWrapping(False)
        self.day_keep_sample_dateTime.setReadOnly(False)
        self.day_keep_sample_dateTime.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.day_keep_sample_dateTime.setMaximumTime(QTime(23, 59, 59))
        self.day_keep_sample_dateTime.setCurrentSection(QDateTimeEdit.DaySection)
        self.day_keep_sample_dateTime.setCalendarPopup(True)
        self.day_keep_sample_dateTime.setCurrentSectionIndex(0)
        self.day_keep_sample_dateTime.setTimeSpec(Qt.LocalTime)
        self.record_heal_textEdit = QTextEdit(self.info_sample_specimen_frame2)
        self.record_heal_textEdit.setObjectName(u"record_heal_textEdit")
        self.record_heal_textEdit.setGeometry(QRect(160, 380, 841, 61))
        self.record_heal_textEdit.setFont(font)
        self.record_heal_textEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.sex_animal_label = QLabel(self.info_sample_specimen_frame2)
        self.sex_animal_label.setObjectName(u"sex_animal_label")
        self.sex_animal_label.setGeometry(QRect(610, 50, 81, 31))
        self.sex_animal_label.setFont(font)
        self.sex_animal_comboBox = QComboBox(self.info_sample_specimen_frame2)
        self.sex_animal_comboBox.addItem("")
        self.sex_animal_comboBox.addItem("")
        self.sex_animal_comboBox.addItem("")
        self.sex_animal_comboBox.addItem("")
        self.sex_animal_comboBox.addItem("")
        self.sex_animal_comboBox.addItem("")
        self.sex_animal_comboBox.addItem("")
        self.sex_animal_comboBox.addItem("")
        self.sex_animal_comboBox.setObjectName(u"sex_animal_comboBox")
        self.sex_animal_comboBox.setGeometry(QRect(700, 41, 131, 41))
        font3 = QFont()
        font3.setFamilies([u"TH Niramit AS"])
        font3.setPointSize(20)
        font3.setBold(True)
        self.sex_animal_comboBox.setFont(font3)
        self.sex_animal_comboBox.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.cause_of_death_label = QLabel(self.info_sample_specimen_frame2)
        self.cause_of_death_label.setObjectName(u"cause_of_death_label")
        self.cause_of_death_label.setGeometry(QRect(850, 50, 141, 31))
        self.cause_of_death_label.setFont(font)
        self.cause_of_death_comboBox = QComboBox(self.info_sample_specimen_frame2)
        self.cause_of_death_comboBox.addItem("")
        self.cause_of_death_comboBox.addItem("")
        self.cause_of_death_comboBox.addItem("")
        self.cause_of_death_comboBox.addItem("")
        self.cause_of_death_comboBox.setObjectName(u"cause_of_death_comboBox")
        self.cause_of_death_comboBox.setGeometry(QRect(1000, 40, 161, 41))
        self.cause_of_death_comboBox.setFont(font3)
        self.cause_of_death_comboBox.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.age_animal_label = QLabel(self.info_sample_specimen_frame2)
        self.age_animal_label.setObjectName(u"age_animal_label")
        self.age_animal_label.setGeometry(QRect(610, 100, 81, 31))
        self.age_animal_label.setFont(font)
        self.year_animal_entry = QLineEdit(self.info_sample_specimen_frame2)
        self.year_animal_entry.setObjectName(u"year_animal_entry")
        self.year_animal_entry.setGeometry(QRect(700, 90, 61, 41))
        self.year_animal_entry.setFont(font)
        self.year_animal_entry.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.year_animal_label = QLabel(self.info_sample_specimen_frame2)
        self.year_animal_label.setObjectName(u"year_animal_label")
        self.year_animal_label.setGeometry(QRect(770, 100, 21, 31))
        self.year_animal_label.setFont(font)
        self.month_animal_label = QLabel(self.info_sample_specimen_frame2)
        self.month_animal_label.setObjectName(u"month_animal_label")
        self.month_animal_label.setGeometry(QRect(870, 100, 41, 31))
        self.month_animal_label.setFont(font)
        self.month_animal_entry = QLineEdit(self.info_sample_specimen_frame2)
        self.month_animal_entry.setObjectName(u"month_animal_entry")
        self.month_animal_entry.setGeometry(QRect(800, 90, 61, 41))
        self.month_animal_entry.setFont(font)
        self.month_animal_entry.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.day_animal_label = QLabel(self.info_sample_specimen_frame2)
        self.day_animal_label.setObjectName(u"day_animal_label")
        self.day_animal_label.setGeometry(QRect(990, 100, 21, 31))
        self.day_animal_label.setFont(font)
        self.day_animal_entry = QLineEdit(self.info_sample_specimen_frame2)
        self.day_animal_entry.setObjectName(u"day_animal_entry")
        self.day_animal_entry.setGeometry(QRect(920, 90, 61, 41))
        self.day_animal_entry.setFont(font)
        self.day_animal_entry.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.unknow_age_animal_checkbox = QCheckBox(self.info_sample_specimen_frame2)
        self.unknow_age_animal_checkbox.setObjectName(u"unknow_age_animal_checkbox")
        self.unknow_age_animal_checkbox.setGeometry(QRect(1040, 106, 121, 20))
        self.unknow_age_animal_checkbox.setFont(font)
        self.weight_animal_entry = QLineEdit(self.info_sample_specimen_frame2)
        self.weight_animal_entry.setObjectName(u"weight_animal_entry")
        self.weight_animal_entry.setGeometry(QRect(690, 230, 121, 41))
        self.weight_animal_entry.setFont(font)
        self.weight_animal_entry.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.weight_animal_label = QLabel(self.info_sample_specimen_frame2)
        self.weight_animal_label.setObjectName(u"weight_animal_label")
        self.weight_animal_label.setGeometry(QRect(610, 240, 61, 31))
        self.weight_animal_label.setFont(font)
        self.kilogram_animal_label = QLabel(self.info_sample_specimen_frame2)
        self.kilogram_animal_label.setObjectName(u"kilogram_animal_label")
        self.kilogram_animal_label.setGeometry(QRect(830, 240, 61, 31))
        self.kilogram_animal_label.setFont(font)
        self.keeping_specimen_frame = QFrame(self.info_sample_specimen_frame2)
        self.keeping_specimen_frame.setObjectName(u"keeping_specimen_frame")
        self.keeping_specimen_frame.setGeometry(QRect(470, 280, 531, 91))
        self.keeping_specimen_frame.setFrameShape(QFrame.Box)
        self.keeping_specimen_frame.setFrameShadow(QFrame.Plain)
        self.keeping_specimen_label = QLabel(self.keeping_specimen_frame)
        self.keeping_specimen_label.setObjectName(u"keeping_specimen_label")
        self.keeping_specimen_label.setGeometry(QRect(170, 10, 161, 31))
        self.keeping_specimen_label.setFont(font)
        self.chill_specimen_radioButton = QRadioButton(self.keeping_specimen_frame)
        self.chill_specimen_radioButton.setObjectName(u"chill_specimen_radioButton")
        self.chill_specimen_radioButton.setGeometry(QRect(10, 50, 141, 31))
        self.chill_specimen_radioButton.setFont(font)
        self.freeze_specimen_radioButton = QRadioButton(self.keeping_specimen_frame)
        self.freeze_specimen_radioButton.setObjectName(u"freeze_specimen_radioButton")
        self.freeze_specimen_radioButton.setGeometry(QRect(150, 50, 141, 31))
        self.freeze_specimen_radioButton.setFont(font)
        self.room_temp_specimen_radioButton = QRadioButton(self.keeping_specimen_frame)
        self.room_temp_specimen_radioButton.setObjectName(u"room_temp_specimen_radioButton")
        self.room_temp_specimen_radioButton.setGeometry(QRect(300, 50, 221, 31))
        self.room_temp_specimen_radioButton.setFont(font)
        self.speed_frame = QFrame(self.info_sample_specimen_frame2)
        self.speed_frame.setObjectName(u"speed_frame")
        self.speed_frame.setGeometry(QRect(1010, 140, 151, 141))
        self.speed_frame.setFrameShape(QFrame.Box)
        self.speed_frame.setFrameShadow(QFrame.Plain)
        self.speed_label = QLabel(self.speed_frame)
        self.speed_label.setObjectName(u"speed_label")
        self.speed_label.setGeometry(QRect(20, 10, 121, 31))
        self.speed_label.setFont(font)
        self.normal_radioButton = QRadioButton(self.speed_frame)
        self.normal_radioButton.setObjectName(u"normal_radioButton")
        self.normal_radioButton.setGeometry(QRect(20, 50, 121, 31))
        self.normal_radioButton.setFont(font)
        self.most_argent_radioButton = QRadioButton(self.speed_frame)
        self.most_argent_radioButton.setObjectName(u"most_argent_radioButton")
        self.most_argent_radioButton.setGeometry(QRect(20, 90, 121, 31))
        self.most_argent_radioButton.setFont(font)
        self.save_pushButton = QPushButton(self.info_sample_specimen_frame2)
        self.save_pushButton.setObjectName(u"save_pushButton")
        self.save_pushButton.setGeometry(QRect(1180, 40, 171, 81))
        font4 = QFont()
        font4.setFamilies([u"TH Niramit AS"])
        font4.setPointSize(24)
        font4.setBold(True)
        self.save_pushButton.setFont(font4)
        self.save_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.back_pushButton = QPushButton(self.info_sample_specimen_frame2)
        self.back_pushButton.setObjectName(u"back_pushButton")
        self.back_pushButton.setGeometry(QRect(1180, 140, 171, 81))
        self.back_pushButton.setFont(font4)
        self.back_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.sample_lab_frame1 = QFrame(self.centralwidget)
        self.sample_lab_frame1.setObjectName(u"sample_lab_frame1")
        self.sample_lab_frame1.setGeometry(QRect(10, 490, 1381, 389))
        self.sample_lab_frame1.setStyleSheet(u"background:rgb(85, 85, 127)")
        self.sample_lab_frame1.setFrameShape(QFrame.Box)
        self.sample_lab_frame1.setFrameShadow(QFrame.Plain)
        self.sample_lab_frame1.setLineWidth(2)
        self.sample_lab_frame2 = QFrame(self.sample_lab_frame1)
        self.sample_lab_frame2.setObjectName(u"sample_lab_frame2")
        self.sample_lab_frame2.setGeometry(QRect(9, 9, 1363, 371))
        self.sample_lab_frame2.setStyleSheet(u"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(197, 255, 225, 255), stop:0.55 rgba(224, 235, 188, 255), stop:0.98 rgba(204, 200, 127, 255), stop:1 rgba(0, 0, 0, 0))")
        self.sample_lab_frame2.setFrameShape(QFrame.Box)
        self.sample_lab_frame2.setFrameShadow(QFrame.Plain)
        self.sample_lab_frame2.setLineWidth(2)
        self.sample_lab_label = QLabel(self.sample_lab_frame2)
        self.sample_lab_label.setObjectName(u"sample_lab_label")
        self.sample_lab_label.setGeometry(QRect(10, 5, 181, 31))
        self.sample_lab_label.setFont(font)
        self.Fungal_pushButton = QPushButton(self.sample_lab_frame2)
        self.Fungal_pushButton.setObjectName(u"Fungal_pushButton")
        self.Fungal_pushButton.setGeometry(QRect(40, 40, 411, 41))
        font5 = QFont()
        font5.setFamilies([u"TH Niramit AS"])
        font5.setPointSize(16)
        font5.setBold(True)
        self.Fungal_pushButton.setFont(font5)
        self.Fungal_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Microbiology_pushButton = QPushButton(self.sample_lab_frame2)
        self.Microbiology_pushButton.setObjectName(u"Microbiology_pushButton")
        self.Microbiology_pushButton.setGeometry(QRect(478, 40, 411, 41))
        self.Microbiology_pushButton.setFont(font5)
        self.Microbiology_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.virology_pushButton = QPushButton(self.sample_lab_frame2)
        self.virology_pushButton.setObjectName(u"virology_pushButton")
        self.virology_pushButton.setGeometry(QRect(915, 40, 411, 41))
        self.virology_pushButton.setFont(font5)
        self.virology_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Serology_pushButton = QPushButton(self.sample_lab_frame2)
        self.Serology_pushButton.setObjectName(u"Serology_pushButton")
        self.Serology_pushButton.setGeometry(QRect(40, 95, 411, 41))
        self.Serology_pushButton.setFont(font5)
        self.Serology_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Parasitology_pushButton = QPushButton(self.sample_lab_frame2)
        self.Parasitology_pushButton.setObjectName(u"Parasitology_pushButton")
        self.Parasitology_pushButton.setGeometry(QRect(478, 95, 411, 41))
        self.Parasitology_pushButton.setFont(font5)
        self.Parasitology_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.feed_analysis_pushButton = QPushButton(self.sample_lab_frame2)
        self.feed_analysis_pushButton.setObjectName(u"feed_analysis_pushButton")
        self.feed_analysis_pushButton.setGeometry(QRect(915, 95, 411, 41))
        self.feed_analysis_pushButton.setFont(font5)
        self.feed_analysis_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.water_quality_pushButton = QPushButton(self.sample_lab_frame2)
        self.water_quality_pushButton.setObjectName(u"water_quality_pushButton")
        self.water_quality_pushButton.setGeometry(QRect(40, 150, 411, 41))
        self.water_quality_pushButton.setFont(font5)
        self.water_quality_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.molecular_pushButton = QPushButton(self.sample_lab_frame2)
        self.molecular_pushButton.setObjectName(u"molecular_pushButton")
        self.molecular_pushButton.setGeometry(QRect(478, 150, 411, 41))
        self.molecular_pushButton.setFont(font5)
        self.molecular_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.hematology_pushButton = QPushButton(self.sample_lab_frame2)
        self.hematology_pushButton.setObjectName(u"hematology_pushButton")
        self.hematology_pushButton.setGeometry(QRect(915, 150, 411, 41))
        self.hematology_pushButton.setFont(font5)
        self.hematology_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Immunohistochemistry_pushButton = QPushButton(self.sample_lab_frame2)
        self.Immunohistochemistry_pushButton.setObjectName(u"Immunohistochemistry_pushButton")
        self.Immunohistochemistry_pushButton.setGeometry(QRect(40, 205, 411, 41))
        self.Immunohistochemistry_pushButton.setFont(font5)
        self.Immunohistochemistry_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.surgical_pushButton = QPushButton(self.sample_lab_frame2)
        self.surgical_pushButton.setObjectName(u"surgical_pushButton")
        self.surgical_pushButton.setGeometry(QRect(478, 205, 411, 41))
        self.surgical_pushButton.setFont(font5)
        self.surgical_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.histopatology_pushButton = QPushButton(self.sample_lab_frame2)
        self.histopatology_pushButton.setObjectName(u"histopatology_pushButton")
        self.histopatology_pushButton.setGeometry(QRect(915, 205, 411, 41))
        self.histopatology_pushButton.setFont(font5)
        self.histopatology_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Necropsy_pushButton = QPushButton(self.sample_lab_frame2)
        self.Necropsy_pushButton.setObjectName(u"Necropsy_pushButton")
        self.Necropsy_pushButton.setGeometry(QRect(40, 260, 411, 41))
        self.Necropsy_pushButton.setFont(font5)
        self.Necropsy_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.cytology_pushButton = QPushButton(self.sample_lab_frame2)
        self.cytology_pushButton.setObjectName(u"cytology_pushButton")
        self.cytology_pushButton.setGeometry(QRect(478, 260, 411, 41))
        self.cytology_pushButton.setFont(font5)
        self.cytology_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.hittopathology_research_pushButton = QPushButton(self.sample_lab_frame2)
        self.hittopathology_research_pushButton.setObjectName(u"hittopathology_research_pushButton")
        self.hittopathology_research_pushButton.setGeometry(QRect(915, 260, 411, 41))
        self.hittopathology_research_pushButton.setFont(font5)
        self.hittopathology_research_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.histopathology_research_recut_pushButton = QPushButton(self.sample_lab_frame2)
        self.histopathology_research_recut_pushButton.setObjectName(u"histopathology_research_recut_pushButton")
        self.histopathology_research_recut_pushButton.setGeometry(QRect(40, 315, 411, 41))
        self.histopathology_research_recut_pushButton.setFont(font5)
        self.histopathology_research_recut_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.food_safty_pushButton = QPushButton(self.sample_lab_frame2)
        self.food_safty_pushButton.setObjectName(u"food_safty_pushButton")
        self.food_safty_pushButton.setGeometry(QRect(478, 315, 411, 41))
        self.food_safty_pushButton.setFont(font5)
        self.food_safty_pushButton.setStyleSheet(u"background:rgb(255, 255, 255)")
        add_data_specimen.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(add_data_specimen)
        self.statusbar.setObjectName(u"statusbar")
        add_data_specimen.setStatusBar(self.statusbar)

        self.retranslateUi(add_data_specimen)

        QMetaObject.connectSlotsByName(add_data_specimen)
    # setupUi

    def retranslateUi(self, add_data_specimen):
        add_data_specimen.setWindowTitle(QCoreApplication.translate("add_data_specimen", u"\u0e40\u0e1e\u0e34\u0e48\u0e21\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e15\u0e31\u0e27\u0e2d\u0e22\u0e48\u0e32\u0e07\u0e17\u0e35\u0e48\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23\u0e2a\u0e48\u0e07\u0e15\u0e23\u0e27\u0e08", None))
        self.info_specimen_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e15\u0e31\u0e27\u0e2d\u0e22\u0e48\u0e32\u0e07\u0e2a\u0e48\u0e07\u0e15\u0e23\u0e27\u0e08", None))
        self.name_animal_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e0a\u0e37\u0e48\u0e2d\u0e2a\u0e31\u0e15\u0e27\u0e4c", None))
        self.number_id_opd_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e21\u0e32\u0e22\u0e40\u0e25\u0e02 (ID/OPD)", None))
        self.animal_type_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e0a\u0e19\u0e34\u0e14\u0e2a\u0e31\u0e15\u0e27\u0e4c", None))
        self.swine_radioButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2a\u0e38\u0e01\u0e23(Swine)", None))
        self.avian_radioButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2a\u0e31\u0e15\u0e27\u0e4c\u0e1b\u0e35\u0e01(Avian)", None))
        self.bovine_radioButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e42\u0e04(Bovine)", None))
        self.equine_radioButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e21\u0e49\u0e32(Equine)", None))
        self.canine_radioButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2a\u0e38\u0e19\u0e31\u0e02(Canine)", None))
        self.feline_radioButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e41\u0e21\u0e27(Feline)", None))
        self.elephant_radioButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e0a\u0e49\u0e32\u0e07(Elephant)", None))
        self.anthor_radioButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2d\u0e37\u0e48\u0e19\u0e46", None))
        self.unknow_radioButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e44\u0e21\u0e48\u0e17\u0e23\u0e32\u0e1a\u0e0a\u0e19\u0e34\u0e14", None))
        self.breed_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e1e\u0e31\u0e19\u0e18\u0e38\u0e4c (Breed)", None))
        self.day_of_death_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e27\u0e31\u0e19\u0e17\u0e35\u0e48\u0e40\u0e2a\u0e35\u0e22\u0e0a\u0e35\u0e27\u0e34\u0e15", None))
        self.day_keep_sample_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e27\u0e31\u0e19\u0e17\u0e35\u0e48\u0e40\u0e01\u0e47\u0e1a\u0e15\u0e31\u0e27\u0e2d\u0e22\u0e48\u0e32\u0e07", None))
        self.record_heal_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e1b\u0e23\u0e30\u0e27\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e23\u0e31\u0e01\u0e29\u0e32", None))
        self.day_of_death_dateTime.setDisplayFormat(QCoreApplication.translate("add_data_specimen", u"d/M/yyyy h:mm ", None))
        self.day_keep_sample_dateTime.setDisplayFormat(QCoreApplication.translate("add_data_specimen", u"d/M/yyyy h:mm ", None))
        self.sex_animal_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e40\u0e1e\u0e28 (SEX)", None))
        self.sex_animal_comboBox.setItemText(0, QCoreApplication.translate("add_data_specimen", u"\u0e1c\u0e39\u0e49 (Male)", None))
        self.sex_animal_comboBox.setItemText(1, QCoreApplication.translate("add_data_specimen", u"\u0e40\u0e21\u0e35\u0e22 (Female)", None))
        self.sex_animal_comboBox.setItemText(2, QCoreApplication.translate("add_data_specimen", u"\u0e44\u0e21\u0e48\u0e17\u0e23\u0e32\u0e1a (Unknow)", None))
        self.sex_animal_comboBox.setItemText(3, QCoreApplication.translate("add_data_specimen", u"\u0e21\u0e49\u0e32 (Foal)", None))
        self.sex_animal_comboBox.setItemText(4, QCoreApplication.translate("add_data_specimen", u"\u0e21\u0e49\u0e32 (Filly)", None))
        self.sex_animal_comboBox.setItemText(5, QCoreApplication.translate("add_data_specimen", u"\u0e21\u0e49\u0e32 (Mare)", None))
        self.sex_animal_comboBox.setItemText(6, QCoreApplication.translate("add_data_specimen", u"\u0e21\u0e49\u0e32 (Gelding)", None))
        self.sex_animal_comboBox.setItemText(7, QCoreApplication.translate("add_data_specimen", u"\u0e21\u0e49\u0e32 (Stallion)", None))

        self.cause_of_death_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2a\u0e32\u0e40\u0e2b\u0e15\u0e38\u0e01\u0e32\u0e23\u0e40\u0e2a\u0e35\u0e22\u0e0a\u0e35\u0e27\u0e34\u0e15", None))
        self.cause_of_death_comboBox.setItemText(0, QCoreApplication.translate("add_data_specimen", u"\u0e22\u0e31\u0e07\u0e21\u0e35\u0e0a\u0e35\u0e27\u0e34\u0e15 (Alive)", None))
        self.cause_of_death_comboBox.setItemText(1, QCoreApplication.translate("add_data_specimen", u"\u0e42\u0e23\u0e04\u0e0a\u0e23\u0e32 (Senile)", None))
        self.cause_of_death_comboBox.setItemText(2, QCoreApplication.translate("add_data_specimen", u"\u0e15\u0e34\u0e14\u0e40\u0e0a\u0e37\u0e49\u0e2d (Infectious Disease)", None))
        self.cause_of_death_comboBox.setItemText(3, QCoreApplication.translate("add_data_specimen", u"\u0e44\u0e21\u0e48\u0e17\u0e23\u0e32\u0e1a\u0e2a\u0e32\u0e40\u0e2b\u0e15\u0e38 (Unknow)", None))

        self.age_animal_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2d\u0e32\u0e22\u0e38 (Age)", None))
        self.year_animal_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e1b\u0e35", None))
        self.month_animal_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e40\u0e14\u0e37\u0e2d\u0e19", None))
        self.day_animal_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e27\u0e31\u0e19", None))
        self.unknow_age_animal_checkbox.setText(QCoreApplication.translate("add_data_specimen", u"\u0e44\u0e21\u0e48\u0e17\u0e23\u0e32\u0e1a\u0e2d\u0e32\u0e22\u0e38", None))
        self.weight_animal_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01", None))
        self.kilogram_animal_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e01\u0e34\u0e42\u0e25\u0e01\u0e23\u0e31\u0e21", None))
        self.keeping_specimen_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e01\u0e32\u0e23\u0e40\u0e01\u0e47\u0e1a\u0e23\u0e31\u0e01\u0e29\u0e32\u0e15\u0e31\u0e27\u0e2d\u0e22\u0e48\u0e32\u0e07", None))
        self.chill_specimen_radioButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e41\u0e0a\u0e48\u0e40\u0e22\u0e47\u0e19 (Chill)", None))
        self.freeze_specimen_radioButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e41\u0e0a\u0e48\u0e41\u0e02\u0e47\u0e07 (Freeze)", None))
        self.room_temp_specimen_radioButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e44\u0e21\u0e48\u0e41\u0e0a\u0e48 (Room Temperature)", None))
        self.speed_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2a\u0e16\u0e32\u0e19\u0e30\u0e15\u0e31\u0e27\u0e2d\u0e22\u0e48\u0e32\u0e07", None))
        self.normal_radioButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e1b\u0e01\u0e15\u0e34", None))
        self.most_argent_radioButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e14\u0e48\u0e27\u0e19\u0e17\u0e35\u0e48\u0e2a\u0e38\u0e14", None))
        self.save_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.back_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e22\u0e49\u0e2d\u0e19\u0e01\u0e25\u0e31\u0e1a", None))
        self.sample_lab_label.setText(QCoreApplication.translate("add_data_specimen", u"\u0e41\u0e25\u0e1b\u0e17\u0e35\u0e48\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23\u0e2a\u0e48\u0e07\u0e15\u0e23\u0e27\u0e08", None))
        self.Fungal_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e23\u0e32\u0e27\u0e34\u0e17\u0e22\u0e32 (Fungal)", None))
        self.Microbiology_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e08\u0e38\u0e25\u0e0a\u0e35\u0e27\u0e27\u0e34\u0e17\u0e22\u0e32 (Microbiology)", None))
        self.virology_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e44\u0e27\u0e23\u0e31\u0e2a\u0e27\u0e34\u0e17\u0e22\u0e32 (Virology)", None))
        self.Serology_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e0b\u0e35\u0e23\u0e31\u0e21\u0e27\u0e34\u0e17\u0e22\u0e32 (Serology)", None))
        self.Parasitology_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e1b\u0e23\u0e2a\u0e34\u0e15\u0e27\u0e34\u0e17\u0e22\u0e32 (Parasitology)", None))
        self.feed_analysis_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e40\u0e04\u0e21\u0e35\u0e27\u0e34\u0e40\u0e04\u0e23\u0e32\u0e30\u0e2b\u0e4c (Feed analysis)", None))
        self.water_quality_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e15\u0e23\u0e27\u0e08\u0e04\u0e38\u0e13\u0e20\u0e32\u0e1e\u0e19\u0e49\u0e33 (Water quality)", None))
        self.molecular_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e2d\u0e13\u0e39\u0e0a\u0e35\u0e27\u0e27\u0e34\u0e17\u0e22\u0e32 (Molecular biology)", None))
        self.hematology_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e42\u0e25\u0e2b\u0e34\u0e15\u0e27\u0e34\u0e17\u0e22\u0e32(Hematology)", None))
        self.Immunohistochemistry_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e1e\u0e22\u0e32\u0e18\u0e34\u0e27\u0e34\u0e17\u0e22\u0e32 (Immunohistochemistry)", None))
        self.surgical_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e1e\u0e22\u0e32\u0e18\u0e34\u0e27\u0e34\u0e17\u0e22\u0e32 (Surgical biopsy)", None))
        self.histopatology_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e1e\u0e22\u0e32\u0e18\u0e34\u0e27\u0e34\u0e17\u0e22\u0e32 (Histopathology)", None))
        self.Necropsy_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e1e\u0e22\u0e32\u0e18\u0e34\u0e27\u0e34\u0e17\u0e22\u0e32 (Necropsy)", None))
        self.cytology_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e1e\u0e22\u0e32\u0e18\u0e34\u0e27\u0e34\u0e17\u0e22\u0e32 (Cytology)", None))
        self.hittopathology_research_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e1e\u0e22\u0e32\u0e18\u0e34\u0e27\u0e34\u0e17\u0e22\u0e32 (Histopathology Research)", None))
        self.histopathology_research_recut_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e1e\u0e22\u0e32\u0e18\u0e34\u0e27\u0e34\u0e17\u0e22\u0e32 (Histopathology Research Recut)", None))
        self.food_safty_pushButton.setText(QCoreApplication.translate("add_data_specimen", u"\u0e2b\u0e49\u0e2d\u0e07\u0e1b\u0e0f\u0e34\u0e1a\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e2d\u0e32\u0e2b\u0e32\u0e23\u0e1b\u0e25\u0e2d\u0e14\u0e20\u0e31\u0e22 (Food safty)", None))
    # retranslateUi


# if __name__ == "__main__":
#     app = QApplication([])
#     specimen_UI = QMainWindow()
#     ui = Ui_add_data_specimen()
#     ui.setupUi(specimen_UI)
#     specimen_UI.show()
#     app.exec()