# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'F1_molecular_biology.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1900, 900)
        MainWindow.setMinimumSize(QSize(1900, 900))
        MainWindow.setMaximumSize(QSize(1900, 900))
        MainWindow.setStyleSheet(u"background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 140, 213, 255), stop:1 rgba(255, 229, 75, 255))")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.avian_frame = QFrame(self.centralwidget)
        self.avian_frame.setObjectName(u"avian_frame")
        self.avian_frame.setGeometry(QRect(2, 0, 411, 635))
        self.avian_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.avian_frame.setFrameShape(QFrame.Box)
        self.avian_frame.setFrameShadow(QFrame.Plain)
        self.avian_frame.setLineWidth(2)
        self.avian_label = QLabel(self.avian_frame)
        self.avian_label.setObjectName(u"avian_label")
        self.avian_label.setGeometry(QRect(5, 5, 307, 31))
        font = QFont()
        font.setFamilies([u"TH Niramit AS"])
        font.setPointSize(20)
        font.setBold(True)
        self.avian_label.setFont(font)
        self.avian_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.avian_label.setFrameShape(QFrame.Box)
        self.avian_label.setLineWidth(2)
        self.avian_label.setAlignment(Qt.AlignCenter)
        self.avian_sample_label = QLabel(self.avian_frame)
        self.avian_sample_label.setObjectName(u"avian_sample_label")
        self.avian_sample_label.setGeometry(QRect(315, 5, 91, 31))
        self.avian_sample_label.setFont(font)
        self.avian_sample_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.avian_sample_label.setFrameShape(QFrame.Box)
        self.avian_sample_label.setLineWidth(2)
        self.avian_sample_label.setAlignment(Qt.AlignCenter)
        self.avian_AI_1_checkBox = QCheckBox(self.avian_frame)
        self.avian_AI_1_checkBox.setObjectName(u"avian_AI_1_checkBox")
        self.avian_AI_1_checkBox.setGeometry(QRect(10, 50, 301, 20))
        font1 = QFont()
        font1.setFamilies([u"TH Niramit AS"])
        font1.setPointSize(19)
        font1.setBold(True)
        self.avian_AI_1_checkBox.setFont(font1)
        self.avian_AI_2_checkBox = QCheckBox(self.avian_frame)
        self.avian_AI_2_checkBox.setObjectName(u"avian_AI_2_checkBox")
        self.avian_AI_2_checkBox.setGeometry(QRect(10, 100, 301, 20))
        self.avian_AI_2_checkBox.setFont(font1)
        self.avian_ibv_checkBox = QCheckBox(self.avian_frame)
        self.avian_ibv_checkBox.setObjectName(u"avian_ibv_checkBox")
        self.avian_ibv_checkBox.setGeometry(QRect(10, 150, 271, 20))
        self.avian_ibv_checkBox.setFont(font1)
        self.avian_ibdv_checkBox = QCheckBox(self.avian_frame)
        self.avian_ibdv_checkBox.setObjectName(u"avian_ibdv_checkBox")
        self.avian_ibdv_checkBox.setGeometry(QRect(10, 200, 271, 20))
        self.avian_ibdv_checkBox.setFont(font1)
        self.avian_ilt_checkBox = QCheckBox(self.avian_frame)
        self.avian_ilt_checkBox.setObjectName(u"avian_ilt_checkBox")
        self.avian_ilt_checkBox.setGeometry(QRect(10, 250, 271, 20))
        self.avian_ilt_checkBox.setFont(font1)
        self.avian_ndv_checkBox = QCheckBox(self.avian_frame)
        self.avian_ndv_checkBox.setObjectName(u"avian_ndv_checkBox")
        self.avian_ndv_checkBox.setGeometry(QRect(10, 300, 271, 20))
        self.avian_ndv_checkBox.setFont(font1)
        self.avian_ndv_2_checkBox = QCheckBox(self.avian_frame)
        self.avian_ndv_2_checkBox.setObjectName(u"avian_ndv_2_checkBox")
        self.avian_ndv_2_checkBox.setGeometry(QRect(10, 350, 271, 20))
        self.avian_ndv_2_checkBox.setFont(font1)
        self.avian_pdd_checkBox = QCheckBox(self.avian_frame)
        self.avian_pdd_checkBox.setObjectName(u"avian_pdd_checkBox")
        self.avian_pdd_checkBox.setGeometry(QRect(10, 400, 271, 20))
        self.avian_pdd_checkBox.setFont(font1)
        self.avian_pbfdv_checkBox = QCheckBox(self.avian_frame)
        self.avian_pbfdv_checkBox.setObjectName(u"avian_pbfdv_checkBox")
        self.avian_pbfdv_checkBox.setGeometry(QRect(10, 450, 271, 20))
        self.avian_pbfdv_checkBox.setFont(font1)
        self.avian_chlamydia_checkBox = QCheckBox(self.avian_frame)
        self.avian_chlamydia_checkBox.setObjectName(u"avian_chlamydia_checkBox")
        self.avian_chlamydia_checkBox.setGeometry(QRect(10, 500, 271, 20))
        self.avian_chlamydia_checkBox.setFont(font1)
        self.avian_pasteurella_checkBox = QCheckBox(self.avian_frame)
        self.avian_pasteurella_checkBox.setObjectName(u"avian_pasteurella_checkBox")
        self.avian_pasteurella_checkBox.setGeometry(QRect(10, 550, 271, 20))
        self.avian_pasteurella_checkBox.setFont(font1)
        self.avian_mg_checkBox = QCheckBox(self.avian_frame)
        self.avian_mg_checkBox.setObjectName(u"avian_mg_checkBox")
        self.avian_mg_checkBox.setGeometry(QRect(10, 600, 271, 20))
        self.avian_mg_checkBox.setFont(font1)
        self.avian_AI_1_lineEdit = QLineEdit(self.avian_frame)
        self.avian_AI_1_lineEdit.setObjectName(u"avian_AI_1_lineEdit")
        self.avian_AI_1_lineEdit.setGeometry(QRect(320, 45, 81, 31))
        self.avian_AI_1_lineEdit.setFont(font)
        self.avian_AI_1_lineEdit.setAlignment(Qt.AlignCenter)
        self.avian_AI_2_lineEdit = QLineEdit(self.avian_frame)
        self.avian_AI_2_lineEdit.setObjectName(u"avian_AI_2_lineEdit")
        self.avian_AI_2_lineEdit.setGeometry(QRect(320, 90, 81, 31))
        self.avian_AI_2_lineEdit.setFont(font)
        self.avian_AI_2_lineEdit.setAlignment(Qt.AlignCenter)
        self.avian_ibv_lineEdit = QLineEdit(self.avian_frame)
        self.avian_ibv_lineEdit.setObjectName(u"avian_ibv_lineEdit")
        self.avian_ibv_lineEdit.setGeometry(QRect(320, 140, 81, 31))
        self.avian_ibv_lineEdit.setFont(font)
        self.avian_ibv_lineEdit.setAlignment(Qt.AlignCenter)
        self.avian_ibdv_lineEdit = QLineEdit(self.avian_frame)
        self.avian_ibdv_lineEdit.setObjectName(u"avian_ibdv_lineEdit")
        self.avian_ibdv_lineEdit.setGeometry(QRect(320, 190, 81, 31))
        self.avian_ibdv_lineEdit.setFont(font)
        self.avian_ibdv_lineEdit.setAlignment(Qt.AlignCenter)
        self.avian_ilt_lineEdit = QLineEdit(self.avian_frame)
        self.avian_ilt_lineEdit.setObjectName(u"avian_ilt_lineEdit")
        self.avian_ilt_lineEdit.setGeometry(QRect(320, 240, 81, 31))
        self.avian_ilt_lineEdit.setFont(font)
        self.avian_ilt_lineEdit.setAlignment(Qt.AlignCenter)
        self.avian_ndv_lineEdit = QLineEdit(self.avian_frame)
        self.avian_ndv_lineEdit.setObjectName(u"avian_ndv_lineEdit")
        self.avian_ndv_lineEdit.setGeometry(QRect(320, 290, 81, 31))
        self.avian_ndv_lineEdit.setFont(font)
        self.avian_ndv_lineEdit.setAlignment(Qt.AlignCenter)
        self.avian_ndv_2_lineEdit = QLineEdit(self.avian_frame)
        self.avian_ndv_2_lineEdit.setObjectName(u"avian_ndv_2_lineEdit")
        self.avian_ndv_2_lineEdit.setGeometry(QRect(320, 340, 81, 31))
        self.avian_ndv_2_lineEdit.setFont(font)
        self.avian_ndv_2_lineEdit.setAlignment(Qt.AlignCenter)
        self.avian_pdd_lineEdit = QLineEdit(self.avian_frame)
        self.avian_pdd_lineEdit.setObjectName(u"avian_pdd_lineEdit")
        self.avian_pdd_lineEdit.setGeometry(QRect(320, 390, 81, 31))
        self.avian_pdd_lineEdit.setFont(font)
        self.avian_pdd_lineEdit.setAlignment(Qt.AlignCenter)
        self.avian_pbfdv_lineEdit = QLineEdit(self.avian_frame)
        self.avian_pbfdv_lineEdit.setObjectName(u"avian_pbfdv_lineEdit")
        self.avian_pbfdv_lineEdit.setGeometry(QRect(320, 440, 81, 31))
        self.avian_pbfdv_lineEdit.setFont(font)
        self.avian_pbfdv_lineEdit.setAlignment(Qt.AlignCenter)
        self.avian_chlamydia_lineEdit = QLineEdit(self.avian_frame)
        self.avian_chlamydia_lineEdit.setObjectName(u"avian_chlamydia_lineEdit")
        self.avian_chlamydia_lineEdit.setGeometry(QRect(320, 490, 81, 31))
        self.avian_chlamydia_lineEdit.setFont(font)
        self.avian_chlamydia_lineEdit.setAlignment(Qt.AlignCenter)
        self.avian_pasteurella_lineEdit = QLineEdit(self.avian_frame)
        self.avian_pasteurella_lineEdit.setObjectName(u"avian_pasteurella_lineEdit")
        self.avian_pasteurella_lineEdit.setGeometry(QRect(320, 540, 81, 31))
        self.avian_pasteurella_lineEdit.setFont(font)
        self.avian_pasteurella_lineEdit.setAlignment(Qt.AlignCenter)
        self.avian_mg_lineEdit = QLineEdit(self.avian_frame)
        self.avian_mg_lineEdit.setObjectName(u"avian_mg_lineEdit")
        self.avian_mg_lineEdit.setGeometry(QRect(320, 590, 81, 31))
        self.avian_mg_lineEdit.setFont(font)
        self.avian_mg_lineEdit.setAlignment(Qt.AlignCenter)
        self.avian_line = QFrame(self.avian_frame)
        self.avian_line.setObjectName(u"avian_line")
        self.avian_line.setGeometry(QRect(305, 45, 16, 581))
        self.avian_line.setFrameShape(QFrame.VLine)
        self.avian_line.setFrameShadow(QFrame.Sunken)
        self.avian_line.raise_()
        self.avian_label.raise_()
        self.avian_sample_label.raise_()
        self.avian_AI_1_checkBox.raise_()
        self.avian_AI_2_checkBox.raise_()
        self.avian_ibv_checkBox.raise_()
        self.avian_ibdv_checkBox.raise_()
        self.avian_ilt_checkBox.raise_()
        self.avian_ndv_checkBox.raise_()
        self.avian_ndv_2_checkBox.raise_()
        self.avian_pdd_checkBox.raise_()
        self.avian_pbfdv_checkBox.raise_()
        self.avian_chlamydia_checkBox.raise_()
        self.avian_pasteurella_checkBox.raise_()
        self.avian_mg_checkBox.raise_()
        self.avian_AI_1_lineEdit.raise_()
        self.avian_AI_2_lineEdit.raise_()
        self.avian_ibv_lineEdit.raise_()
        self.avian_ibdv_lineEdit.raise_()
        self.avian_ilt_lineEdit.raise_()
        self.avian_ndv_lineEdit.raise_()
        self.avian_ndv_2_lineEdit.raise_()
        self.avian_pdd_lineEdit.raise_()
        self.avian_pbfdv_lineEdit.raise_()
        self.avian_chlamydia_lineEdit.raise_()
        self.avian_pasteurella_lineEdit.raise_()
        self.avian_mg_lineEdit.raise_()
        self.feline_frame = QFrame(self.centralwidget)
        self.feline_frame.setObjectName(u"feline_frame")
        self.feline_frame.setGeometry(QRect(2, 640, 411, 235))
        self.feline_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.feline_frame.setFrameShape(QFrame.Box)
        self.feline_frame.setFrameShadow(QFrame.Plain)
        self.feline_frame.setLineWidth(2)
        self.feline_label = QLabel(self.feline_frame)
        self.feline_label.setObjectName(u"feline_label")
        self.feline_label.setGeometry(QRect(5, 5, 307, 31))
        self.feline_label.setFont(font)
        self.feline_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.feline_label.setFrameShape(QFrame.Box)
        self.feline_label.setLineWidth(2)
        self.feline_label.setAlignment(Qt.AlignCenter)
        self.feline_sample_label = QLabel(self.feline_frame)
        self.feline_sample_label.setObjectName(u"feline_sample_label")
        self.feline_sample_label.setGeometry(QRect(315, 5, 91, 31))
        self.feline_sample_label.setFont(font)
        self.feline_sample_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.feline_sample_label.setFrameShape(QFrame.Box)
        self.feline_sample_label.setLineWidth(2)
        self.feline_sample_label.setAlignment(Qt.AlignCenter)
        self.feline_felv_checkBox = QCheckBox(self.feline_frame)
        self.feline_felv_checkBox.setObjectName(u"feline_felv_checkBox")
        self.feline_felv_checkBox.setGeometry(QRect(10, 50, 301, 20))
        self.feline_felv_checkBox.setFont(font1)
        self.feline_fip_checkBox = QCheckBox(self.feline_frame)
        self.feline_fip_checkBox.setObjectName(u"feline_fip_checkBox")
        self.feline_fip_checkBox.setGeometry(QRect(10, 100, 301, 20))
        self.feline_fip_checkBox.setFont(font1)
        self.feline_fiv_checkBox = QCheckBox(self.feline_frame)
        self.feline_fiv_checkBox.setObjectName(u"feline_fiv_checkBox")
        self.feline_fiv_checkBox.setGeometry(QRect(10, 150, 271, 20))
        self.feline_fiv_checkBox.setFont(font1)
        self.feline_panleukopenia_checkBox = QCheckBox(self.feline_frame)
        self.feline_panleukopenia_checkBox.setObjectName(u"feline_panleukopenia_checkBox")
        self.feline_panleukopenia_checkBox.setGeometry(QRect(10, 200, 271, 20))
        self.feline_panleukopenia_checkBox.setFont(font1)
        self.feline_felv_lineEdit = QLineEdit(self.feline_frame)
        self.feline_felv_lineEdit.setObjectName(u"feline_felv_lineEdit")
        self.feline_felv_lineEdit.setGeometry(QRect(320, 45, 81, 31))
        self.feline_felv_lineEdit.setFont(font)
        self.feline_felv_lineEdit.setAlignment(Qt.AlignCenter)
        self.feline_fip_lineEdit = QLineEdit(self.feline_frame)
        self.feline_fip_lineEdit.setObjectName(u"feline_fip_lineEdit")
        self.feline_fip_lineEdit.setGeometry(QRect(320, 90, 81, 31))
        self.feline_fip_lineEdit.setFont(font)
        self.feline_fip_lineEdit.setAlignment(Qt.AlignCenter)
        self.feline_fiv_lineEdit = QLineEdit(self.feline_frame)
        self.feline_fiv_lineEdit.setObjectName(u"feline_fiv_lineEdit")
        self.feline_fiv_lineEdit.setGeometry(QRect(320, 140, 81, 31))
        self.feline_fiv_lineEdit.setFont(font)
        self.feline_fiv_lineEdit.setAlignment(Qt.AlignCenter)
        self.feline_panleukopenia_lineEdit = QLineEdit(self.feline_frame)
        self.feline_panleukopenia_lineEdit.setObjectName(u"feline_panleukopenia_lineEdit")
        self.feline_panleukopenia_lineEdit.setGeometry(QRect(320, 190, 81, 31))
        self.feline_panleukopenia_lineEdit.setFont(font)
        self.feline_panleukopenia_lineEdit.setAlignment(Qt.AlignCenter)
        self.feline_line = QFrame(self.feline_frame)
        self.feline_line.setObjectName(u"feline_line")
        self.feline_line.setGeometry(QRect(305, 45, 16, 181))
        self.feline_line.setFrameShape(QFrame.VLine)
        self.feline_line.setFrameShadow(QFrame.Sunken)
        self.feline_line.raise_()
        self.feline_label.raise_()
        self.feline_sample_label.raise_()
        self.feline_felv_checkBox.raise_()
        self.feline_fip_checkBox.raise_()
        self.feline_fiv_checkBox.raise_()
        self.feline_panleukopenia_checkBox.raise_()
        self.feline_felv_lineEdit.raise_()
        self.feline_fip_lineEdit.raise_()
        self.feline_fiv_lineEdit.raise_()
        self.feline_panleukopenia_lineEdit.raise_()
        self.elephant_frame = QFrame(self.centralwidget)
        self.elephant_frame.setObjectName(u"elephant_frame")
        self.elephant_frame.setGeometry(QRect(415, 0, 411, 285))
        self.elephant_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.elephant_frame.setFrameShape(QFrame.Box)
        self.elephant_frame.setFrameShadow(QFrame.Plain)
        self.elephant_frame.setLineWidth(2)
        self.elephant_label = QLabel(self.elephant_frame)
        self.elephant_label.setObjectName(u"elephant_label")
        self.elephant_label.setGeometry(QRect(5, 5, 307, 31))
        self.elephant_label.setFont(font)
        self.elephant_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.elephant_label.setFrameShape(QFrame.Box)
        self.elephant_label.setLineWidth(2)
        self.elephant_label.setAlignment(Qt.AlignCenter)
        self.elephant_sample_label = QLabel(self.elephant_frame)
        self.elephant_sample_label.setObjectName(u"elephant_sample_label")
        self.elephant_sample_label.setGeometry(QRect(315, 5, 91, 31))
        self.elephant_sample_label.setFont(font)
        self.elephant_sample_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.elephant_sample_label.setFrameShape(QFrame.Box)
        self.elephant_sample_label.setLineWidth(2)
        self.elephant_sample_label.setAlignment(Qt.AlignCenter)
        self.elephant_eehv1a_4_checkBox = QCheckBox(self.elephant_frame)
        self.elephant_eehv1a_4_checkBox.setObjectName(u"elephant_eehv1a_4_checkBox")
        self.elephant_eehv1a_4_checkBox.setGeometry(QRect(10, 50, 301, 20))
        self.elephant_eehv1a_4_checkBox.setFont(font1)
        self.elephant_eehv1a_1_checkBox = QCheckBox(self.elephant_frame)
        self.elephant_eehv1a_1_checkBox.setObjectName(u"elephant_eehv1a_1_checkBox")
        self.elephant_eehv1a_1_checkBox.setGeometry(QRect(10, 100, 301, 20))
        self.elephant_eehv1a_1_checkBox.setFont(font1)
        self.elephant_eehv1a_2_checkBox = QCheckBox(self.elephant_frame)
        self.elephant_eehv1a_2_checkBox.setObjectName(u"elephant_eehv1a_2_checkBox")
        self.elephant_eehv1a_2_checkBox.setGeometry(QRect(10, 150, 271, 20))
        self.elephant_eehv1a_2_checkBox.setFont(font1)
        self.elephant_eehv4_1_checkBox = QCheckBox(self.elephant_frame)
        self.elephant_eehv4_1_checkBox.setObjectName(u"elephant_eehv4_1_checkBox")
        self.elephant_eehv4_1_checkBox.setGeometry(QRect(10, 200, 271, 20))
        self.elephant_eehv4_1_checkBox.setFont(font1)
        self.elephant_eehv4_2_checkBox = QCheckBox(self.elephant_frame)
        self.elephant_eehv4_2_checkBox.setObjectName(u"elephant_eehv4_2_checkBox")
        self.elephant_eehv4_2_checkBox.setGeometry(QRect(10, 250, 271, 20))
        self.elephant_eehv4_2_checkBox.setFont(font1)
        self.elephant_eehv1a_4_lineEdit = QLineEdit(self.elephant_frame)
        self.elephant_eehv1a_4_lineEdit.setObjectName(u"elephant_eehv1a_4_lineEdit")
        self.elephant_eehv1a_4_lineEdit.setGeometry(QRect(320, 45, 81, 31))
        self.elephant_eehv1a_4_lineEdit.setFont(font)
        self.elephant_eehv1a_4_lineEdit.setAlignment(Qt.AlignCenter)
        self.elephant_eehv1a_1_lineEdit = QLineEdit(self.elephant_frame)
        self.elephant_eehv1a_1_lineEdit.setObjectName(u"elephant_eehv1a_1_lineEdit")
        self.elephant_eehv1a_1_lineEdit.setGeometry(QRect(320, 90, 81, 31))
        self.elephant_eehv1a_1_lineEdit.setFont(font)
        self.elephant_eehv1a_1_lineEdit.setAlignment(Qt.AlignCenter)
        self.elephant_eehv1a_2_lineEdit = QLineEdit(self.elephant_frame)
        self.elephant_eehv1a_2_lineEdit.setObjectName(u"elephant_eehv1a_2_lineEdit")
        self.elephant_eehv1a_2_lineEdit.setGeometry(QRect(320, 140, 81, 31))
        self.elephant_eehv1a_2_lineEdit.setFont(font)
        self.elephant_eehv1a_2_lineEdit.setAlignment(Qt.AlignCenter)
        self.elephant_eehv4_1_lineEdit = QLineEdit(self.elephant_frame)
        self.elephant_eehv4_1_lineEdit.setObjectName(u"elephant_eehv4_1_lineEdit")
        self.elephant_eehv4_1_lineEdit.setGeometry(QRect(320, 190, 81, 31))
        self.elephant_eehv4_1_lineEdit.setFont(font)
        self.elephant_eehv4_1_lineEdit.setAlignment(Qt.AlignCenter)
        self.elephant_eehv4_2_lineEdit = QLineEdit(self.elephant_frame)
        self.elephant_eehv4_2_lineEdit.setObjectName(u"elephant_eehv4_2_lineEdit")
        self.elephant_eehv4_2_lineEdit.setGeometry(QRect(320, 240, 81, 31))
        self.elephant_eehv4_2_lineEdit.setFont(font)
        self.elephant_eehv4_2_lineEdit.setAlignment(Qt.AlignCenter)
        self.elephant_line = QFrame(self.elephant_frame)
        self.elephant_line.setObjectName(u"elephant_line")
        self.elephant_line.setGeometry(QRect(305, 45, 16, 231))
        self.elephant_line.setFrameShape(QFrame.VLine)
        self.elephant_line.setFrameShadow(QFrame.Sunken)
        self.elephant_line.raise_()
        self.elephant_label.raise_()
        self.elephant_sample_label.raise_()
        self.elephant_eehv1a_4_checkBox.raise_()
        self.elephant_eehv1a_1_checkBox.raise_()
        self.elephant_eehv1a_2_checkBox.raise_()
        self.elephant_eehv4_1_checkBox.raise_()
        self.elephant_eehv4_2_checkBox.raise_()
        self.elephant_eehv1a_4_lineEdit.raise_()
        self.elephant_eehv1a_1_lineEdit.raise_()
        self.elephant_eehv1a_2_lineEdit.raise_()
        self.elephant_eehv4_1_lineEdit.raise_()
        self.elephant_eehv4_2_lineEdit.raise_()
        self.bovine_frame = QFrame(self.centralwidget)
        self.bovine_frame.setObjectName(u"bovine_frame")
        self.bovine_frame.setGeometry(QRect(415, 290, 411, 241))
        self.bovine_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.bovine_frame.setFrameShape(QFrame.Box)
        self.bovine_frame.setFrameShadow(QFrame.Plain)
        self.bovine_frame.setLineWidth(2)
        self.bovine_label = QLabel(self.bovine_frame)
        self.bovine_label.setObjectName(u"bovine_label")
        self.bovine_label.setGeometry(QRect(5, 5, 307, 31))
        self.bovine_label.setFont(font)
        self.bovine_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.bovine_label.setFrameShape(QFrame.Box)
        self.bovine_label.setLineWidth(2)
        self.bovine_label.setAlignment(Qt.AlignCenter)
        self.bovine_sample_label = QLabel(self.bovine_frame)
        self.bovine_sample_label.setObjectName(u"bovine_sample_label")
        self.bovine_sample_label.setGeometry(QRect(315, 5, 91, 31))
        self.bovine_sample_label.setFont(font)
        self.bovine_sample_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.bovine_sample_label.setFrameShape(QFrame.Box)
        self.bovine_sample_label.setLineWidth(2)
        self.bovine_sample_label.setAlignment(Qt.AlignCenter)
        self.bovin_blv_checkBox = QCheckBox(self.bovine_frame)
        self.bovin_blv_checkBox.setObjectName(u"bovin_blv_checkBox")
        self.bovin_blv_checkBox.setGeometry(QRect(10, 50, 301, 20))
        self.bovin_blv_checkBox.setFont(font1)
        self.bovin_fmdv_checkBox = QCheckBox(self.bovine_frame)
        self.bovin_fmdv_checkBox.setObjectName(u"bovin_fmdv_checkBox")
        self.bovin_fmdv_checkBox.setGeometry(QRect(10, 100, 301, 20))
        self.bovin_fmdv_checkBox.setFont(font1)
        self.bovin_lsdv_checkBox = QCheckBox(self.bovine_frame)
        self.bovin_lsdv_checkBox.setObjectName(u"bovin_lsdv_checkBox")
        self.bovin_lsdv_checkBox.setGeometry(QRect(10, 150, 271, 20))
        self.bovin_lsdv_checkBox.setFont(font1)
        self.bovin_bvd_checkBox = QCheckBox(self.bovine_frame)
        self.bovin_bvd_checkBox.setObjectName(u"bovin_bvd_checkBox")
        self.bovin_bvd_checkBox.setGeometry(QRect(10, 200, 271, 20))
        self.bovin_bvd_checkBox.setFont(font1)
        self.bovin_blv_lineEdit = QLineEdit(self.bovine_frame)
        self.bovin_blv_lineEdit.setObjectName(u"bovin_blv_lineEdit")
        self.bovin_blv_lineEdit.setGeometry(QRect(320, 45, 81, 31))
        self.bovin_blv_lineEdit.setFont(font)
        self.bovin_blv_lineEdit.setAlignment(Qt.AlignCenter)
        self.bovin_fmdv_lineEdit = QLineEdit(self.bovine_frame)
        self.bovin_fmdv_lineEdit.setObjectName(u"bovin_fmdv_lineEdit")
        self.bovin_fmdv_lineEdit.setGeometry(QRect(320, 90, 81, 31))
        self.bovin_fmdv_lineEdit.setFont(font)
        self.bovin_fmdv_lineEdit.setAlignment(Qt.AlignCenter)
        self.bovin_lsdv_lineEdit = QLineEdit(self.bovine_frame)
        self.bovin_lsdv_lineEdit.setObjectName(u"bovin_lsdv_lineEdit")
        self.bovin_lsdv_lineEdit.setGeometry(QRect(320, 140, 81, 31))
        self.bovin_lsdv_lineEdit.setFont(font)
        self.bovin_lsdv_lineEdit.setAlignment(Qt.AlignCenter)
        self.bovin_bvd_lineEdit = QLineEdit(self.bovine_frame)
        self.bovin_bvd_lineEdit.setObjectName(u"bovin_bvd_lineEdit")
        self.bovin_bvd_lineEdit.setGeometry(QRect(320, 190, 81, 31))
        self.bovin_bvd_lineEdit.setFont(font)
        self.bovin_bvd_lineEdit.setAlignment(Qt.AlignCenter)
        self.bovine_line = QFrame(self.bovine_frame)
        self.bovine_line.setObjectName(u"bovine_line")
        self.bovine_line.setGeometry(QRect(305, 45, 16, 181))
        self.bovine_line.setFrameShape(QFrame.VLine)
        self.bovine_line.setFrameShadow(QFrame.Sunken)
        self.bovine_line.raise_()
        self.bovine_label.raise_()
        self.bovine_sample_label.raise_()
        self.bovin_blv_checkBox.raise_()
        self.bovin_fmdv_checkBox.raise_()
        self.bovin_lsdv_checkBox.raise_()
        self.bovin_bvd_checkBox.raise_()
        self.bovin_blv_lineEdit.raise_()
        self.bovin_fmdv_lineEdit.raise_()
        self.bovin_lsdv_lineEdit.raise_()
        self.bovin_bvd_lineEdit.raise_()
        self.equine_frame = QFrame(self.centralwidget)
        self.equine_frame.setObjectName(u"equine_frame")
        self.equine_frame.setGeometry(QRect(415, 537, 411, 141))
        self.equine_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.equine_frame.setFrameShape(QFrame.Box)
        self.equine_frame.setFrameShadow(QFrame.Plain)
        self.equine_frame.setLineWidth(2)
        self.equine_label = QLabel(self.equine_frame)
        self.equine_label.setObjectName(u"equine_label")
        self.equine_label.setGeometry(QRect(5, 5, 307, 31))
        self.equine_label.setFont(font)
        self.equine_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.equine_label.setFrameShape(QFrame.Box)
        self.equine_label.setLineWidth(2)
        self.equine_label.setAlignment(Qt.AlignCenter)
        self.equine_saple_label = QLabel(self.equine_frame)
        self.equine_saple_label.setObjectName(u"equine_saple_label")
        self.equine_saple_label.setGeometry(QRect(315, 5, 91, 31))
        self.equine_saple_label.setFont(font)
        self.equine_saple_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.equine_saple_label.setFrameShape(QFrame.Box)
        self.equine_saple_label.setLineWidth(2)
        self.equine_saple_label.setAlignment(Qt.AlignCenter)
        self.equine_ehv_checkBox = QCheckBox(self.equine_frame)
        self.equine_ehv_checkBox.setObjectName(u"equine_ehv_checkBox")
        self.equine_ehv_checkBox.setGeometry(QRect(10, 50, 301, 20))
        self.equine_ehv_checkBox.setFont(font1)
        self.equine_ahs_checkBox = QCheckBox(self.equine_frame)
        self.equine_ahs_checkBox.setObjectName(u"equine_ahs_checkBox")
        self.equine_ahs_checkBox.setGeometry(QRect(10, 100, 301, 20))
        self.equine_ahs_checkBox.setFont(font1)
        self.equine_ehv_lineEdit = QLineEdit(self.equine_frame)
        self.equine_ehv_lineEdit.setObjectName(u"equine_ehv_lineEdit")
        self.equine_ehv_lineEdit.setGeometry(QRect(320, 45, 81, 31))
        self.equine_ehv_lineEdit.setFont(font)
        self.equine_ehv_lineEdit.setAlignment(Qt.AlignCenter)
        self.equine_ahs_lineEdit = QLineEdit(self.equine_frame)
        self.equine_ahs_lineEdit.setObjectName(u"equine_ahs_lineEdit")
        self.equine_ahs_lineEdit.setGeometry(QRect(320, 90, 81, 31))
        self.equine_ahs_lineEdit.setFont(font)
        self.equine_ahs_lineEdit.setAlignment(Qt.AlignCenter)
        self.equine_line = QFrame(self.equine_frame)
        self.equine_line.setObjectName(u"equine_line")
        self.equine_line.setGeometry(QRect(305, 45, 16, 91))
        self.equine_line.setFrameShape(QFrame.VLine)
        self.equine_line.setFrameShadow(QFrame.Sunken)
        self.equine_line.raise_()
        self.equine_label.raise_()
        self.equine_saple_label.raise_()
        self.equine_ehv_checkBox.raise_()
        self.equine_ahs_checkBox.raise_()
        self.equine_ehv_lineEdit.raise_()
        self.equine_ahs_lineEdit.raise_()
        self.aqutic_animal_frame = QFrame(self.centralwidget)
        self.aqutic_animal_frame.setObjectName(u"aqutic_animal_frame")
        self.aqutic_animal_frame.setGeometry(QRect(415, 685, 411, 191))
        self.aqutic_animal_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.aqutic_animal_frame.setFrameShape(QFrame.Box)
        self.aqutic_animal_frame.setFrameShadow(QFrame.Plain)
        self.aqutic_animal_frame.setLineWidth(2)
        self.aquatic_animal_label = QLabel(self.aqutic_animal_frame)
        self.aquatic_animal_label.setObjectName(u"aquatic_animal_label")
        self.aquatic_animal_label.setGeometry(QRect(5, 5, 307, 31))
        self.aquatic_animal_label.setFont(font)
        self.aquatic_animal_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.aquatic_animal_label.setFrameShape(QFrame.Box)
        self.aquatic_animal_label.setLineWidth(2)
        self.aquatic_animal_label.setAlignment(Qt.AlignCenter)
        self.aquatic_animal_sample_label = QLabel(self.aqutic_animal_frame)
        self.aquatic_animal_sample_label.setObjectName(u"aquatic_animal_sample_label")
        self.aquatic_animal_sample_label.setGeometry(QRect(315, 5, 91, 31))
        self.aquatic_animal_sample_label.setFont(font)
        self.aquatic_animal_sample_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.aquatic_animal_sample_label.setFrameShape(QFrame.Box)
        self.aquatic_animal_sample_label.setLineWidth(2)
        self.aquatic_animal_sample_label.setAlignment(Qt.AlignCenter)
        self.aquatic_animal_khv_checkBox = QCheckBox(self.aqutic_animal_frame)
        self.aquatic_animal_khv_checkBox.setObjectName(u"aquatic_animal_khv_checkBox")
        self.aquatic_animal_khv_checkBox.setGeometry(QRect(10, 50, 301, 20))
        self.aquatic_animal_khv_checkBox.setFont(font1)
        self.aquatic_animal_tilv_checkBox = QCheckBox(self.aqutic_animal_frame)
        self.aquatic_animal_tilv_checkBox.setObjectName(u"aquatic_animal_tilv_checkBox")
        self.aquatic_animal_tilv_checkBox.setGeometry(QRect(10, 100, 301, 20))
        self.aquatic_animal_tilv_checkBox.setFont(font1)
        self.aquatic_animal_cev_checkBox = QCheckBox(self.aqutic_animal_frame)
        self.aquatic_animal_cev_checkBox.setObjectName(u"aquatic_animal_cev_checkBox")
        self.aquatic_animal_cev_checkBox.setGeometry(QRect(10, 150, 271, 20))
        self.aquatic_animal_cev_checkBox.setFont(font1)
        self.aquatic_animal_khv_lineEdit = QLineEdit(self.aqutic_animal_frame)
        self.aquatic_animal_khv_lineEdit.setObjectName(u"aquatic_animal_khv_lineEdit")
        self.aquatic_animal_khv_lineEdit.setGeometry(QRect(320, 45, 81, 31))
        self.aquatic_animal_khv_lineEdit.setFont(font)
        self.aquatic_animal_khv_lineEdit.setAlignment(Qt.AlignCenter)
        self.aquatic_animal_tilv_lineEdit = QLineEdit(self.aqutic_animal_frame)
        self.aquatic_animal_tilv_lineEdit.setObjectName(u"aquatic_animal_tilv_lineEdit")
        self.aquatic_animal_tilv_lineEdit.setGeometry(QRect(320, 90, 81, 31))
        self.aquatic_animal_tilv_lineEdit.setFont(font)
        self.aquatic_animal_tilv_lineEdit.setAlignment(Qt.AlignCenter)
        self.aquatic_animal_cev_lineEdit = QLineEdit(self.aqutic_animal_frame)
        self.aquatic_animal_cev_lineEdit.setObjectName(u"aquatic_animal_cev_lineEdit")
        self.aquatic_animal_cev_lineEdit.setGeometry(QRect(320, 140, 81, 31))
        self.aquatic_animal_cev_lineEdit.setFont(font)
        self.aquatic_animal_cev_lineEdit.setAlignment(Qt.AlignCenter)
        self.aquatic_animal_line = QFrame(self.aqutic_animal_frame)
        self.aquatic_animal_line.setObjectName(u"aquatic_animal_line")
        self.aquatic_animal_line.setGeometry(QRect(305, 45, 16, 131))
        self.aquatic_animal_line.setFrameShape(QFrame.VLine)
        self.aquatic_animal_line.setFrameShadow(QFrame.Sunken)
        self.aquatic_animal_line.raise_()
        self.aquatic_animal_label.raise_()
        self.aquatic_animal_sample_label.raise_()
        self.aquatic_animal_khv_checkBox.raise_()
        self.aquatic_animal_tilv_checkBox.raise_()
        self.aquatic_animal_cev_checkBox.raise_()
        self.aquatic_animal_khv_lineEdit.raise_()
        self.aquatic_animal_tilv_lineEdit.raise_()
        self.aquatic_animal_cev_lineEdit.raise_()
        self.blood_1_frame = QFrame(self.centralwidget)
        self.blood_1_frame.setObjectName(u"blood_1_frame")
        self.blood_1_frame.setGeometry(QRect(828, 0, 411, 441))
        self.blood_1_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.blood_1_frame.setFrameShape(QFrame.Box)
        self.blood_1_frame.setFrameShadow(QFrame.Plain)
        self.blood_1_frame.setLineWidth(2)
        self.blood_1_label = QLabel(self.blood_1_frame)
        self.blood_1_label.setObjectName(u"blood_1_label")
        self.blood_1_label.setGeometry(QRect(5, 5, 307, 31))
        self.blood_1_label.setFont(font)
        self.blood_1_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.blood_1_label.setFrameShape(QFrame.Box)
        self.blood_1_label.setLineWidth(2)
        self.blood_1_label.setAlignment(Qt.AlignCenter)
        self.blood_1_sample_label = QLabel(self.blood_1_frame)
        self.blood_1_sample_label.setObjectName(u"blood_1_sample_label")
        self.blood_1_sample_label.setGeometry(QRect(315, 5, 91, 31))
        self.blood_1_sample_label.setFont(font)
        self.blood_1_sample_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.blood_1_sample_label.setFrameShape(QFrame.Box)
        self.blood_1_sample_label.setLineWidth(2)
        self.blood_1_sample_label.setAlignment(Qt.AlignCenter)
        self.blood_1_ana_checkBox = QCheckBox(self.blood_1_frame)
        self.blood_1_ana_checkBox.setObjectName(u"blood_1_ana_checkBox")
        self.blood_1_ana_checkBox.setGeometry(QRect(10, 50, 301, 20))
        self.blood_1_ana_checkBox.setFont(font1)
        self.blood_1_babe_checkBox = QCheckBox(self.blood_1_frame)
        self.blood_1_babe_checkBox.setObjectName(u"blood_1_babe_checkBox")
        self.blood_1_babe_checkBox.setGeometry(QRect(10, 100, 301, 20))
        self.blood_1_babe_checkBox.setFont(font1)
        self.blood_1_ehr_checkBox = QCheckBox(self.blood_1_frame)
        self.blood_1_ehr_checkBox.setObjectName(u"blood_1_ehr_checkBox")
        self.blood_1_ehr_checkBox.setGeometry(QRect(10, 150, 271, 20))
        self.blood_1_ehr_checkBox.setFont(font1)
        self.blood_1_the_checkBox = QCheckBox(self.blood_1_frame)
        self.blood_1_the_checkBox.setObjectName(u"blood_1_the_checkBox")
        self.blood_1_the_checkBox.setGeometry(QRect(10, 200, 271, 20))
        self.blood_1_the_checkBox.setFont(font1)
        self.blood_1_haem_checkBox = QCheckBox(self.blood_1_frame)
        self.blood_1_haem_checkBox.setObjectName(u"blood_1_haem_checkBox")
        self.blood_1_haem_checkBox.setGeometry(QRect(10, 250, 271, 20))
        self.blood_1_haem_checkBox.setFont(font1)
        self.blood_1_ecanis_checkBox = QCheckBox(self.blood_1_frame)
        self.blood_1_ecanis_checkBox.setObjectName(u"blood_1_ecanis_checkBox")
        self.blood_1_ecanis_checkBox.setGeometry(QRect(10, 300, 271, 20))
        self.blood_1_ecanis_checkBox.setFont(font1)
        self.blood_1_leis_checkBox = QCheckBox(self.blood_1_frame)
        self.blood_1_leis_checkBox.setObjectName(u"blood_1_leis_checkBox")
        self.blood_1_leis_checkBox.setGeometry(QRect(10, 350, 271, 20))
        self.blood_1_leis_checkBox.setFont(font1)
        self.blood_1_try_checkBox = QCheckBox(self.blood_1_frame)
        self.blood_1_try_checkBox.setObjectName(u"blood_1_try_checkBox")
        self.blood_1_try_checkBox.setGeometry(QRect(10, 400, 271, 20))
        self.blood_1_try_checkBox.setFont(font1)
        self.blood_1_ana_lineEdit = QLineEdit(self.blood_1_frame)
        self.blood_1_ana_lineEdit.setObjectName(u"blood_1_ana_lineEdit")
        self.blood_1_ana_lineEdit.setGeometry(QRect(320, 45, 81, 31))
        self.blood_1_ana_lineEdit.setFont(font)
        self.blood_1_ana_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_1_babe_lineEdit = QLineEdit(self.blood_1_frame)
        self.blood_1_babe_lineEdit.setObjectName(u"blood_1_babe_lineEdit")
        self.blood_1_babe_lineEdit.setGeometry(QRect(320, 90, 81, 31))
        self.blood_1_babe_lineEdit.setFont(font)
        self.blood_1_babe_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_1_ehr_lineEdit = QLineEdit(self.blood_1_frame)
        self.blood_1_ehr_lineEdit.setObjectName(u"blood_1_ehr_lineEdit")
        self.blood_1_ehr_lineEdit.setGeometry(QRect(320, 140, 81, 31))
        self.blood_1_ehr_lineEdit.setFont(font)
        self.blood_1_ehr_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_1_the_lineEdit = QLineEdit(self.blood_1_frame)
        self.blood_1_the_lineEdit.setObjectName(u"blood_1_the_lineEdit")
        self.blood_1_the_lineEdit.setGeometry(QRect(320, 190, 81, 31))
        self.blood_1_the_lineEdit.setFont(font)
        self.blood_1_the_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_1_haem_lineEdit = QLineEdit(self.blood_1_frame)
        self.blood_1_haem_lineEdit.setObjectName(u"blood_1_haem_lineEdit")
        self.blood_1_haem_lineEdit.setGeometry(QRect(320, 240, 81, 31))
        self.blood_1_haem_lineEdit.setFont(font)
        self.blood_1_haem_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_1_ecanis_lineEdit = QLineEdit(self.blood_1_frame)
        self.blood_1_ecanis_lineEdit.setObjectName(u"blood_1_ecanis_lineEdit")
        self.blood_1_ecanis_lineEdit.setGeometry(QRect(320, 290, 81, 31))
        self.blood_1_ecanis_lineEdit.setFont(font)
        self.blood_1_ecanis_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_1_leis_lineEdit = QLineEdit(self.blood_1_frame)
        self.blood_1_leis_lineEdit.setObjectName(u"blood_1_leis_lineEdit")
        self.blood_1_leis_lineEdit.setGeometry(QRect(320, 340, 81, 31))
        self.blood_1_leis_lineEdit.setFont(font)
        self.blood_1_leis_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_1_try_lineEdit = QLineEdit(self.blood_1_frame)
        self.blood_1_try_lineEdit.setObjectName(u"blood_1_try_lineEdit")
        self.blood_1_try_lineEdit.setGeometry(QRect(320, 390, 81, 31))
        self.blood_1_try_lineEdit.setFont(font)
        self.blood_1_try_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_1_line = QFrame(self.blood_1_frame)
        self.blood_1_line.setObjectName(u"blood_1_line")
        self.blood_1_line.setGeometry(QRect(305, 45, 16, 381))
        self.blood_1_line.setFrameShape(QFrame.VLine)
        self.blood_1_line.setFrameShadow(QFrame.Sunken)
        self.blood_1_line.raise_()
        self.blood_1_label.raise_()
        self.blood_1_sample_label.raise_()
        self.blood_1_ana_checkBox.raise_()
        self.blood_1_babe_checkBox.raise_()
        self.blood_1_ehr_checkBox.raise_()
        self.blood_1_the_checkBox.raise_()
        self.blood_1_haem_checkBox.raise_()
        self.blood_1_ecanis_checkBox.raise_()
        self.blood_1_leis_checkBox.raise_()
        self.blood_1_try_checkBox.raise_()
        self.blood_1_ana_lineEdit.raise_()
        self.blood_1_babe_lineEdit.raise_()
        self.blood_1_ehr_lineEdit.raise_()
        self.blood_1_the_lineEdit.raise_()
        self.blood_1_haem_lineEdit.raise_()
        self.blood_1_ecanis_lineEdit.raise_()
        self.blood_1_leis_lineEdit.raise_()
        self.blood_1_try_lineEdit.raise_()
        self.blood_2_frame = QFrame(self.centralwidget)
        self.blood_2_frame.setObjectName(u"blood_2_frame")
        self.blood_2_frame.setGeometry(QRect(828, 445, 411, 431))
        self.blood_2_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.blood_2_frame.setFrameShape(QFrame.Box)
        self.blood_2_frame.setFrameShadow(QFrame.Plain)
        self.blood_2_frame.setLineWidth(2)
        self.blood_2_label = QLabel(self.blood_2_frame)
        self.blood_2_label.setObjectName(u"blood_2_label")
        self.blood_2_label.setGeometry(QRect(5, 5, 307, 31))
        self.blood_2_label.setFont(font)
        self.blood_2_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.blood_2_label.setFrameShape(QFrame.Box)
        self.blood_2_label.setLineWidth(2)
        self.blood_2_label.setAlignment(Qt.AlignCenter)
        self.blood_2_sample_label = QLabel(self.blood_2_frame)
        self.blood_2_sample_label.setObjectName(u"blood_2_sample_label")
        self.blood_2_sample_label.setGeometry(QRect(315, 5, 91, 31))
        self.blood_2_sample_label.setFont(font)
        self.blood_2_sample_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.blood_2_sample_label.setFrameShape(QFrame.Box)
        self.blood_2_sample_label.setLineWidth(2)
        self.blood_2_sample_label.setAlignment(Qt.AlignCenter)
        self.blood_2_asf_1_checkBox = QCheckBox(self.blood_2_frame)
        self.blood_2_asf_1_checkBox.setObjectName(u"blood_2_asf_1_checkBox")
        self.blood_2_asf_1_checkBox.setGeometry(QRect(10, 50, 301, 20))
        self.blood_2_asf_1_checkBox.setFont(font1)
        self.blood_2_asf_2_checkBox = QCheckBox(self.blood_2_frame)
        self.blood_2_asf_2_checkBox.setObjectName(u"blood_2_asf_2_checkBox")
        self.blood_2_asf_2_checkBox.setGeometry(QRect(10, 100, 301, 20))
        self.blood_2_asf_2_checkBox.setFont(font1)
        self.blood_2_asf_3_checkBox = QCheckBox(self.blood_2_frame)
        self.blood_2_asf_3_checkBox.setObjectName(u"blood_2_asf_3_checkBox")
        self.blood_2_asf_3_checkBox.setGeometry(QRect(10, 150, 271, 20))
        self.blood_2_asf_3_checkBox.setFont(font1)
        self.blood_2_csf_checkBox = QCheckBox(self.blood_2_frame)
        self.blood_2_csf_checkBox.setObjectName(u"blood_2_csf_checkBox")
        self.blood_2_csf_checkBox.setGeometry(QRect(10, 200, 271, 20))
        self.blood_2_csf_checkBox.setFont(font1)
        self.blood_2_hp_checkBox = QCheckBox(self.blood_2_frame)
        self.blood_2_hp_checkBox.setObjectName(u"blood_2_hp_checkBox")
        self.blood_2_hp_checkBox.setGeometry(QRect(10, 250, 271, 20))
        self.blood_2_hp_checkBox.setFont(font1)
        self.blood_2_prrsv_checkBox = QCheckBox(self.blood_2_frame)
        self.blood_2_prrsv_checkBox.setObjectName(u"blood_2_prrsv_checkBox")
        self.blood_2_prrsv_checkBox.setGeometry(QRect(10, 300, 271, 20))
        self.blood_2_prrsv_checkBox.setFont(font1)
        self.blood_2_pcv_checkBox = QCheckBox(self.blood_2_frame)
        self.blood_2_pcv_checkBox.setObjectName(u"blood_2_pcv_checkBox")
        self.blood_2_pcv_checkBox.setGeometry(QRect(10, 350, 271, 20))
        self.blood_2_pcv_checkBox.setFont(font1)
        self.blood_2_ped_checkBox = QCheckBox(self.blood_2_frame)
        self.blood_2_ped_checkBox.setObjectName(u"blood_2_ped_checkBox")
        self.blood_2_ped_checkBox.setGeometry(QRect(10, 400, 271, 20))
        self.blood_2_ped_checkBox.setFont(font1)
        self.blood_2_asf_1_lineEdit = QLineEdit(self.blood_2_frame)
        self.blood_2_asf_1_lineEdit.setObjectName(u"blood_2_asf_1_lineEdit")
        self.blood_2_asf_1_lineEdit.setGeometry(QRect(320, 45, 81, 31))
        self.blood_2_asf_1_lineEdit.setFont(font)
        self.blood_2_asf_1_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_2_asf_2_lineEdit = QLineEdit(self.blood_2_frame)
        self.blood_2_asf_2_lineEdit.setObjectName(u"blood_2_asf_2_lineEdit")
        self.blood_2_asf_2_lineEdit.setGeometry(QRect(320, 90, 81, 31))
        self.blood_2_asf_2_lineEdit.setFont(font)
        self.blood_2_asf_2_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_2_asf_3_lineEdit = QLineEdit(self.blood_2_frame)
        self.blood_2_asf_3_lineEdit.setObjectName(u"blood_2_asf_3_lineEdit")
        self.blood_2_asf_3_lineEdit.setGeometry(QRect(320, 140, 81, 31))
        self.blood_2_asf_3_lineEdit.setFont(font)
        self.blood_2_asf_3_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_2_csf_lineEdit = QLineEdit(self.blood_2_frame)
        self.blood_2_csf_lineEdit.setObjectName(u"blood_2_csf_lineEdit")
        self.blood_2_csf_lineEdit.setGeometry(QRect(320, 190, 81, 31))
        self.blood_2_csf_lineEdit.setFont(font)
        self.blood_2_csf_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_2_hp_lineEdit = QLineEdit(self.blood_2_frame)
        self.blood_2_hp_lineEdit.setObjectName(u"blood_2_hp_lineEdit")
        self.blood_2_hp_lineEdit.setGeometry(QRect(320, 240, 81, 31))
        self.blood_2_hp_lineEdit.setFont(font)
        self.blood_2_hp_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_2_prrsv_lineEdit = QLineEdit(self.blood_2_frame)
        self.blood_2_prrsv_lineEdit.setObjectName(u"blood_2_prrsv_lineEdit")
        self.blood_2_prrsv_lineEdit.setGeometry(QRect(320, 290, 81, 31))
        self.blood_2_prrsv_lineEdit.setFont(font)
        self.blood_2_prrsv_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_2_pcv_lineEdit = QLineEdit(self.blood_2_frame)
        self.blood_2_pcv_lineEdit.setObjectName(u"blood_2_pcv_lineEdit")
        self.blood_2_pcv_lineEdit.setGeometry(QRect(320, 340, 81, 31))
        self.blood_2_pcv_lineEdit.setFont(font)
        self.blood_2_pcv_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_2_ped_lineEdit = QLineEdit(self.blood_2_frame)
        self.blood_2_ped_lineEdit.setObjectName(u"blood_2_ped_lineEdit")
        self.blood_2_ped_lineEdit.setGeometry(QRect(320, 390, 81, 31))
        self.blood_2_ped_lineEdit.setFont(font)
        self.blood_2_ped_lineEdit.setAlignment(Qt.AlignCenter)
        self.blood_2_line = QFrame(self.blood_2_frame)
        self.blood_2_line.setObjectName(u"blood_2_line")
        self.blood_2_line.setGeometry(QRect(305, 45, 16, 381))
        self.blood_2_line.setFrameShape(QFrame.VLine)
        self.blood_2_line.setFrameShadow(QFrame.Sunken)
        self.blood_2_line.raise_()
        self.blood_2_label.raise_()
        self.blood_2_sample_label.raise_()
        self.blood_2_asf_1_checkBox.raise_()
        self.blood_2_asf_2_checkBox.raise_()
        self.blood_2_asf_3_checkBox.raise_()
        self.blood_2_csf_checkBox.raise_()
        self.blood_2_hp_checkBox.raise_()
        self.blood_2_prrsv_checkBox.raise_()
        self.blood_2_pcv_checkBox.raise_()
        self.blood_2_ped_checkBox.raise_()
        self.blood_2_asf_1_lineEdit.raise_()
        self.blood_2_asf_2_lineEdit.raise_()
        self.blood_2_asf_3_lineEdit.raise_()
        self.blood_2_csf_lineEdit.raise_()
        self.blood_2_hp_lineEdit.raise_()
        self.blood_2_prrsv_lineEdit.raise_()
        self.blood_2_pcv_lineEdit.raise_()
        self.blood_2_ped_lineEdit.raise_()
        self.others_frame = QFrame(self.centralwidget)
        self.others_frame.setObjectName(u"others_frame")
        self.others_frame.setGeometry(QRect(1241, 0, 411, 731))
        self.others_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.others_frame.setFrameShape(QFrame.Box)
        self.others_frame.setFrameShadow(QFrame.Plain)
        self.others_frame.setLineWidth(2)
        self.others_label = QLabel(self.others_frame)
        self.others_label.setObjectName(u"others_label")
        self.others_label.setGeometry(QRect(5, 5, 307, 31))
        self.others_label.setFont(font)
        self.others_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.others_label.setFrameShape(QFrame.Box)
        self.others_label.setLineWidth(2)
        self.others_label.setAlignment(Qt.AlignCenter)
        self.others_sample_label = QLabel(self.others_frame)
        self.others_sample_label.setObjectName(u"others_sample_label")
        self.others_sample_label.setGeometry(QRect(315, 5, 91, 31))
        self.others_sample_label.setFont(font)
        self.others_sample_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.others_sample_label.setFrameShape(QFrame.Box)
        self.others_sample_label.setLineWidth(2)
        self.others_sample_label.setAlignment(Qt.AlignCenter)
        self.others_bird_1_checkBox = QCheckBox(self.others_frame)
        self.others_bird_1_checkBox.setObjectName(u"others_bird_1_checkBox")
        self.others_bird_1_checkBox.setGeometry(QRect(10, 50, 301, 20))
        self.others_bird_1_checkBox.setFont(font1)
        self.others_bird_2_checkBox = QCheckBox(self.others_frame)
        self.others_bird_2_checkBox.setObjectName(u"others_bird_2_checkBox")
        self.others_bird_2_checkBox.setGeometry(QRect(10, 100, 301, 20))
        self.others_bird_2_checkBox.setFont(font1)
        self.others_clos_checkBox = QCheckBox(self.others_frame)
        self.others_clos_checkBox.setObjectName(u"others_clos_checkBox")
        self.others_clos_checkBox.setGeometry(QRect(10, 150, 311, 20))
        self.others_clos_checkBox.setFont(font1)
        self.others_lep_checkBox = QCheckBox(self.others_frame)
        self.others_lep_checkBox.setObjectName(u"others_lep_checkBox")
        self.others_lep_checkBox.setGeometry(QRect(10, 200, 271, 20))
        self.others_lep_checkBox.setFont(font1)
        self.others_toxo_checkBox = QCheckBox(self.others_frame)
        self.others_toxo_checkBox.setObjectName(u"others_toxo_checkBox")
        self.others_toxo_checkBox.setGeometry(QRect(10, 250, 271, 20))
        self.others_toxo_checkBox.setFont(font1)
        self.others_melio_checkBox = QCheckBox(self.others_frame)
        self.others_melio_checkBox.setObjectName(u"others_melio_checkBox")
        self.others_melio_checkBox.setGeometry(QRect(10, 300, 271, 20))
        self.others_melio_checkBox.setFont(font1)
        self.others_myco_checkBox = QCheckBox(self.others_frame)
        self.others_myco_checkBox.setObjectName(u"others_myco_checkBox")
        self.others_myco_checkBox.setGeometry(QRect(10, 350, 271, 20))
        self.others_myco_checkBox.setFont(font1)
        self.others_mavium_checkBox = QCheckBox(self.others_frame)
        self.others_mavium_checkBox.setObjectName(u"others_mavium_checkBox")
        self.others_mavium_checkBox.setGeometry(QRect(10, 400, 271, 20))
        self.others_mavium_checkBox.setFont(font1)
        self.others_mbovis_checkBox = QCheckBox(self.others_frame)
        self.others_mbovis_checkBox.setObjectName(u"others_mbovis_checkBox")
        self.others_mbovis_checkBox.setGeometry(QRect(10, 450, 271, 20))
        self.others_mbovis_checkBox.setFont(font1)
        self.others_mtube_checkBox = QCheckBox(self.others_frame)
        self.others_mtube_checkBox.setObjectName(u"others_mtube_checkBox")
        self.others_mtube_checkBox.setGeometry(QRect(10, 500, 271, 20))
        self.others_mtube_checkBox.setFont(font1)
        self.others_ahs_checkBox = QCheckBox(self.others_frame)
        self.others_ahs_checkBox.setObjectName(u"others_ahs_checkBox")
        self.others_ahs_checkBox.setGeometry(QRect(10, 550, 271, 20))
        self.others_ahs_checkBox.setFont(font1)
        self.others_others_1_checkBox = QCheckBox(self.others_frame)
        self.others_others_1_checkBox.setObjectName(u"others_others_1_checkBox")
        self.others_others_1_checkBox.setGeometry(QRect(10, 600, 21, 20))
        self.others_others_1_checkBox.setFont(font1)
        self.others_bird_1_lineEdit = QLineEdit(self.others_frame)
        self.others_bird_1_lineEdit.setObjectName(u"others_bird_1_lineEdit")
        self.others_bird_1_lineEdit.setGeometry(QRect(320, 45, 81, 31))
        self.others_bird_1_lineEdit.setFont(font)
        self.others_bird_1_lineEdit.setAlignment(Qt.AlignCenter)
        self.others_bird_2_lineEdit = QLineEdit(self.others_frame)
        self.others_bird_2_lineEdit.setObjectName(u"others_bird_2_lineEdit")
        self.others_bird_2_lineEdit.setGeometry(QRect(320, 90, 81, 31))
        self.others_bird_2_lineEdit.setFont(font)
        self.others_bird_2_lineEdit.setAlignment(Qt.AlignCenter)
        self.others_clos_lineEdit = QLineEdit(self.others_frame)
        self.others_clos_lineEdit.setObjectName(u"others_clos_lineEdit")
        self.others_clos_lineEdit.setGeometry(QRect(320, 140, 81, 31))
        self.others_clos_lineEdit.setFont(font)
        self.others_clos_lineEdit.setAlignment(Qt.AlignCenter)
        self.others_lep_lineEdit = QLineEdit(self.others_frame)
        self.others_lep_lineEdit.setObjectName(u"others_lep_lineEdit")
        self.others_lep_lineEdit.setGeometry(QRect(320, 190, 81, 31))
        self.others_lep_lineEdit.setFont(font)
        self.others_lep_lineEdit.setAlignment(Qt.AlignCenter)
        self.others_toxo_lineEdit = QLineEdit(self.others_frame)
        self.others_toxo_lineEdit.setObjectName(u"others_toxo_lineEdit")
        self.others_toxo_lineEdit.setGeometry(QRect(320, 240, 81, 31))
        self.others_toxo_lineEdit.setFont(font)
        self.others_toxo_lineEdit.setAlignment(Qt.AlignCenter)
        self.others_melio_lineEdit = QLineEdit(self.others_frame)
        self.others_melio_lineEdit.setObjectName(u"others_melio_lineEdit")
        self.others_melio_lineEdit.setGeometry(QRect(320, 290, 81, 31))
        self.others_melio_lineEdit.setFont(font)
        self.others_melio_lineEdit.setAlignment(Qt.AlignCenter)
        self.others_myco_lineEdit = QLineEdit(self.others_frame)
        self.others_myco_lineEdit.setObjectName(u"others_myco_lineEdit")
        self.others_myco_lineEdit.setGeometry(QRect(320, 340, 81, 31))
        self.others_myco_lineEdit.setFont(font)
        self.others_myco_lineEdit.setAlignment(Qt.AlignCenter)
        self.others_mavium_lineEdit = QLineEdit(self.others_frame)
        self.others_mavium_lineEdit.setObjectName(u"others_mavium_lineEdit")
        self.others_mavium_lineEdit.setGeometry(QRect(320, 390, 81, 31))
        self.others_mavium_lineEdit.setFont(font)
        self.others_mavium_lineEdit.setAlignment(Qt.AlignCenter)
        self.others_mbovis_lineEdit = QLineEdit(self.others_frame)
        self.others_mbovis_lineEdit.setObjectName(u"others_mbovis_lineEdit")
        self.others_mbovis_lineEdit.setGeometry(QRect(320, 440, 81, 31))
        self.others_mbovis_lineEdit.setFont(font)
        self.others_mbovis_lineEdit.setAlignment(Qt.AlignCenter)
        self.others_mtube_lineEdit = QLineEdit(self.others_frame)
        self.others_mtube_lineEdit.setObjectName(u"others_mtube_lineEdit")
        self.others_mtube_lineEdit.setGeometry(QRect(320, 490, 81, 31))
        self.others_mtube_lineEdit.setFont(font)
        self.others_mtube_lineEdit.setAlignment(Qt.AlignCenter)
        self.others_ahs_lineEdit = QLineEdit(self.others_frame)
        self.others_ahs_lineEdit.setObjectName(u"others_ahs_lineEdit")
        self.others_ahs_lineEdit.setGeometry(QRect(320, 540, 81, 31))
        self.others_ahs_lineEdit.setFont(font)
        self.others_ahs_lineEdit.setAlignment(Qt.AlignCenter)
        self.others_others_1_lineEdit_2 = QLineEdit(self.others_frame)
        self.others_others_1_lineEdit_2.setObjectName(u"others_others_1_lineEdit_2")
        self.others_others_1_lineEdit_2.setGeometry(QRect(320, 590, 81, 31))
        self.others_others_1_lineEdit_2.setFont(font)
        self.others_others_1_lineEdit_2.setAlignment(Qt.AlignCenter)
        self.others_line = QFrame(self.others_frame)
        self.others_line.setObjectName(u"others_line")
        self.others_line.setGeometry(QRect(305, 45, 16, 681))
        self.others_line.setFrameShape(QFrame.VLine)
        self.others_line.setFrameShadow(QFrame.Sunken)
        self.others_others_1_lineEdit = QLineEdit(self.others_frame)
        self.others_others_1_lineEdit.setObjectName(u"others_others_1_lineEdit")
        self.others_others_1_lineEdit.setGeometry(QRect(40, 590, 251, 31))
        self.others_others_1_lineEdit.setFont(font)
        self.others_others_1_lineEdit.setAlignment(Qt.AlignCenter)
        self.others_others_1_price_label = QLabel(self.others_frame)
        self.others_others_1_price_label.setObjectName(u"others_others_1_price_label")
        self.others_others_1_price_label.setGeometry(QRect(40, 635, 49, 16))
        self.others_others_1_price_label.setFont(font1)
        self.others_others_1_price_lineEdit = QLineEdit(self.others_frame)
        self.others_others_1_price_lineEdit.setObjectName(u"others_others_1_price_lineEdit")
        self.others_others_1_price_lineEdit.setGeometry(QRect(90, 625, 101, 31))
        self.others_others_1_price_lineEdit.setFont(font)
        self.others_others_1_price_lineEdit.setAlignment(Qt.AlignCenter)
        self.others_others_2_price_label = QLabel(self.others_frame)
        self.others_others_2_price_label.setObjectName(u"others_others_2_price_label")
        self.others_others_2_price_label.setGeometry(QRect(40, 705, 49, 16))
        self.others_others_2_price_label.setFont(font1)
        self.others_others_2_lineEdit = QLineEdit(self.others_frame)
        self.others_others_2_lineEdit.setObjectName(u"others_others_2_lineEdit")
        self.others_others_2_lineEdit.setGeometry(QRect(40, 660, 251, 31))
        self.others_others_2_lineEdit.setFont(font)
        self.others_others_2_lineEdit.setAlignment(Qt.AlignCenter)
        self.others_others_2_price_lineEdit = QLineEdit(self.others_frame)
        self.others_others_2_price_lineEdit.setObjectName(u"others_others_2_price_lineEdit")
        self.others_others_2_price_lineEdit.setGeometry(QRect(90, 695, 101, 31))
        self.others_others_2_price_lineEdit.setFont(font)
        self.others_others_2_price_lineEdit.setAlignment(Qt.AlignCenter)
        self.others_others_2_lineEdit_2 = QLineEdit(self.others_frame)
        self.others_others_2_lineEdit_2.setObjectName(u"others_others_2_lineEdit_2")
        self.others_others_2_lineEdit_2.setGeometry(QRect(320, 660, 81, 31))
        self.others_others_2_lineEdit_2.setFont(font)
        self.others_others_2_lineEdit_2.setAlignment(Qt.AlignCenter)
        self.others_others_2_checkBox = QCheckBox(self.others_frame)
        self.others_others_2_checkBox.setObjectName(u"others_others_2_checkBox")
        self.others_others_2_checkBox.setGeometry(QRect(10, 670, 21, 20))
        self.others_others_2_checkBox.setFont(font1)
        self.others_line.raise_()
        self.others_label.raise_()
        self.others_sample_label.raise_()
        self.others_bird_1_checkBox.raise_()
        self.others_bird_2_checkBox.raise_()
        self.others_clos_checkBox.raise_()
        self.others_lep_checkBox.raise_()
        self.others_toxo_checkBox.raise_()
        self.others_melio_checkBox.raise_()
        self.others_myco_checkBox.raise_()
        self.others_mavium_checkBox.raise_()
        self.others_mbovis_checkBox.raise_()
        self.others_mtube_checkBox.raise_()
        self.others_ahs_checkBox.raise_()
        self.others_others_1_checkBox.raise_()
        self.others_bird_1_lineEdit.raise_()
        self.others_bird_2_lineEdit.raise_()
        self.others_clos_lineEdit.raise_()
        self.others_lep_lineEdit.raise_()
        self.others_toxo_lineEdit.raise_()
        self.others_melio_lineEdit.raise_()
        self.others_myco_lineEdit.raise_()
        self.others_mavium_lineEdit.raise_()
        self.others_mbovis_lineEdit.raise_()
        self.others_mtube_lineEdit.raise_()
        self.others_ahs_lineEdit.raise_()
        self.others_others_1_lineEdit_2.raise_()
        self.others_others_1_lineEdit.raise_()
        self.others_others_1_price_label.raise_()
        self.others_others_1_price_lineEdit.raise_()
        self.others_others_2_price_label.raise_()
        self.others_others_2_lineEdit.raise_()
        self.others_others_2_price_lineEdit.raise_()
        self.others_others_2_lineEdit_2.raise_()
        self.others_others_2_checkBox.raise_()
        self.canine_frame = QFrame(self.centralwidget)
        self.canine_frame.setObjectName(u"canine_frame")
        self.canine_frame.setGeometry(QRect(1241, 735, 411, 141))
        self.canine_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.canine_frame.setFrameShape(QFrame.Box)
        self.canine_frame.setFrameShadow(QFrame.Plain)
        self.canine_frame.setLineWidth(2)
        self.canine_label = QLabel(self.canine_frame)
        self.canine_label.setObjectName(u"canine_label")
        self.canine_label.setGeometry(QRect(5, 5, 307, 31))
        self.canine_label.setFont(font)
        self.canine_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.canine_label.setFrameShape(QFrame.Box)
        self.canine_label.setLineWidth(2)
        self.canine_label.setAlignment(Qt.AlignCenter)
        self.canine_sample_label = QLabel(self.canine_frame)
        self.canine_sample_label.setObjectName(u"canine_sample_label")
        self.canine_sample_label.setGeometry(QRect(315, 5, 91, 31))
        self.canine_sample_label.setFont(font)
        self.canine_sample_label.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.canine_sample_label.setFrameShape(QFrame.Box)
        self.canine_sample_label.setLineWidth(2)
        self.canine_sample_label.setAlignment(Qt.AlignCenter)
        self.canine_cdv_checkBox = QCheckBox(self.canine_frame)
        self.canine_cdv_checkBox.setObjectName(u"canine_cdv_checkBox")
        self.canine_cdv_checkBox.setGeometry(QRect(10, 50, 301, 20))
        self.canine_cdv_checkBox.setFont(font1)
        self.canine_cpv_checkBox = QCheckBox(self.canine_frame)
        self.canine_cpv_checkBox.setObjectName(u"canine_cpv_checkBox")
        self.canine_cpv_checkBox.setGeometry(QRect(10, 100, 301, 20))
        self.canine_cpv_checkBox.setFont(font1)
        self.canine_cdv_lineEdit = QLineEdit(self.canine_frame)
        self.canine_cdv_lineEdit.setObjectName(u"canine_cdv_lineEdit")
        self.canine_cdv_lineEdit.setGeometry(QRect(320, 45, 81, 31))
        self.canine_cdv_lineEdit.setFont(font)
        self.canine_cdv_lineEdit.setAlignment(Qt.AlignCenter)
        self.canine_cpv_lineEdit = QLineEdit(self.canine_frame)
        self.canine_cpv_lineEdit.setObjectName(u"canine_cpv_lineEdit")
        self.canine_cpv_lineEdit.setGeometry(QRect(320, 90, 81, 31))
        self.canine_cpv_lineEdit.setFont(font)
        self.canine_cpv_lineEdit.setAlignment(Qt.AlignCenter)
        self.canine_line = QFrame(self.canine_frame)
        self.canine_line.setObjectName(u"canine_line")
        self.canine_line.setGeometry(QRect(305, 45, 16, 91))
        self.canine_line.setFrameShape(QFrame.VLine)
        self.canine_line.setFrameShadow(QFrame.Sunken)
        self.summary_frame = QFrame(self.centralwidget)
        self.summary_frame.setObjectName(u"summary_frame")
        self.summary_frame.setGeometry(QRect(1655, 185, 240, 691))
        self.summary_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.summary_frame.setFrameShape(QFrame.Box)
        self.summary_frame.setFrameShadow(QFrame.Plain)
        self.summary_frame.setLineWidth(2)
        self.summary_pushButton = QPushButton(self.summary_frame)
        self.summary_pushButton.setObjectName(u"summary_pushButton")
        self.summary_pushButton.setGeometry(QRect(40, 30, 161, 61))
        font2 = QFont()
        font2.setFamilies([u"TH Niramit AS"])
        font2.setPointSize(22)
        font2.setBold(True)
        self.summary_pushButton.setFont(font2)
        self.summary_pushButton.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.summary_pushButton.setStyleSheet(u"\n"
"    background-color: rgb(162, 233, 255);\n"
"\n"
"\n"
"")
        self.summary_pushButton.setAutoDefault(False)
        self.number_item_label = QLabel(self.summary_frame)
        self.number_item_label.setObjectName(u"number_item_label")
        self.number_item_label.setGeometry(QRect(10, 170, 61, 16))
        self.number_item_label.setFont(font1)
        self.number_item_lineEdit = QLineEdit(self.summary_frame)
        self.number_item_lineEdit.setObjectName(u"number_item_lineEdit")
        self.number_item_lineEdit.setGeometry(QRect(85, 155, 81, 41))
        self.number_item_lineEdit.setFont(font)
        self.number_item_lineEdit.setAlignment(Qt.AlignCenter)
        self.number_item_label2 = QLabel(self.summary_frame)
        self.number_item_label2.setObjectName(u"number_item_label2")
        self.number_item_label2.setGeometry(QRect(170, 170, 61, 16))
        self.number_item_label2.setFont(font1)
        self.bath_label = QLabel(self.summary_frame)
        self.bath_label.setObjectName(u"bath_label")
        self.bath_label.setGeometry(QRect(196, 245, 41, 16))
        self.bath_label.setFont(font1)
        self.cost_item_label = QLabel(self.summary_frame)
        self.cost_item_label.setObjectName(u"cost_item_label")
        self.cost_item_label.setGeometry(QRect(10, 245, 71, 16))
        self.cost_item_label.setFont(font1)
        self.cost_item_lineEdit = QLineEdit(self.summary_frame)
        self.cost_item_lineEdit.setObjectName(u"cost_item_lineEdit")
        self.cost_item_lineEdit.setGeometry(QRect(85, 230, 101, 41))
        self.cost_item_lineEdit.setFont(font)
        self.cost_item_lineEdit.setAlignment(Qt.AlignCenter)
        self.save_data_pushButton = QPushButton(self.summary_frame)
        self.save_data_pushButton.setObjectName(u"save_data_pushButton")
        self.save_data_pushButton.setGeometry(QRect(40, 530, 161, 61))
        self.save_data_pushButton.setFont(font2)
        self.save_data_pushButton.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.save_data_pushButton.setStyleSheet(u"\n"
"    background-color:rgb(82, 255, 51)\n"
"\n"
"\n"
"")
        self.save_data_pushButton.setAutoDefault(False)
        self.back_to_home_pushButton = QPushButton(self.summary_frame)
        self.back_to_home_pushButton.setObjectName(u"back_to_home_pushButton")
        self.back_to_home_pushButton.setGeometry(QRect(40, 600, 161, 61))
        self.back_to_home_pushButton.setFont(font2)
        self.back_to_home_pushButton.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.back_to_home_pushButton.setStyleSheet(u"\n"
"    background-color: rgb(255, 135, 99)\n"
"\n"
"\n"
"")
        self.back_to_home_pushButton.setAutoDefault(False)
        self.laboratory_frame = QFrame(self.centralwidget)
        self.laboratory_frame.setObjectName(u"laboratory_frame")
        self.laboratory_frame.setGeometry(QRect(1655, 0, 241, 181))
        self.laboratory_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.laboratory_frame.setFrameShape(QFrame.Box)
        self.laboratory_frame.setFrameShadow(QFrame.Plain)
        self.laboratory_frame.setLineWidth(2)
        self.laboratory_label = QLabel(self.laboratory_frame)
        self.laboratory_label.setObjectName(u"laboratory_label")
        self.laboratory_label.setGeometry(QRect(5, 5, 231, 31))
        self.laboratory_label.setFont(font)
        self.laboratory_label.setStyleSheet(u"background:rgb(255, 85, 0)")
        self.laboratory_label.setFrameShape(QFrame.Box)
        self.laboratory_label.setLineWidth(2)
        self.laboratory_label.setAlignment(Qt.AlignCenter)
        self.laboratory_cpcr_checkBox = QCheckBox(self.laboratory_frame)
        self.laboratory_cpcr_checkBox.setObjectName(u"laboratory_cpcr_checkBox")
        self.laboratory_cpcr_checkBox.setGeometry(QRect(30, 50, 111, 20))
        self.laboratory_cpcr_checkBox.setFont(font1)
        self.laboratory_pcr_checkBox = QCheckBox(self.laboratory_frame)
        self.laboratory_pcr_checkBox.setObjectName(u"laboratory_pcr_checkBox")
        self.laboratory_pcr_checkBox.setGeometry(QRect(30, 100, 141, 20))
        self.laboratory_pcr_checkBox.setFont(font1)
        self.laboratory_extraction_checkBox = QCheckBox(self.laboratory_frame)
        self.laboratory_extraction_checkBox.setObjectName(u"laboratory_extraction_checkBox")
        self.laboratory_extraction_checkBox.setGeometry(QRect(30, 150, 111, 20))
        self.laboratory_extraction_checkBox.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.summary_pushButton.setDefault(False)
        self.save_data_pushButton.setDefault(False)
        self.back_to_home_pushButton.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Molecular_from", None))
        self.avian_label.setText(QCoreApplication.translate("MainWindow", u"AVIAN", None))
        self.avian_sample_label.setText(QCoreApplication.translate("MainWindow", u"SAMPLE", None))
        self.avian_AI_1_checkBox.setText(QCoreApplication.translate("MainWindow", u"AI; type A, H5/H7/H9 - cPCR (700)", None))
        self.avian_AI_2_checkBox.setText(QCoreApplication.translate("MainWindow", u"AI; type A, H5/H7/H9 - qPCR (1200)", None))
        self.avian_ibv_checkBox.setText(QCoreApplication.translate("MainWindow", u"IBV (700)", None))
        self.avian_ibdv_checkBox.setText(QCoreApplication.translate("MainWindow", u"IBDV (700)", None))
        self.avian_ilt_checkBox.setText(QCoreApplication.translate("MainWindow", u"ILT (600)", None))
        self.avian_ndv_checkBox.setText(QCoreApplication.translate("MainWindow", u"NDV - cPCR (700)", None))
        self.avian_ndv_2_checkBox.setText(QCoreApplication.translate("MainWindow", u"NDV - qPCR (1200)", None))
        self.avian_pdd_checkBox.setText(QCoreApplication.translate("MainWindow", u"PDD (700)", None))
        self.avian_pbfdv_checkBox.setText(QCoreApplication.translate("MainWindow", u"PBFDV (600)", None))
        self.avian_chlamydia_checkBox.setText(QCoreApplication.translate("MainWindow", u"Chlamydia psittaci (600)", None))
        self.avian_pasteurella_checkBox.setText(QCoreApplication.translate("MainWindow", u"Pasteurella multocida (600)", None))
        self.avian_mg_checkBox.setText(QCoreApplication.translate("MainWindow", u"MG (600)", None))
        self.avian_AI_1_lineEdit.setInputMask("")
        self.avian_AI_1_lineEdit.setText("")
        self.avian_AI_2_lineEdit.setText("")
        self.avian_ibv_lineEdit.setText("")
        self.avian_ibdv_lineEdit.setText("")
        self.avian_ilt_lineEdit.setText("")
        self.avian_ndv_lineEdit.setText("")
        self.avian_ndv_2_lineEdit.setText("")
        self.avian_pdd_lineEdit.setText("")
        self.avian_pbfdv_lineEdit.setText("")
        self.avian_chlamydia_lineEdit.setText("")
        self.avian_pasteurella_lineEdit.setText("")
        self.avian_mg_lineEdit.setText("")
        self.feline_label.setText(QCoreApplication.translate("MainWindow", u"Feline", None))
        self.feline_sample_label.setText(QCoreApplication.translate("MainWindow", u"SAMPLE", None))
        self.feline_felv_checkBox.setText(QCoreApplication.translate("MainWindow", u"FeLV (600)", None))
        self.feline_fip_checkBox.setText(QCoreApplication.translate("MainWindow", u"FIP (800)", None))
        self.feline_fiv_checkBox.setText(QCoreApplication.translate("MainWindow", u"FIV (600)", None))
        self.feline_panleukopenia_checkBox.setText(QCoreApplication.translate("MainWindow", u"Panleukopenia (600)", None))
        self.feline_felv_lineEdit.setText("")
        self.feline_fip_lineEdit.setText("")
        self.feline_fiv_lineEdit.setText("")
        self.feline_panleukopenia_lineEdit.setText("")
        self.elephant_label.setText(QCoreApplication.translate("MainWindow", u"Elephant", None))
        self.elephant_sample_label.setText(QCoreApplication.translate("MainWindow", u"SAMPLE", None))
        self.elephant_eehv1a_4_checkBox.setText(QCoreApplication.translate("MainWindow", u"EEHV1A/4 (600)", None))
        self.elephant_eehv1a_1_checkBox.setText(QCoreApplication.translate("MainWindow", u"EEHV1A - cPCR (700)", None))
        self.elephant_eehv1a_2_checkBox.setText(QCoreApplication.translate("MainWindow", u"EEHV1A - qPCR (1200)", None))
        self.elephant_eehv4_1_checkBox.setText(QCoreApplication.translate("MainWindow", u"EEHV4 - cPCR (700)", None))
        self.elephant_eehv4_2_checkBox.setText(QCoreApplication.translate("MainWindow", u"EEHV4 - qPCR (1200)", None))
        self.elephant_eehv1a_4_lineEdit.setInputMask("")
        self.elephant_eehv1a_4_lineEdit.setText("")
        self.elephant_eehv1a_1_lineEdit.setText("")
        self.elephant_eehv1a_2_lineEdit.setText("")
        self.elephant_eehv4_1_lineEdit.setText("")
        self.elephant_eehv4_2_lineEdit.setText("")
        self.bovine_label.setText(QCoreApplication.translate("MainWindow", u"Bovine", None))
        self.bovine_sample_label.setText(QCoreApplication.translate("MainWindow", u"SAMPLE", None))
        self.bovin_blv_checkBox.setText(QCoreApplication.translate("MainWindow", u"BLV (700)", None))
        self.bovin_fmdv_checkBox.setText(QCoreApplication.translate("MainWindow", u"FMDV (700)", None))
        self.bovin_lsdv_checkBox.setText(QCoreApplication.translate("MainWindow", u"LSDV (600)", None))
        self.bovin_bvd_checkBox.setText(QCoreApplication.translate("MainWindow", u"BVD (700)", None))
        self.bovin_blv_lineEdit.setText("")
        self.bovin_fmdv_lineEdit.setText("")
        self.bovin_lsdv_lineEdit.setText("")
        self.bovin_bvd_lineEdit.setText("")
        self.equine_label.setText(QCoreApplication.translate("MainWindow", u"Equine", None))
        self.equine_saple_label.setText(QCoreApplication.translate("MainWindow", u"SAMPLE", None))
        self.equine_ehv_checkBox.setText(QCoreApplication.translate("MainWindow", u"EHV (1,4) (700)", None))
        self.equine_ahs_checkBox.setText(QCoreApplication.translate("MainWindow", u"AHS (700)", None))
        self.equine_ehv_lineEdit.setText("")
        self.equine_ahs_lineEdit.setText("")
        self.aquatic_animal_label.setText(QCoreApplication.translate("MainWindow", u"Aquatic animal", None))
        self.aquatic_animal_sample_label.setText(QCoreApplication.translate("MainWindow", u"SAMPLE", None))
        self.aquatic_animal_khv_checkBox.setText(QCoreApplication.translate("MainWindow", u"KHV (600)", None))
        self.aquatic_animal_tilv_checkBox.setText(QCoreApplication.translate("MainWindow", u"TiLV (700)", None))
        self.aquatic_animal_cev_checkBox.setText(QCoreApplication.translate("MainWindow", u"CEV (600)", None))
        self.aquatic_animal_khv_lineEdit.setText("")
        self.aquatic_animal_tilv_lineEdit.setText("")
        self.aquatic_animal_cev_lineEdit.setText("")
        self.blood_1_label.setText(QCoreApplication.translate("MainWindow", u"Blood parasite", None))
        self.blood_1_sample_label.setText(QCoreApplication.translate("MainWindow", u"SAMPLE", None))
        self.blood_1_ana_checkBox.setText(QCoreApplication.translate("MainWindow", u"Anaplasma spp.(500)", None))
        self.blood_1_babe_checkBox.setText(QCoreApplication.translate("MainWindow", u"Babesia spp. (500)", None))
        self.blood_1_ehr_checkBox.setText(QCoreApplication.translate("MainWindow", u"Ehrlichia canis (500)", None))
        self.blood_1_the_checkBox.setText(QCoreApplication.translate("MainWindow", u"Theileria spp.(500)", None))
        self.blood_1_haem_checkBox.setText(QCoreApplication.translate("MainWindow", u"Haemobartonella spp.(600)", None))
        self.blood_1_ecanis_checkBox.setText(QCoreApplication.translate("MainWindow", u"E.canis & Babesia (600)", None))
        self.blood_1_leis_checkBox.setText(QCoreApplication.translate("MainWindow", u"Leishmania spp. (700)", None))
        self.blood_1_try_checkBox.setText(QCoreApplication.translate("MainWindow", u"Trypanosoma evansi(500)", None))
        self.blood_1_ana_lineEdit.setInputMask("")
        self.blood_1_ana_lineEdit.setText("")
        self.blood_1_babe_lineEdit.setText("")
        self.blood_1_ehr_lineEdit.setText("")
        self.blood_1_the_lineEdit.setText("")
        self.blood_1_haem_lineEdit.setText("")
        self.blood_1_ecanis_lineEdit.setText("")
        self.blood_1_leis_lineEdit.setText("")
        self.blood_1_try_lineEdit.setText("")
        self.blood_2_label.setText(QCoreApplication.translate("MainWindow", u"Blood parasite", None))
        self.blood_2_sample_label.setText(QCoreApplication.translate("MainWindow", u"SAMPLE", None))
        self.blood_2_asf_1_checkBox.setText(QCoreApplication.translate("MainWindow", u"ASF-cPCR (400)", None))
        self.blood_2_asf_2_checkBox.setText(QCoreApplication.translate("MainWindow", u"ASF-qPCR (800)", None))
        self.blood_2_asf_3_checkBox.setText(QCoreApplication.translate("MainWindow", u"ASF-qPCR (1000)", None))
        self.blood_2_csf_checkBox.setText(QCoreApplication.translate("MainWindow", u"CSF (700)", None))
        self.blood_2_hp_checkBox.setText(QCoreApplication.translate("MainWindow", u"HP-PRRSV (700)", None))
        self.blood_2_prrsv_checkBox.setText(QCoreApplication.translate("MainWindow", u"PRRSV (800)", None))
        self.blood_2_pcv_checkBox.setText(QCoreApplication.translate("MainWindow", u"PCV-2 (600)", None))
        self.blood_2_ped_checkBox.setText(QCoreApplication.translate("MainWindow", u"PED (700)", None))
        self.blood_2_asf_1_lineEdit.setInputMask("")
        self.blood_2_asf_1_lineEdit.setText("")
        self.blood_2_asf_2_lineEdit.setText("")
        self.blood_2_asf_3_lineEdit.setText("")
        self.blood_2_csf_lineEdit.setText("")
        self.blood_2_hp_lineEdit.setText("")
        self.blood_2_prrsv_lineEdit.setText("")
        self.blood_2_pcv_lineEdit.setText("")
        self.blood_2_ped_lineEdit.setText("")
        self.others_label.setText(QCoreApplication.translate("MainWindow", u"Others", None))
        self.others_sample_label.setText(QCoreApplication.translate("MainWindow", u"SAMPLE", None))
        self.others_bird_1_checkBox.setText(QCoreApplication.translate("MainWindow", u"Bird sexing (300)", None))
        self.others_bird_2_checkBox.setText(QCoreApplication.translate("MainWindow", u"Bird sexing (350)", None))
        self.others_clos_checkBox.setText(QCoreApplication.translate("MainWindow", u"Clostridial perfringens toxins (700)", None))
        self.others_lep_checkBox.setText(QCoreApplication.translate("MainWindow", u"Leptospirosis (600)", None))
        self.others_toxo_checkBox.setText(QCoreApplication.translate("MainWindow", u"Toxoplasma gondii (600)", None))
        self.others_melio_checkBox.setText(QCoreApplication.translate("MainWindow", u"Melioidosis (700)", None))
        self.others_myco_checkBox.setText(QCoreApplication.translate("MainWindow", u"Mycobacterium spp.(600)", None))
        self.others_mavium_checkBox.setText(QCoreApplication.translate("MainWindow", u"M.avium (600)", None))
        self.others_mbovis_checkBox.setText(QCoreApplication.translate("MainWindow", u"M.bovis (600)", None))
        self.others_mtube_checkBox.setText(QCoreApplication.translate("MainWindow", u"M.tuberculosis(600)", None))
        self.others_ahs_checkBox.setText(QCoreApplication.translate("MainWindow", u"AHS qPCR(1200)", None))
        self.others_others_1_checkBox.setText("")
        self.others_bird_1_lineEdit.setInputMask("")
        self.others_bird_1_lineEdit.setText("")
        self.others_bird_2_lineEdit.setText("")
        self.others_clos_lineEdit.setText("")
        self.others_lep_lineEdit.setText("")
        self.others_toxo_lineEdit.setText("")
        self.others_melio_lineEdit.setText("")
        self.others_myco_lineEdit.setText("")
        self.others_mavium_lineEdit.setText("")
        self.others_mbovis_lineEdit.setText("")
        self.others_mtube_lineEdit.setText("")
        self.others_ahs_lineEdit.setText("")
        self.others_others_1_lineEdit_2.setText("")
        self.others_others_1_lineEdit.setText("")
        self.others_others_1_price_label.setText(QCoreApplication.translate("MainWindow", u"\u0e23\u0e32\u0e04\u0e32", None))
        self.others_others_1_price_lineEdit.setText("")
        self.others_others_2_price_label.setText(QCoreApplication.translate("MainWindow", u"\u0e23\u0e32\u0e04\u0e32", None))
        self.others_others_2_lineEdit.setText("")
        self.others_others_2_price_lineEdit.setText("")
        self.others_others_2_lineEdit_2.setText("")
        self.others_others_2_checkBox.setText("")
        self.canine_label.setText(QCoreApplication.translate("MainWindow", u"CANINE", None))
        self.canine_sample_label.setText(QCoreApplication.translate("MainWindow", u"SAMPLE", None))
        self.canine_cdv_checkBox.setText(QCoreApplication.translate("MainWindow", u"CDV (700)", None))
        self.canine_cpv_checkBox.setText(QCoreApplication.translate("MainWindow", u"CPV (600)", None))
        self.canine_cdv_lineEdit.setText("")
        self.canine_cpv_lineEdit.setText("")
        self.summary_pushButton.setText(QCoreApplication.translate("MainWindow", u"\u0e2a\u0e23\u0e38\u0e1b\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23", None))
        self.number_item_label.setText(QCoreApplication.translate("MainWindow", u"\u0e08\u0e33\u0e19\u0e27\u0e19", None))
        self.number_item_lineEdit.setText("")
        self.number_item_label2.setText(QCoreApplication.translate("MainWindow", u"\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23", None))
        self.bath_label.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e32\u0e17", None))
        self.cost_item_label.setText(QCoreApplication.translate("MainWindow", u"\u0e04\u0e48\u0e32\u0e43\u0e0a\u0e49\u0e08\u0e48\u0e32\u0e22", None))
        self.cost_item_lineEdit.setText("")
        self.save_data_pushButton.setText(QCoreApplication.translate("MainWindow", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25", None))
        self.back_to_home_pushButton.setText(QCoreApplication.translate("MainWindow", u"\u0e01\u0e25\u0e31\u0e1a\u0e2b\u0e19\u0e49\u0e32\u0e2b\u0e25\u0e31\u0e01", None))
        self.laboratory_label.setText(QCoreApplication.translate("MainWindow", u"Laboratory Request", None))
        self.laboratory_cpcr_checkBox.setText(QCoreApplication.translate("MainWindow", u"cPCR", None))
        self.laboratory_pcr_checkBox.setText(QCoreApplication.translate("MainWindow", u"qPCR", None))
        self.laboratory_extraction_checkBox.setText(QCoreApplication.translate("MainWindow", u"Extraction", None))
    # retranslateUi

if __name__ == "__main__":
    app = QApplication([])
    specimen_UI = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(specimen_UI)
    specimen_UI.show()
    app.exec()