# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'F2_bacterie_biology.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStatusBar, QTextEdit, QWidget)

class Ui_BACTERIE(object):
    def setupUi(self, BACTERIE):
        if not BACTERIE.objectName():
            BACTERIE.setObjectName(u"BACTERIE")
        BACTERIE.resize(1450, 950)
        BACTERIE.setMinimumSize(QSize(1450, 950))
        BACTERIE.setMaximumSize(QSize(1450, 950))
        BACTERIE.setStyleSheet(u"background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 140, 213, 255), stop:1 rgba(255, 229, 75, 255))")
        self.centralwidget = QWidget(BACTERIE)
        self.centralwidget.setObjectName(u"centralwidget")
        self.sample_preparation_frame = QFrame(self.centralwidget)
        self.sample_preparation_frame.setObjectName(u"sample_preparation_frame")
        self.sample_preparation_frame.setGeometry(QRect(0, 0, 241, 681))
        font = QFont()
        font.setFamilies([u"Times New Roman"])
        font.setPointSize(10)
        self.sample_preparation_frame.setFont(font)
        self.sample_preparation_frame.setStyleSheet(u"background:rgb(255, 236, 226)")
        self.sample_preparation_frame.setFrameShape(QFrame.Box)
        self.sample_preparation_frame.setFrameShadow(QFrame.Raised)
        self.sample_preparation_frame.setLineWidth(2)
        self.sample_preparation_label = QLabel(self.sample_preparation_frame)
        self.sample_preparation_label.setObjectName(u"sample_preparation_label")
        self.sample_preparation_label.setGeometry(QRect(0, 0, 161, 41))
        self.sample_preparation_label.setFont(font)
        self.sample_preparation_label.setFrameShape(QFrame.Box)
        self.sample_preparation_label.setFrameShadow(QFrame.Raised)
        self.sample_preparation_label.setLineWidth(3)
        self.sample_preparation_label.setAlignment(Qt.AlignCenter)
        self.sample_label = QLabel(self.sample_preparation_frame)
        self.sample_label.setObjectName(u"sample_label")
        self.sample_label.setGeometry(QRect(160, 0, 81, 41))
        self.sample_label.setFont(font)
        self.sample_label.setFrameShape(QFrame.Box)
        self.sample_label.setFrameShadow(QFrame.Raised)
        self.sample_label.setLineWidth(3)
        self.sample_label.setAlignment(Qt.AlignCenter)
        self.swab_LT_checkBox = QCheckBox(self.sample_preparation_frame)
        self.swab_LT_checkBox.setObjectName(u"swab_LT_checkBox")
        self.swab_LT_checkBox.setGeometry(QRect(10, 50, 151, 21))
        self.swab_LT_checkBox.setFont(font)
        self.swab_RT_checkBox = QCheckBox(self.sample_preparation_frame)
        self.swab_RT_checkBox.setObjectName(u"swab_RT_checkBox")
        self.swab_RT_checkBox.setGeometry(QRect(10, 80, 151, 21))
        self.swab_RT_checkBox.setFont(font)
        self.swab_LT_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.swab_LT_lineEdit.setObjectName(u"swab_LT_lineEdit")
        self.swab_LT_lineEdit.setGeometry(QRect(170, 50, 61, 21))
        self.swab_LT_lineEdit.setFont(font)
        self.swab_LT_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.swab_LT_lineEdit.setAlignment(Qt.AlignCenter)
        self.swab_RT_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.swab_RT_lineEdit.setObjectName(u"swab_RT_lineEdit")
        self.swab_RT_lineEdit.setGeometry(QRect(170, 80, 61, 21))
        self.swab_RT_lineEdit.setFont(font)
        self.swab_RT_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.swab_RT_lineEdit.setAlignment(Qt.AlignCenter)
        self.wound_checkBox = QCheckBox(self.sample_preparation_frame)
        self.wound_checkBox.setObjectName(u"wound_checkBox")
        self.wound_checkBox.setGeometry(QRect(10, 110, 151, 21))
        self.wound_checkBox.setFont(font)
        self.wound_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.wound_lineEdit.setObjectName(u"wound_lineEdit")
        self.wound_lineEdit.setGeometry(QRect(170, 110, 61, 21))
        self.wound_lineEdit.setFont(font)
        self.wound_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.wound_lineEdit.setAlignment(Qt.AlignCenter)
        self.Aspirate_LT_checkBox = QCheckBox(self.sample_preparation_frame)
        self.Aspirate_LT_checkBox.setObjectName(u"Aspirate_LT_checkBox")
        self.Aspirate_LT_checkBox.setGeometry(QRect(10, 140, 121, 21))
        self.Aspirate_LT_checkBox.setFont(font)
        self.Aspirate_LT_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.Aspirate_LT_lineEdit.setObjectName(u"Aspirate_LT_lineEdit")
        self.Aspirate_LT_lineEdit.setGeometry(QRect(170, 140, 61, 21))
        self.Aspirate_LT_lineEdit.setFont(font)
        self.Aspirate_LT_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Aspirate_LT_lineEdit.setAlignment(Qt.AlignCenter)
        self.Aspirate_RT_checkBox = QCheckBox(self.sample_preparation_frame)
        self.Aspirate_RT_checkBox.setObjectName(u"Aspirate_RT_checkBox")
        self.Aspirate_RT_checkBox.setGeometry(QRect(10, 170, 111, 21))
        self.Aspirate_RT_checkBox.setFont(font)
        self.Aspirate_RT_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.Aspirate_RT_lineEdit.setObjectName(u"Aspirate_RT_lineEdit")
        self.Aspirate_RT_lineEdit.setGeometry(QRect(170, 170, 61, 21))
        self.Aspirate_RT_lineEdit.setFont(font)
        self.Aspirate_RT_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Aspirate_RT_lineEdit.setAlignment(Qt.AlignCenter)
        self.urine_checkBox = QCheckBox(self.sample_preparation_frame)
        self.urine_checkBox.setObjectName(u"urine_checkBox")
        self.urine_checkBox.setGeometry(QRect(10, 200, 71, 21))
        self.urine_checkBox.setFont(font)
        self.urine_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.urine_lineEdit.setObjectName(u"urine_lineEdit")
        self.urine_lineEdit.setGeometry(QRect(170, 200, 61, 21))
        self.urine_lineEdit.setFont(font)
        self.urine_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.urine_lineEdit.setAlignment(Qt.AlignCenter)
        self.Midstream_checkBox = QCheckBox(self.sample_preparation_frame)
        self.Midstream_checkBox.setObjectName(u"Midstream_checkBox")
        self.Midstream_checkBox.setGeometry(QRect(10, 230, 91, 21))
        self.Midstream_checkBox.setFont(font)
        self.Midstream_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.Midstream_lineEdit.setObjectName(u"Midstream_lineEdit")
        self.Midstream_lineEdit.setGeometry(QRect(170, 230, 61, 21))
        self.Midstream_lineEdit.setFont(font)
        self.Midstream_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Midstream_lineEdit.setAlignment(Qt.AlignCenter)
        self.Catheterization_checkBox = QCheckBox(self.sample_preparation_frame)
        self.Catheterization_checkBox.setObjectName(u"Catheterization_checkBox")
        self.Catheterization_checkBox.setGeometry(QRect(10, 260, 111, 21))
        self.Catheterization_checkBox.setFont(font)
        self.Catheterization_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.Catheterization_lineEdit.setObjectName(u"Catheterization_lineEdit")
        self.Catheterization_lineEdit.setGeometry(QRect(170, 260, 61, 21))
        self.Catheterization_lineEdit.setFont(font)
        self.Catheterization_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Catheterization_lineEdit.setAlignment(Qt.AlignCenter)
        self.Cystocentesis_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.Cystocentesis_lineEdit.setObjectName(u"Cystocentesis_lineEdit")
        self.Cystocentesis_lineEdit.setGeometry(QRect(170, 290, 61, 21))
        self.Cystocentesis_lineEdit.setFont(font)
        self.Cystocentesis_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Cystocentesis_lineEdit.setAlignment(Qt.AlignCenter)
        self.Cystocentesis_checkBox = QCheckBox(self.sample_preparation_frame)
        self.Cystocentesis_checkBox.setObjectName(u"Cystocentesis_checkBox")
        self.Cystocentesis_checkBox.setGeometry(QRect(10, 290, 131, 21))
        self.Cystocentesis_checkBox.setFont(font)
        self.Tissues_LT_checkBox = QCheckBox(self.sample_preparation_frame)
        self.Tissues_LT_checkBox.setObjectName(u"Tissues_LT_checkBox")
        self.Tissues_LT_checkBox.setGeometry(QRect(10, 320, 91, 21))
        self.Tissues_LT_checkBox.setFont(font)
        self.Tissues_LT_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.Tissues_LT_lineEdit.setObjectName(u"Tissues_LT_lineEdit")
        self.Tissues_LT_lineEdit.setGeometry(QRect(170, 320, 61, 21))
        self.Tissues_LT_lineEdit.setFont(font)
        self.Tissues_LT_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Tissues_LT_lineEdit.setAlignment(Qt.AlignCenter)
        self.Tissues_RT_checkBox = QCheckBox(self.sample_preparation_frame)
        self.Tissues_RT_checkBox.setObjectName(u"Tissues_RT_checkBox")
        self.Tissues_RT_checkBox.setGeometry(QRect(10, 350, 101, 21))
        self.Tissues_RT_checkBox.setFont(font)
        self.Tissues_RT_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.Tissues_RT_lineEdit.setObjectName(u"Tissues_RT_lineEdit")
        self.Tissues_RT_lineEdit.setGeometry(QRect(170, 350, 61, 21))
        self.Tissues_RT_lineEdit.setFont(font)
        self.Tissues_RT_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Tissues_RT_lineEdit.setAlignment(Qt.AlignCenter)
        self.biopsy_LT_checkBox = QCheckBox(self.sample_preparation_frame)
        self.biopsy_LT_checkBox.setObjectName(u"biopsy_LT_checkBox")
        self.biopsy_LT_checkBox.setGeometry(QRect(10, 380, 91, 21))
        self.biopsy_LT_checkBox.setFont(font)
        self.biopsy_LT_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.biopsy_LT_lineEdit.setObjectName(u"biopsy_LT_lineEdit")
        self.biopsy_LT_lineEdit.setGeometry(QRect(170, 380, 61, 21))
        self.biopsy_LT_lineEdit.setFont(font)
        self.biopsy_LT_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.biopsy_LT_lineEdit.setAlignment(Qt.AlignCenter)
        self.biopsy_RT_checkBox = QCheckBox(self.sample_preparation_frame)
        self.biopsy_RT_checkBox.setObjectName(u"biopsy_RT_checkBox")
        self.biopsy_RT_checkBox.setGeometry(QRect(10, 410, 91, 21))
        self.biopsy_RT_checkBox.setFont(font)
        self.biopsy_RT_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.biopsy_RT_lineEdit.setObjectName(u"biopsy_RT_lineEdit")
        self.biopsy_RT_lineEdit.setGeometry(QRect(170, 410, 61, 21))
        self.biopsy_RT_lineEdit.setFont(font)
        self.biopsy_RT_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.biopsy_RT_lineEdit.setAlignment(Qt.AlignCenter)
        self.body_fluid_LT_checkBox = QCheckBox(self.sample_preparation_frame)
        self.body_fluid_LT_checkBox.setObjectName(u"body_fluid_LT_checkBox")
        self.body_fluid_LT_checkBox.setGeometry(QRect(10, 440, 121, 21))
        self.body_fluid_LT_checkBox.setFont(font)
        self.body_fluid_LT_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.body_fluid_LT_lineEdit.setObjectName(u"body_fluid_LT_lineEdit")
        self.body_fluid_LT_lineEdit.setGeometry(QRect(170, 440, 61, 21))
        self.body_fluid_LT_lineEdit.setFont(font)
        self.body_fluid_LT_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.body_fluid_LT_lineEdit.setAlignment(Qt.AlignCenter)
        self.body_fluid_RT_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.body_fluid_RT_lineEdit.setObjectName(u"body_fluid_RT_lineEdit")
        self.body_fluid_RT_lineEdit.setGeometry(QRect(170, 470, 61, 21))
        self.body_fluid_RT_lineEdit.setFont(font)
        self.body_fluid_RT_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.body_fluid_RT_lineEdit.setAlignment(Qt.AlignCenter)
        self.body_fluid_RT_checkBox = QCheckBox(self.sample_preparation_frame)
        self.body_fluid_RT_checkBox.setObjectName(u"body_fluid_RT_checkBox")
        self.body_fluid_RT_checkBox.setGeometry(QRect(10, 470, 111, 21))
        self.body_fluid_RT_checkBox.setFont(font)
        self.csf_checkBox = QCheckBox(self.sample_preparation_frame)
        self.csf_checkBox.setObjectName(u"csf_checkBox")
        self.csf_checkBox.setGeometry(QRect(10, 500, 101, 21))
        self.csf_checkBox.setFont(font)
        self.csf_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.csf_lineEdit.setObjectName(u"csf_lineEdit")
        self.csf_lineEdit.setGeometry(QRect(170, 500, 61, 21))
        self.csf_lineEdit.setFont(font)
        self.csf_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.csf_lineEdit.setAlignment(Qt.AlignCenter)
        self.feces_checkBox = QCheckBox(self.sample_preparation_frame)
        self.feces_checkBox.setObjectName(u"feces_checkBox")
        self.feces_checkBox.setGeometry(QRect(10, 530, 81, 21))
        self.feces_checkBox.setFont(font)
        self.feces_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.feces_lineEdit.setObjectName(u"feces_lineEdit")
        self.feces_lineEdit.setGeometry(QRect(170, 530, 61, 21))
        self.feces_lineEdit.setFont(font)
        self.feces_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.feces_lineEdit.setAlignment(Qt.AlignCenter)
        self.PUS_checkBox = QCheckBox(self.sample_preparation_frame)
        self.PUS_checkBox.setObjectName(u"PUS_checkBox")
        self.PUS_checkBox.setGeometry(QRect(10, 560, 91, 21))
        self.PUS_checkBox.setFont(font)
        self.PUS_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.PUS_lineEdit.setObjectName(u"PUS_lineEdit")
        self.PUS_lineEdit.setGeometry(QRect(170, 560, 61, 21))
        self.PUS_lineEdit.setFont(font)
        self.PUS_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.PUS_lineEdit.setAlignment(Qt.AlignCenter)
        self.Blood_checkBox = QCheckBox(self.sample_preparation_frame)
        self.Blood_checkBox.setObjectName(u"Blood_checkBox")
        self.Blood_checkBox.setGeometry(QRect(10, 590, 81, 21))
        self.Blood_checkBox.setFont(font)
        self.Blood_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.Blood_lineEdit.setObjectName(u"Blood_lineEdit")
        self.Blood_lineEdit.setGeometry(QRect(170, 590, 61, 21))
        self.Blood_lineEdit.setFont(font)
        self.Blood_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Blood_lineEdit.setAlignment(Qt.AlignCenter)
        self.Blood_agar_checkBox = QCheckBox(self.sample_preparation_frame)
        self.Blood_agar_checkBox.setObjectName(u"Blood_agar_checkBox")
        self.Blood_agar_checkBox.setGeometry(QRect(10, 620, 101, 21))
        self.Blood_agar_checkBox.setFont(font)
        self.Blood_agar_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.Blood_agar_lineEdit.setObjectName(u"Blood_agar_lineEdit")
        self.Blood_agar_lineEdit.setGeometry(QRect(170, 620, 61, 21))
        self.Blood_agar_lineEdit.setFont(font)
        self.Blood_agar_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Blood_agar_lineEdit.setAlignment(Qt.AlignCenter)
        self.Skin_scraping_checkBox = QCheckBox(self.sample_preparation_frame)
        self.Skin_scraping_checkBox.setObjectName(u"Skin_scraping_checkBox")
        self.Skin_scraping_checkBox.setGeometry(QRect(10, 650, 101, 21))
        self.Skin_scraping_checkBox.setFont(font)
        self.Skin_scraping_lineEdit = QLineEdit(self.sample_preparation_frame)
        self.Skin_scraping_lineEdit.setObjectName(u"Skin_scraping_lineEdit")
        self.Skin_scraping_lineEdit.setGeometry(QRect(170, 650, 61, 21))
        self.Skin_scraping_lineEdit.setFont(font)
        self.Skin_scraping_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Skin_scraping_lineEdit.setAlignment(Qt.AlignCenter)
        self.drug_sensitivity_frame = QFrame(self.centralwidget)
        self.drug_sensitivity_frame.setObjectName(u"drug_sensitivity_frame")
        self.drug_sensitivity_frame.setGeometry(QRect(250, 0, 541, 351))
        self.drug_sensitivity_frame.setFont(font)
        self.drug_sensitivity_frame.setStyleSheet(u"background:rgb(255, 236, 226)")
        self.drug_sensitivity_frame.setFrameShape(QFrame.Box)
        self.drug_sensitivity_frame.setFrameShadow(QFrame.Raised)
        self.drug_sensitivity_frame.setLineWidth(2)
        self.drug_sensitivity_label = QLabel(self.drug_sensitivity_frame)
        self.drug_sensitivity_label.setObjectName(u"drug_sensitivity_label")
        self.drug_sensitivity_label.setGeometry(QRect(5, 5, 531, 41))
        self.drug_sensitivity_label.setFont(font)
        self.drug_sensitivity_label.setFrameShape(QFrame.Box)
        self.drug_sensitivity_label.setFrameShadow(QFrame.Raised)
        self.drug_sensitivity_label.setLineWidth(3)
        self.drug_sensitivity_label.setAlignment(Qt.AlignCenter)
        self.amikacin_AK_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.amikacin_AK_checkBox.setObjectName(u"amikacin_AK_checkBox")
        self.amikacin_AK_checkBox.setGeometry(QRect(10, 50, 121, 21))
        self.amikacin_AK_checkBox.setFont(font)
        self.Amoxycillin_AML_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Amoxycillin_AML_checkBox.setObjectName(u"Amoxycillin_AML_checkBox")
        self.Amoxycillin_AML_checkBox.setGeometry(QRect(200, 50, 131, 21))
        self.Amoxycillin_AML_checkBox.setFont(font)
        self.Amoxy_AMC_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Amoxy_AMC_checkBox.setObjectName(u"Amoxy_AMC_checkBox")
        self.Amoxy_AMC_checkBox.setGeometry(QRect(380, 50, 141, 21))
        self.Amoxy_AMC_checkBox.setFont(font)
        self.Ampicillin_AMP_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Ampicillin_AMP_checkBox.setObjectName(u"Ampicillin_AMP_checkBox")
        self.Ampicillin_AMP_checkBox.setGeometry(QRect(10, 70, 121, 21))
        self.Ampicillin_AMP_checkBox.setFont(font)
        self.Bactracin_B_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Bactracin_B_checkBox.setObjectName(u"Bactracin_B_checkBox")
        self.Bactracin_B_checkBox.setGeometry(QRect(200, 70, 111, 21))
        self.Bactracin_B_checkBox.setFont(font)
        self.Clav_AMC_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Clav_AMC_checkBox.setObjectName(u"Clav_AMC_checkBox")
        self.Clav_AMC_checkBox.setGeometry(QRect(380, 70, 141, 21))
        self.Clav_AMC_checkBox.setFont(font)
        self.Ceftazidime_CAZ_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Ceftazidime_CAZ_checkBox.setObjectName(u"Ceftazidime_CAZ_checkBox")
        self.Ceftazidime_CAZ_checkBox.setGeometry(QRect(10, 90, 131, 21))
        self.Ceftazidime_CAZ_checkBox.setFont(font)
        self.Ceftiofur_EFT_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Ceftiofur_EFT_checkBox.setObjectName(u"Ceftiofur_EFT_checkBox")
        self.Ceftiofur_EFT_checkBox.setGeometry(QRect(200, 90, 121, 21))
        self.Ceftiofur_EFT_checkBox.setFont(font)
        self.Ceftriaxone_cro_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Ceftriaxone_cro_checkBox.setObjectName(u"Ceftriaxone_cro_checkBox")
        self.Ceftriaxone_cro_checkBox.setGeometry(QRect(380, 90, 151, 21))
        self.Ceftriaxone_cro_checkBox.setFont(font)
        self.Cephalexin_CL_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Cephalexin_CL_checkBox.setObjectName(u"Cephalexin_CL_checkBox")
        self.Cephalexin_CL_checkBox.setGeometry(QRect(10, 110, 121, 21))
        self.Cephalexin_CL_checkBox.setFont(font)
        self.Cephalothin_KF_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Cephalothin_KF_checkBox.setObjectName(u"Cephalothin_KF_checkBox")
        self.Cephalothin_KF_checkBox.setGeometry(QRect(200, 110, 131, 21))
        self.Cephalothin_KF_checkBox.setFont(font)
        self.Cephazolin_KZ_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Cephazolin_KZ_checkBox.setObjectName(u"Cephazolin_KZ_checkBox")
        self.Cephazolin_KZ_checkBox.setGeometry(QRect(380, 110, 141, 21))
        self.Cephazolin_KZ_checkBox.setFont(font)
        self.Chloramphenicol_C_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Chloramphenicol_C_checkBox.setObjectName(u"Chloramphenicol_C_checkBox")
        self.Chloramphenicol_C_checkBox.setGeometry(QRect(10, 130, 151, 21))
        self.Chloramphenicol_C_checkBox.setFont(font)
        self.Ciprofloxacin_CIP_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Ciprofloxacin_CIP_checkBox.setObjectName(u"Ciprofloxacin_CIP_checkBox")
        self.Ciprofloxacin_CIP_checkBox.setGeometry(QRect(200, 130, 131, 21))
        self.Ciprofloxacin_CIP_checkBox.setFont(font)
        self.Clindamicin_DA_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Clindamicin_DA_checkBox.setObjectName(u"Clindamicin_DA_checkBox")
        self.Clindamicin_DA_checkBox.setGeometry(QRect(380, 130, 151, 21))
        self.Clindamicin_DA_checkBox.setFont(font)
        self.Cloxacillin_OB_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Cloxacillin_OB_checkBox.setObjectName(u"Cloxacillin_OB_checkBox")
        self.Cloxacillin_OB_checkBox.setGeometry(QRect(10, 150, 121, 21))
        self.Cloxacillin_OB_checkBox.setFont(font)
        self.Colistin_CT_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Colistin_CT_checkBox.setObjectName(u"Colistin_CT_checkBox")
        self.Colistin_CT_checkBox.setGeometry(QRect(200, 150, 121, 21))
        self.Colistin_CT_checkBox.setFont(font)
        self.Doxycycline_DO_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Doxycycline_DO_checkBox.setObjectName(u"Doxycycline_DO_checkBox")
        self.Doxycycline_DO_checkBox.setGeometry(QRect(380, 150, 151, 21))
        self.Doxycycline_DO_checkBox.setFont(font)
        self.Enrofloxacin_ENR_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Enrofloxacin_ENR_checkBox.setObjectName(u"Enrofloxacin_ENR_checkBox")
        self.Enrofloxacin_ENR_checkBox.setGeometry(QRect(10, 170, 131, 21))
        self.Enrofloxacin_ENR_checkBox.setFont(font)
        self.Erythromycin_E_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Erythromycin_E_checkBox.setObjectName(u"Erythromycin_E_checkBox")
        self.Erythromycin_E_checkBox.setGeometry(QRect(200, 170, 131, 21))
        self.Erythromycin_E_checkBox.setFont(font)
        self.Fosfomycin_FOS_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Fosfomycin_FOS_checkBox.setObjectName(u"Fosfomycin_FOS_checkBox")
        self.Fosfomycin_FOS_checkBox.setGeometry(QRect(380, 170, 151, 21))
        self.Fosfomycin_FOS_checkBox.setFont(font)
        self.Gentamycin_CN_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Gentamycin_CN_checkBox.setObjectName(u"Gentamycin_CN_checkBox")
        self.Gentamycin_CN_checkBox.setGeometry(QRect(10, 190, 131, 21))
        self.Gentamycin_CN_checkBox.setFont(font)
        self.Imipenem_IPM_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Imipenem_IPM_checkBox.setObjectName(u"Imipenem_IPM_checkBox")
        self.Imipenem_IPM_checkBox.setGeometry(QRect(200, 190, 131, 21))
        self.Imipenem_IPM_checkBox.setFont(font)
        self.Kanamycin_K_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Kanamycin_K_checkBox.setObjectName(u"Kanamycin_K_checkBox")
        self.Kanamycin_K_checkBox.setGeometry(QRect(380, 190, 141, 21))
        self.Kanamycin_K_checkBox.setFont(font)
        self.Lincomycin_MY_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Lincomycin_MY_checkBox.setObjectName(u"Lincomycin_MY_checkBox")
        self.Lincomycin_MY_checkBox.setGeometry(QRect(10, 210, 121, 21))
        self.Lincomycin_MY_checkBox.setFont(font)
        self.Neomycin_N_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Neomycin_N_checkBox.setObjectName(u"Neomycin_N_checkBox")
        self.Neomycin_N_checkBox.setGeometry(QRect(200, 210, 121, 21))
        self.Neomycin_N_checkBox.setFont(font)
        self.Nitrofurantoin_F_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Nitrofurantoin_F_checkBox.setObjectName(u"Nitrofurantoin_F_checkBox")
        self.Nitrofurantoin_F_checkBox.setGeometry(QRect(380, 210, 151, 21))
        self.Nitrofurantoin_F_checkBox.setFont(font)
        self.Norfloxacin_NOR_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Norfloxacin_NOR_checkBox.setObjectName(u"Norfloxacin_NOR_checkBox")
        self.Norfloxacin_NOR_checkBox.setGeometry(QRect(10, 230, 131, 21))
        self.Norfloxacin_NOR_checkBox.setFont(font)
        self.Novobiocin_NV_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Novobiocin_NV_checkBox.setObjectName(u"Novobiocin_NV_checkBox")
        self.Novobiocin_NV_checkBox.setGeometry(QRect(200, 230, 131, 21))
        self.Novobiocin_NV_checkBox.setFont(font)
        self.Optocin_OP_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Optocin_OP_checkBox.setObjectName(u"Optocin_OP_checkBox")
        self.Optocin_OP_checkBox.setGeometry(QRect(380, 230, 121, 21))
        self.Optocin_OP_checkBox.setFont(font)
        self.Oxacillin_OX_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Oxacillin_OX_checkBox.setObjectName(u"Oxacillin_OX_checkBox")
        self.Oxacillin_OX_checkBox.setGeometry(QRect(10, 250, 101, 21))
        self.Oxacillin_OX_checkBox.setFont(font)
        self.Oxytetracycline_OT_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Oxytetracycline_OT_checkBox.setObjectName(u"Oxytetracycline_OT_checkBox")
        self.Oxytetracycline_OT_checkBox.setGeometry(QRect(200, 250, 141, 21))
        self.Oxytetracycline_OT_checkBox.setFont(font)
        self.PeniciliinG_P_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.PeniciliinG_P_checkBox.setObjectName(u"PeniciliinG_P_checkBox")
        self.PeniciliinG_P_checkBox.setGeometry(QRect(380, 250, 131, 21))
        self.PeniciliinG_P_checkBox.setFont(font)
        self.PolymyxcinB_PB_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.PolymyxcinB_PB_checkBox.setObjectName(u"PolymyxcinB_PB_checkBox")
        self.PolymyxcinB_PB_checkBox.setGeometry(QRect(10, 270, 121, 21))
        self.PolymyxcinB_PB_checkBox.setFont(font)
        self.Rifampicin_RD_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Rifampicin_RD_checkBox.setObjectName(u"Rifampicin_RD_checkBox")
        self.Rifampicin_RD_checkBox.setGeometry(QRect(200, 270, 131, 21))
        self.Rifampicin_RD_checkBox.setFont(font)
        self.Streptomycin_S_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Streptomycin_S_checkBox.setObjectName(u"Streptomycin_S_checkBox")
        self.Streptomycin_S_checkBox.setGeometry(QRect(380, 270, 151, 21))
        self.Streptomycin_S_checkBox.setFont(font)
        self.Sulfa_trimetroprom_STX_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Sulfa_trimetroprom_STX_checkBox.setObjectName(u"Sulfa_trimetroprom_STX_checkBox")
        self.Sulfa_trimetroprom_STX_checkBox.setGeometry(QRect(10, 290, 161, 21))
        self.Sulfa_trimetroprom_STX_checkBox.setFont(font)
        self.Tetracycline_TE_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Tetracycline_TE_checkBox.setObjectName(u"Tetracycline_TE_checkBox")
        self.Tetracycline_TE_checkBox.setGeometry(QRect(200, 290, 121, 21))
        self.Tetracycline_TE_checkBox.setFont(font)
        self.Tobramycin_TOB_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Tobramycin_TOB_checkBox.setObjectName(u"Tobramycin_TOB_checkBox")
        self.Tobramycin_TOB_checkBox.setGeometry(QRect(380, 290, 141, 21))
        self.Tobramycin_TOB_checkBox.setFont(font)
        self.Vancomycin_VA_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.Vancomycin_VA_checkBox.setObjectName(u"Vancomycin_VA_checkBox")
        self.Vancomycin_VA_checkBox.setGeometry(QRect(10, 310, 121, 21))
        self.Vancomycin_VA_checkBox.setFont(font)
        self.others_checkBox = QCheckBox(self.drug_sensitivity_frame)
        self.others_checkBox.setObjectName(u"others_checkBox")
        self.others_checkBox.setGeometry(QRect(200, 310, 21, 21))
        self.others_checkBox.setFont(font)
        self.others_lineEdit = QLineEdit(self.drug_sensitivity_frame)
        self.others_lineEdit.setObjectName(u"others_lineEdit")
        self.others_lineEdit.setGeometry(QRect(220, 310, 291, 21))
        self.others_lineEdit.setFont(font)
        self.others_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.others_lineEdit.setAlignment(Qt.AlignCenter)
        self.bacterial_iden_frame = QFrame(self.centralwidget)
        self.bacterial_iden_frame.setObjectName(u"bacterial_iden_frame")
        self.bacterial_iden_frame.setGeometry(QRect(250, 360, 541, 161))
        self.bacterial_iden_frame.setFont(font)
        self.bacterial_iden_frame.setStyleSheet(u"background:rgb(255, 236, 226)")
        self.bacterial_iden_frame.setFrameShape(QFrame.Box)
        self.bacterial_iden_frame.setFrameShadow(QFrame.Raised)
        self.bacterial_iden_frame.setLineWidth(2)
        self.bacterial_iden_label = QLabel(self.bacterial_iden_frame)
        self.bacterial_iden_label.setObjectName(u"bacterial_iden_label")
        self.bacterial_iden_label.setGeometry(QRect(5, 5, 521, 41))
        self.bacterial_iden_label.setFont(font)
        self.bacterial_iden_label.setFrameShape(QFrame.Box)
        self.bacterial_iden_label.setFrameShadow(QFrame.Raised)
        self.bacterial_iden_label.setLineWidth(3)
        self.bacterial_iden_label.setAlignment(Qt.AlignCenter)
        self.Actinobacillus_checkBox = QCheckBox(self.bacterial_iden_frame)
        self.Actinobacillus_checkBox.setObjectName(u"Actinobacillus_checkBox")
        self.Actinobacillus_checkBox.setGeometry(QRect(10, 50, 191, 21))
        self.Actinobacillus_checkBox.setFont(font)
        self.Aeromonas_checkBox = QCheckBox(self.bacterial_iden_frame)
        self.Aeromonas_checkBox.setObjectName(u"Aeromonas_checkBox")
        self.Aeromonas_checkBox.setGeometry(QRect(203, 50, 151, 21))
        self.Aeromonas_checkBox.setFont(font)
        self.Bordetella_checkBox = QCheckBox(self.bacterial_iden_frame)
        self.Bordetella_checkBox.setObjectName(u"Bordetella_checkBox")
        self.Bordetella_checkBox.setGeometry(QRect(380, 50, 151, 21))
        self.Bordetella_checkBox.setFont(font)
        self.Corynebacterium_checkBox = QCheckBox(self.bacterial_iden_frame)
        self.Corynebacterium_checkBox.setObjectName(u"Corynebacterium_checkBox")
        self.Corynebacterium_checkBox.setGeometry(QRect(10, 78, 191, 21))
        self.Corynebacterium_checkBox.setFont(font)
        self.Enterobacter_checkBox = QCheckBox(self.bacterial_iden_frame)
        self.Enterobacter_checkBox.setObjectName(u"Enterobacter_checkBox")
        self.Enterobacter_checkBox.setGeometry(QRect(203, 78, 191, 21))
        self.Enterobacter_checkBox.setFont(font)
        self.Escherichia_checkBox = QCheckBox(self.bacterial_iden_frame)
        self.Escherichia_checkBox.setObjectName(u"Escherichia_checkBox")
        self.Escherichia_checkBox.setGeometry(QRect(380, 78, 141, 21))
        self.Escherichia_checkBox.setFont(font)
        self.Klebsiella_checkBox = QCheckBox(self.bacterial_iden_frame)
        self.Klebsiella_checkBox.setObjectName(u"Klebsiella_checkBox")
        self.Klebsiella_checkBox.setGeometry(QRect(10, 104, 191, 21))
        self.Klebsiella_checkBox.setFont(font)
        self.Pasteurella_checkBox = QCheckBox(self.bacterial_iden_frame)
        self.Pasteurella_checkBox.setObjectName(u"Pasteurella_checkBox")
        self.Pasteurella_checkBox.setGeometry(QRect(203, 104, 191, 21))
        self.Pasteurella_checkBox.setFont(font)
        self.Salmonella_checkBox = QCheckBox(self.bacterial_iden_frame)
        self.Salmonella_checkBox.setObjectName(u"Salmonella_checkBox")
        self.Salmonella_checkBox.setGeometry(QRect(380, 104, 151, 21))
        self.Salmonella_checkBox.setFont(font)
        self.Streptococus_checkBox = QCheckBox(self.bacterial_iden_frame)
        self.Streptococus_checkBox.setObjectName(u"Streptococus_checkBox")
        self.Streptococus_checkBox.setGeometry(QRect(10, 132, 191, 21))
        self.Streptococus_checkBox.setFont(font)
        self.Staphylococcus_checkBox = QCheckBox(self.bacterial_iden_frame)
        self.Staphylococcus_checkBox.setObjectName(u"Staphylococcus_checkBox")
        self.Staphylococcus_checkBox.setGeometry(QRect(203, 132, 191, 21))
        self.Staphylococcus_checkBox.setFont(font)
        self.iden_others_checkBox = QCheckBox(self.bacterial_iden_frame)
        self.iden_others_checkBox.setObjectName(u"iden_others_checkBox")
        self.iden_others_checkBox.setGeometry(QRect(380, 130, 21, 21))
        self.iden_others_checkBox.setFont(font)
        self.bacterial_others_lineEdit = QLineEdit(self.bacterial_iden_frame)
        self.bacterial_others_lineEdit.setObjectName(u"bacterial_others_lineEdit")
        self.bacterial_others_lineEdit.setGeometry(QRect(397, 130, 131, 21))
        self.bacterial_others_lineEdit.setFont(font)
        self.bacterial_others_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.bacterial_others_lineEdit.setAlignment(Qt.AlignCenter)
        self.laboratory_re_frame = QFrame(self.centralwidget)
        self.laboratory_re_frame.setObjectName(u"laboratory_re_frame")
        self.laboratory_re_frame.setGeometry(QRect(800, 0, 311, 261))
        self.laboratory_re_frame.setFont(font)
        self.laboratory_re_frame.setStyleSheet(u"background:rgb(255, 236, 226)")
        self.laboratory_re_frame.setFrameShape(QFrame.Box)
        self.laboratory_re_frame.setFrameShadow(QFrame.Raised)
        self.laboratory_re_frame.setLineWidth(2)
        self.laboratory_re_label = QLabel(self.laboratory_re_frame)
        self.laboratory_re_label.setObjectName(u"laboratory_re_label")
        self.laboratory_re_label.setGeometry(QRect(5, 5, 301, 41))
        self.laboratory_re_label.setFont(font)
        self.laboratory_re_label.setFrameShape(QFrame.Box)
        self.laboratory_re_label.setFrameShadow(QFrame.Raised)
        self.laboratory_re_label.setLineWidth(3)
        self.laboratory_re_label.setAlignment(Qt.AlignCenter)
        self.Fungal_cul_checkBox = QCheckBox(self.laboratory_re_frame)
        self.Fungal_cul_checkBox.setObjectName(u"Fungal_cul_checkBox")
        self.Fungal_cul_checkBox.setGeometry(QRect(10, 50, 271, 31))
        self.Fungal_cul_checkBox.setFont(font)
        self.Bacterial_iden_checkBox = QCheckBox(self.laboratory_re_frame)
        self.Bacterial_iden_checkBox.setObjectName(u"Bacterial_iden_checkBox")
        self.Bacterial_iden_checkBox.setGeometry(QRect(10, 80, 291, 31))
        self.Bacterial_iden_checkBox.setFont(font)
        self.VITEK2_with_checkBox = QCheckBox(self.laboratory_re_frame)
        self.VITEK2_with_checkBox.setObjectName(u"VITEK2_with_checkBox")
        self.VITEK2_with_checkBox.setGeometry(QRect(10, 110, 251, 31))
        self.VITEK2_with_checkBox.setFont(font)
        self.VITEK2_iden_checkBox = QCheckBox(self.laboratory_re_frame)
        self.VITEK2_iden_checkBox.setObjectName(u"VITEK2_iden_checkBox")
        self.VITEK2_iden_checkBox.setGeometry(QRect(10, 140, 251, 31))
        self.VITEK2_iden_checkBox.setFont(font)
        self.MIC_checkBox = QCheckBox(self.laboratory_re_frame)
        self.MIC_checkBox.setObjectName(u"MIC_checkBox")
        self.MIC_checkBox.setGeometry(QRect(10, 170, 281, 31))
        self.MIC_checkBox.setFont(font)
        self.summary_frame = QFrame(self.centralwidget)
        self.summary_frame.setObjectName(u"summary_frame")
        self.summary_frame.setGeometry(QRect(800, 270, 311, 411))
        self.summary_frame.setFont(font)
        self.summary_frame.setStyleSheet(u"background:rgb(255, 236, 226)")
        self.summary_frame.setFrameShape(QFrame.Box)
        self.summary_frame.setFrameShadow(QFrame.Raised)
        self.summary_frame.setLineWidth(2)
        self.summary_Button = QPushButton(self.summary_frame)
        self.summary_Button.setObjectName(u"summary_Button")
        self.summary_Button.setGeometry(QRect(30, 10, 251, 51))
        font1 = QFont()
        font1.setFamilies([u"TH Niramit AS"])
        font1.setPointSize(16)
        self.summary_Button.setFont(font1)
        self.summary_Button.setStyleSheet(u"background:rgb(170, 255, 255)")
        self.amount_label = QLabel(self.summary_frame)
        self.amount_label.setObjectName(u"amount_label")
        self.amount_label.setGeometry(QRect(30, 90, 101, 31))
        self.amount_label.setFont(font1)
        self.amount_lineEdit = QLineEdit(self.summary_frame)
        self.amount_lineEdit.setObjectName(u"amount_lineEdit")
        self.amount_lineEdit.setGeometry(QRect(30, 120, 141, 31))
        self.amount_lineEdit.setFont(font)
        self.amount_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.amount_lineEdit.setAlignment(Qt.AlignCenter)
        self.list_label = QLabel(self.summary_frame)
        self.list_label.setObjectName(u"list_label")
        self.list_label.setGeometry(QRect(190, 120, 71, 41))
        self.list_label.setFont(font1)
        self.cost_label = QLabel(self.summary_frame)
        self.cost_label.setObjectName(u"cost_label")
        self.cost_label.setGeometry(QRect(30, 180, 101, 31))
        self.cost_label.setFont(font1)
        self.cost_lineEdit = QLineEdit(self.summary_frame)
        self.cost_lineEdit.setObjectName(u"cost_lineEdit")
        self.cost_lineEdit.setGeometry(QRect(30, 210, 141, 31))
        self.cost_lineEdit.setFont(font)
        self.cost_lineEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.cost_lineEdit.setAlignment(Qt.AlignCenter)
        self.cost_unit_label = QLabel(self.summary_frame)
        self.cost_unit_label.setObjectName(u"cost_unit_label")
        self.cost_unit_label.setGeometry(QRect(200, 210, 41, 41))
        self.cost_unit_label.setFont(font1)
        self.save_data_pushButton = QPushButton(self.summary_frame)
        self.save_data_pushButton.setObjectName(u"save_data_pushButton")
        self.save_data_pushButton.setGeometry(QRect(30, 270, 251, 51))
        self.save_data_pushButton.setFont(font1)
        self.save_data_pushButton.setStyleSheet(u"background:rgb(0, 255, 127)")
        self.cancel_pushButton = QPushButton(self.summary_frame)
        self.cancel_pushButton.setObjectName(u"cancel_pushButton")
        self.cancel_pushButton.setGeometry(QRect(30, 340, 251, 51))
        self.cancel_pushButton.setFont(font1)
        self.cancel_pushButton.setStyleSheet(u"background:rgb(255, 85, 0)")
        self.remark_frame = QFrame(self.centralwidget)
        self.remark_frame.setObjectName(u"remark_frame")
        self.remark_frame.setGeometry(QRect(250, 530, 541, 151))
        self.remark_frame.setFont(font)
        self.remark_frame.setStyleSheet(u"background:rgb(255, 236, 226)")
        self.remark_frame.setFrameShape(QFrame.Box)
        self.remark_frame.setFrameShadow(QFrame.Raised)
        self.remark_frame.setLineWidth(2)
        self.remark_textEdit = QTextEdit(self.remark_frame)
        self.remark_textEdit.setObjectName(u"remark_textEdit")
        self.remark_textEdit.setGeometry(QRect(9, 45, 521, 91))
        self.remark_textEdit.setFont(font)
        self.remark_textEdit.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.remark_textEdit.setFrameShape(QFrame.Box)
        self.remark_textEdit.setFrameShadow(QFrame.Plain)
        self.remark_textEdit.setLineWidth(2)
        self.remark_label = QLabel(self.remark_frame)
        self.remark_label.setObjectName(u"remark_label")
        self.remark_label.setGeometry(QRect(0, 0, 541, 41))
        self.remark_label.setFont(font)
        self.remark_label.setFrameShape(QFrame.Box)
        self.remark_label.setFrameShadow(QFrame.Raised)
        self.remark_label.setLineWidth(2)
        self.remark_label.setAlignment(Qt.AlignCenter)
        BACTERIE.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(BACTERIE)
        self.statusbar.setObjectName(u"statusbar")
        BACTERIE.setStatusBar(self.statusbar)

        self.retranslateUi(BACTERIE)

        QMetaObject.connectSlotsByName(BACTERIE)
    # setupUi

    def retranslateUi(self, BACTERIE):
        BACTERIE.setWindowTitle(QCoreApplication.translate("BACTERIE", u"BACTERIE", None))
        self.sample_preparation_label.setText(QCoreApplication.translate("BACTERIE", u"SAMPLE PREPARATION", None))
        self.sample_label.setText(QCoreApplication.translate("BACTERIE", u"SAMPLE", None))
        self.swab_LT_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Swab [LT]", None))
        self.swab_RT_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Swab [RT]", None))
        self.wound_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Wound", None))
        self.Aspirate_LT_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Aspirate [LT]", None))
        self.Aspirate_RT_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Aspirate [RT]", None))
        self.urine_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Urine", None))
        self.Midstream_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Midstream", None))
        self.Catheterization_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Catheterization ", None))
        self.Cystocentesis_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Cystocentesis", None))
        self.Tissues_LT_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Tissues [LT]", None))
        self.Tissues_RT_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Tissues [RT]", None))
        self.biopsy_LT_checkBox.setText(QCoreApplication.translate("BACTERIE", u"biopsy [LT]", None))
        self.biopsy_RT_checkBox.setText(QCoreApplication.translate("BACTERIE", u"biopsy [RT]", None))
        self.body_fluid_LT_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Body fluid [LT]", None))
        self.body_fluid_RT_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Body fluid [RT]", None))
        self.csf_checkBox.setText(QCoreApplication.translate("BACTERIE", u"CSF", None))
        self.feces_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Feces ", None))
        self.PUS_checkBox.setText(QCoreApplication.translate("BACTERIE", u"PUS ", None))
        self.Blood_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Blood", None))
        self.Blood_agar_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Blood agar", None))
        self.Skin_scraping_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Skin scraping ", None))
        self.drug_sensitivity_label.setText(QCoreApplication.translate("BACTERIE", u"DRUG SENSITIVITY (6-8 DRUGS)", None))
        self.amikacin_AK_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Amikacin(AK)", None))
        self.Amoxycillin_AML_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Amoxycillin(AML)", None))
        self.Amoxy_AMC_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Amoxy(AMC)", None))
        self.Ampicillin_AMP_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Ampicillin(AMP)", None))
        self.Bactracin_B_checkBox.setText(QCoreApplication.translate("BACTERIE", u" Bactracin(B)", None))
        self.Clav_AMC_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Clav(AMC)", None))
        self.Ceftazidime_CAZ_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Ceftazidime(CAZ)", None))
        self.Ceftiofur_EFT_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Ceftiofur(EFT)", None))
        self.Ceftriaxone_cro_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Ceftriaxone(CRO)", None))
        self.Cephalexin_CL_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Cephalexin(CL)", None))
        self.Cephalothin_KF_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Cephalothin(KF)", None))
        self.Cephazolin_KZ_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Cephazolin(KZ)", None))
        self.Chloramphenicol_C_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Chloramphenicol(C)", None))
        self.Ciprofloxacin_CIP_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Ciprofloxacin(CIP)", None))
        self.Clindamicin_DA_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Clindamicin(DA)", None))
        self.Cloxacillin_OB_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Cloxacillin(OB)", None))
        self.Colistin_CT_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Colistin(CT)", None))
        self.Doxycycline_DO_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Doxycycline(DO)", None))
        self.Enrofloxacin_ENR_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Enrofloxacin(ENR)", None))
        self.Erythromycin_E_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Erythromycin(E)", None))
        self.Fosfomycin_FOS_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Fosfomycin(FOS)", None))
        self.Gentamycin_CN_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Gentamycin(CN)", None))
        self.Imipenem_IPM_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Imipenem(IPM)", None))
        self.Kanamycin_K_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Kanamycin(K)", None))
        self.Lincomycin_MY_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Lincomycin(MY)", None))
        self.Neomycin_N_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Neomycin(N)", None))
        self.Nitrofurantoin_F_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Nitrofurantoin(F)", None))
        self.Norfloxacin_NOR_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Norfloxacin(NOR)", None))
        self.Novobiocin_NV_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Novobiocin(NV)", None))
        self.Optocin_OP_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Optocin(OP)", None))
        self.Oxacillin_OX_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Oxacillin(OX)", None))
        self.Oxytetracycline_OT_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Oxytetracycline(OT)", None))
        self.PeniciliinG_P_checkBox.setText(QCoreApplication.translate("BACTERIE", u"PeniciliinG(P)", None))
        self.PolymyxcinB_PB_checkBox.setText(QCoreApplication.translate("BACTERIE", u"PolymyxcinB(PB)", None))
        self.Rifampicin_RD_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Rifampicin(RD)", None))
        self.Streptomycin_S_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Streptomycin(S)", None))
        self.Sulfa_trimetroprom_STX_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Sulfa-Trimetroprom(SXT)", None))
        self.Tetracycline_TE_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Tetracycline(TE)", None))
        self.Tobramycin_TOB_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Tobramycin(TOB)", None))
        self.Vancomycin_VA_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Vancomycin(VA)", None))
        self.others_checkBox.setText("")
        self.bacterial_iden_label.setText(QCoreApplication.translate("BACTERIE", u"BACTERIAL IDENTIFICATION (250)", None))
        self.Actinobacillus_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Actinobacillus spp.", None))
        self.Aeromonas_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Aeromonas spp.", None))
        self.Bordetella_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Bordetella spp.", None))
        self.Corynebacterium_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Corynebacterium spp.", None))
        self.Enterobacter_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Enterobacter spp.", None))
        self.Escherichia_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Escherichia coli", None))
        self.Klebsiella_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Klebsiella spp.", None))
        self.Pasteurella_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Pasteurella spp.", None))
        self.Salmonella_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Salmonella spp.", None))
        self.Streptococus_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Streptococus spp.", None))
        self.Staphylococcus_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Staphylococcus spp.", None))
        self.iden_others_checkBox.setText("")
        self.laboratory_re_label.setText(QCoreApplication.translate("BACTERIE", u"LABORATORY REQUEST FOR", None))
        self.Fungal_cul_checkBox.setText(QCoreApplication.translate("BACTERIE", u" Fungal culture and identification (250)", None))
        self.Bacterial_iden_checkBox.setText(QCoreApplication.translate("BACTERIE", u"Bacterial identification and drug sensitivity (250)", None))
        self.VITEK2_with_checkBox.setText(QCoreApplication.translate("BACTERIE", u"VITEK2 with MIC (950) ", None))
        self.VITEK2_iden_checkBox.setText(QCoreApplication.translate("BACTERIE", u"VITEK2 iden (550) ", None))
        self.MIC_checkBox.setText(QCoreApplication.translate("BACTERIE", u"MIC (550)", None))
        self.summary_Button.setText(QCoreApplication.translate("BACTERIE", u"\u0e04\u0e33\u0e19\u0e27\u0e13\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23\u0e15\u0e23\u0e27\u0e08", None))
        self.amount_label.setText(QCoreApplication.translate("BACTERIE", u"\u0e08\u0e33\u0e19\u0e27\u0e19", None))
        self.list_label.setText(QCoreApplication.translate("BACTERIE", u"\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23", None))
        self.cost_label.setText(QCoreApplication.translate("BACTERIE", u"\u0e04\u0e48\u0e32\u0e43\u0e0a\u0e49\u0e08\u0e48\u0e32\u0e22", None))
        self.cost_unit_label.setText(QCoreApplication.translate("BACTERIE", u"\u0e1a\u0e32\u0e17", None))
        self.save_data_pushButton.setText(QCoreApplication.translate("BACTERIE", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25", None))
        self.cancel_pushButton.setText(QCoreApplication.translate("BACTERIE", u"\u0e22\u0e01\u0e40\u0e25\u0e34\u0e01\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23", None))
        self.remark_label.setText(QCoreApplication.translate("BACTERIE", u"REMARK", None))
    # retranslateUi

