# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'F3_parasite_biology.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_UI_parasite(object):
    def setupUi(self, UI_parasite):
        if not UI_parasite.objectName():
            UI_parasite.setObjectName(u"UI_parasite")
        UI_parasite.resize(1100, 600)
        UI_parasite.setMinimumSize(QSize(1100, 600))
        UI_parasite.setMaximumSize(QSize(1100, 600))
        UI_parasite.setStyleSheet(u"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(206, 255, 230, 255), stop:0.55 rgba(224, 235, 188, 255), stop:0.98 rgba(210, 219, 165, 255), stop:1 rgba(0, 0, 0, 0))")
        self.centralwidget = QWidget(UI_parasite)
        self.centralwidget.setObjectName(u"centralwidget")
        self.test_label = QLabel(self.centralwidget)
        self.test_label.setObjectName(u"test_label")
        self.test_label.setGeometry(QRect(10, 5, 771, 41))
        font = QFont()
        font.setFamilies([u"Times New Roman"])
        font.setPointSize(10)
        font.setBold(True)
        self.test_label.setFont(font)
        self.test_label.setStyleSheet(u"background:rgb(170, 255, 255)")
        self.test_label.setFrameShape(QFrame.Box)
        self.test_label.setLineWidth(2)
        self.test_label.setAlignment(Qt.AlignCenter)
        self.test_frame = QFrame(self.centralwidget)
        self.test_frame.setObjectName(u"test_frame")
        self.test_frame.setGeometry(QRect(10, 50, 771, 231))
        font1 = QFont()
        font1.setFamilies([u"Times New Roman"])
        font1.setPointSize(10)
        self.test_frame.setFont(font1)
        self.test_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.test_frame.setFrameShape(QFrame.Box)
        self.test_frame.setFrameShadow(QFrame.Plain)
        self.test_frame.setLineWidth(2)
        self.PCV_checkBox = QCheckBox(self.test_frame)
        self.PCV_checkBox.setObjectName(u"PCV_checkBox")
        self.PCV_checkBox.setGeometry(QRect(10, 10, 321, 21))
        self.PCV_checkBox.setFont(font)
        self.Stained_checkBox = QCheckBox(self.test_frame)
        self.Stained_checkBox.setObjectName(u"Stained_checkBox")
        self.Stained_checkBox.setGeometry(QRect(210, 10, 321, 21))
        self.Stained_checkBox.setFont(font)
        self.woo_s_checkBox = QCheckBox(self.test_frame)
        self.woo_s_checkBox.setObjectName(u"woo_s_checkBox")
        self.woo_s_checkBox.setGeometry(QRect(510, 10, 231, 21))
        self.woo_s_checkBox.setFont(font)
        self.Stained_blood_smear_checkBox = QCheckBox(self.test_frame)
        self.Stained_blood_smear_checkBox.setObjectName(u"Stained_blood_smear_checkBox")
        self.Stained_blood_smear_checkBox.setGeometry(QRect(10, 140, 391, 21))
        self.Stained_blood_smear_checkBox.setFont(font)
        self.Floatation_centrifugal_checkBox = QCheckBox(self.test_frame)
        self.Floatation_centrifugal_checkBox.setObjectName(u"Floatation_centrifugal_checkBox")
        self.Floatation_centrifugal_checkBox.setGeometry(QRect(10, 190, 401, 21))
        self.Floatation_centrifugal_checkBox.setFont(font)
        self.Floatation_checkBox = QCheckBox(self.test_frame)
        self.Floatation_checkBox.setObjectName(u"Floatation_checkBox")
        self.Floatation_checkBox.setGeometry(QRect(10, 30, 321, 31))
        self.Floatation_checkBox.setFont(font)
        self.Sedimentation_checkBox = QCheckBox(self.test_frame)
        self.Sedimentation_checkBox.setObjectName(u"Sedimentation_checkBox")
        self.Sedimentation_checkBox.setGeometry(QRect(210, 30, 271, 31))
        self.Sedimentation_checkBox.setFont(font)
        self.MC_master_checkBox = QCheckBox(self.test_frame)
        self.MC_master_checkBox.setObjectName(u"MC_master_checkBox")
        self.MC_master_checkBox.setGeometry(QRect(510, 30, 241, 31))
        self.MC_master_checkBox.setFont(font)
        self.Centrifugal_checkBox = QCheckBox(self.test_frame)
        self.Centrifugal_checkBox.setObjectName(u"Centrifugal_checkBox")
        self.Centrifugal_checkBox.setGeometry(QRect(10, 160, 401, 31))
        self.Centrifugal_checkBox.setFont(font)
        self.Floatation_for_dog_checkBox = QCheckBox(self.test_frame)
        self.Floatation_for_dog_checkBox.setObjectName(u"Floatation_for_dog_checkBox")
        self.Floatation_for_dog_checkBox.setGeometry(QRect(10, 110, 411, 21))
        self.Floatation_for_dog_checkBox.setFont(font)
        self.Parasite_in_meat_checkBox = QCheckBox(self.test_frame)
        self.Parasite_in_meat_checkBox.setObjectName(u"Parasite_in_meat_checkBox")
        self.Parasite_in_meat_checkBox.setGeometry(QRect(10, 60, 321, 21))
        self.Parasite_in_meat_checkBox.setFont(font)
        self.Parasite_iden_checkBox = QCheckBox(self.test_frame)
        self.Parasite_iden_checkBox.setObjectName(u"Parasite_iden_checkBox")
        self.Parasite_iden_checkBox.setGeometry(QRect(10, 80, 321, 31))
        self.Parasite_iden_checkBox.setFont(font)
        self.parasite_summary_frame = QFrame(self.centralwidget)
        self.parasite_summary_frame.setObjectName(u"parasite_summary_frame")
        self.parasite_summary_frame.setGeometry(QRect(799, 5, 295, 371))
        self.parasite_summary_frame.setFont(font1)
        self.parasite_summary_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.parasite_summary_frame.setFrameShape(QFrame.Box)
        self.parasite_summary_frame.setFrameShadow(QFrame.Plain)
        self.parasite_summary_frame.setLineWidth(2)
        self.parasite_summary_pushButton = QPushButton(self.parasite_summary_frame)
        self.parasite_summary_pushButton.setObjectName(u"parasite_summary_pushButton")
        self.parasite_summary_pushButton.setGeometry(QRect(20, 10, 261, 41))
        font2 = QFont()
        font2.setFamilies([u"TH Niramit AS"])
        font2.setPointSize(16)
        font2.setBold(True)
        self.parasite_summary_pushButton.setFont(font2)
        self.parasite_summary_pushButton.setStyleSheet(u"background:rgb(170, 255, 255)")
        self.parasite_cost_frame = QFrame(self.parasite_summary_frame)
        self.parasite_cost_frame.setObjectName(u"parasite_cost_frame")
        self.parasite_cost_frame.setGeometry(QRect(20, 60, 261, 171))
        self.parasite_cost_frame.setFont(font1)
        self.parasite_cost_frame.setFrameShape(QFrame.Box)
        self.parasite_cost_frame.setFrameShadow(QFrame.Plain)
        self.parasite_cost_frame.setLineWidth(2)
        self.parasite_amount_label = QLabel(self.parasite_cost_frame)
        self.parasite_amount_label.setObjectName(u"parasite_amount_label")
        self.parasite_amount_label.setGeometry(QRect(10, 10, 61, 31))
        self.parasite_amount_label.setFont(font2)
        self.parasite_amount_lineEdit = QLineEdit(self.parasite_cost_frame)
        self.parasite_amount_lineEdit.setObjectName(u"parasite_amount_lineEdit")
        self.parasite_amount_lineEdit.setGeometry(QRect(10, 40, 171, 31))
        self.parasite_amount_lineEdit.setFont(font)
        self.parasite_amount_lineEdit.setAlignment(Qt.AlignCenter)
        self.parasite_number_amount_label = QLabel(self.parasite_cost_frame)
        self.parasite_number_amount_label.setObjectName(u"parasite_number_amount_label")
        self.parasite_number_amount_label.setGeometry(QRect(190, 40, 61, 31))
        self.parasite_number_amount_label.setFont(font2)
        self.parasite_cost_label = QLabel(self.parasite_cost_frame)
        self.parasite_cost_label.setObjectName(u"parasite_cost_label")
        self.parasite_cost_label.setGeometry(QRect(10, 90, 71, 31))
        self.parasite_cost_label.setFont(font2)
        self.parasite_cost_lineEdit = QLineEdit(self.parasite_cost_frame)
        self.parasite_cost_lineEdit.setObjectName(u"parasite_cost_lineEdit")
        self.parasite_cost_lineEdit.setGeometry(QRect(10, 120, 171, 31))
        self.parasite_cost_lineEdit.setFont(font)
        self.parasite_cost_lineEdit.setAlignment(Qt.AlignCenter)
        self.parasite_cost_unit_label = QLabel(self.parasite_cost_frame)
        self.parasite_cost_unit_label.setObjectName(u"parasite_cost_unit_label")
        self.parasite_cost_unit_label.setGeometry(QRect(190, 120, 41, 31))
        self.parasite_cost_unit_label.setFont(font2)
        self.parasite_save_data_pushButton = QPushButton(self.parasite_summary_frame)
        self.parasite_save_data_pushButton.setObjectName(u"parasite_save_data_pushButton")
        self.parasite_save_data_pushButton.setGeometry(QRect(20, 240, 261, 51))
        self.parasite_save_data_pushButton.setFont(font)
        self.parasite_save_data_pushButton.setStyleSheet(u"background:rgb(170, 255, 127)")
        self.parasite_cancel_pushButton = QPushButton(self.parasite_summary_frame)
        self.parasite_cancel_pushButton.setObjectName(u"parasite_cancel_pushButton")
        self.parasite_cancel_pushButton.setGeometry(QRect(20, 300, 261, 51))
        self.parasite_cancel_pushButton.setFont(font)
        self.parasite_cancel_pushButton.setStyleSheet(u"background:rgb(255, 85, 0)")
        UI_parasite.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(UI_parasite)
        self.statusbar.setObjectName(u"statusbar")
        UI_parasite.setStatusBar(self.statusbar)

        self.retranslateUi(UI_parasite)

        QMetaObject.connectSlotsByName(UI_parasite)
    # setupUi

    def retranslateUi(self, UI_parasite):
        UI_parasite.setWindowTitle(QCoreApplication.translate("UI_parasite", u"PARASITE", None))
        self.test_label.setText(QCoreApplication.translate("UI_parasite", u"TEST", None))
        self.PCV_checkBox.setText(QCoreApplication.translate("UI_parasite", u"PCV (50)", None))
        self.Stained_checkBox.setText(QCoreApplication.translate("UI_parasite", u"Stained blood smear (100)", None))
        self.woo_s_checkBox.setText(QCoreApplication.translate("UI_parasite", u"Woo\u2019s (50)", None))
        self.Stained_blood_smear_checkBox.setText(QCoreApplication.translate("UI_parasite", u"Stained blood smear + Woo\u2019s + PCV (150)", None))
        self.Floatation_centrifugal_checkBox.setText(QCoreApplication.translate("UI_parasite", u"Floatation test + Centrifugal sedimentation for dog and cat (200)", None))
        self.Floatation_checkBox.setText(QCoreApplication.translate("UI_parasite", u"Floatation (50)", None))
        self.Sedimentation_checkBox.setText(QCoreApplication.translate("UI_parasite", u"Sedimentation (50)", None))
        self.MC_master_checkBox.setText(QCoreApplication.translate("UI_parasite", u"Mc Master egg count (100)", None))
        self.Centrifugal_checkBox.setText(QCoreApplication.translate("UI_parasite", u"Centrifugal sedimentation for dog and cat (150)	", None))
        self.Floatation_for_dog_checkBox.setText(QCoreApplication.translate("UI_parasite", u"Floatation for dog and cat (100)", None))
        self.Parasite_in_meat_checkBox.setText(QCoreApplication.translate("UI_parasite", u"Parasite in meat (300)", None))
        self.Parasite_iden_checkBox.setText(QCoreApplication.translate("UI_parasite", u"Parasite identification (100)", None))
        self.parasite_summary_pushButton.setText(QCoreApplication.translate("UI_parasite", u"\u0e1b\u0e23\u0e30\u0e40\u0e21\u0e34\u0e19\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23\u0e17\u0e14\u0e2a\u0e2d\u0e1a", None))
        self.parasite_amount_label.setText(QCoreApplication.translate("UI_parasite", u"\u0e08\u0e33\u0e19\u0e27\u0e19", None))
        self.parasite_number_amount_label.setText(QCoreApplication.translate("UI_parasite", u"\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23", None))
        self.parasite_cost_label.setText(QCoreApplication.translate("UI_parasite", u"\u0e04\u0e48\u0e32\u0e43\u0e0a\u0e49\u0e08\u0e48\u0e32\u0e22", None))
        self.parasite_cost_unit_label.setText(QCoreApplication.translate("UI_parasite", u"\u0e1a\u0e32\u0e17", None))
        self.parasite_save_data_pushButton.setText(QCoreApplication.translate("UI_parasite", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.parasite_cancel_pushButton.setText(QCoreApplication.translate("UI_parasite", u"\u0e22\u0e01\u0e40\u0e25\u0e34\u0e01", None))
    # retranslateUi

