# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'F4_Service_after_death.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDateEdit, QDateTimeEdit,
    QFrame, QLabel, QLineEdit, QMainWindow,
    QPushButton, QRadioButton, QSizePolicy, QTextEdit,
    QTimeEdit, QWidget)

class Ui_Service_after_death(object):
    def setupUi(self, Service_after_death):
        if not Service_after_death.objectName():
            Service_after_death.setObjectName(u"Service_after_death")
        Service_after_death.resize(1560, 770)
        Service_after_death.setMinimumSize(QSize(1560, 770))
        Service_after_death.setMaximumSize(QSize(1560, 770))
        Service_after_death.setStyleSheet(u"background:rgb(135, 255, 191)")
        self.Service_after_death_window = QWidget(Service_after_death)
        self.Service_after_death_window.setObjectName(u"Service_after_death_window")
        self.Main_header_label = QLabel(self.Service_after_death_window)
        self.Main_header_label.setObjectName(u"Main_header_label")
        self.Main_header_label.setGeometry(QRect(10, 5, 1031, 51))
        font = QFont()
        font.setFamilies([u"TH Niramit AS"])
        font.setPointSize(30)
        font.setBold(True)
        self.Main_header_label.setFont(font)
        self.Main_header_label.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.Main_header_label.setFrameShape(QFrame.Shape.Box)
        self.Main_header_label.setLineWidth(3)
        self.Main_header_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.select_frame = QFrame(self.Service_after_death_window)
        self.select_frame.setObjectName(u"select_frame")
        self.select_frame.setGeometry(QRect(10, 60, 1031, 71))
        self.select_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.select_frame.setFrameShape(QFrame.Shape.Box)
        self.select_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.select_frame.setLineWidth(3)
        self.select_carcass = QRadioButton(self.select_frame)
        self.select_carcass.setObjectName(u"select_carcass")
        self.select_carcass.setGeometry(QRect(461, 10, 161, 51))
        font1 = QFont()
        font1.setFamilies([u"TH Niramit AS"])
        font1.setPointSize(28)
        font1.setBold(True)
        self.select_carcass.setFont(font1)
        self.select_daimond = QRadioButton(self.select_frame)
        self.select_daimond.setObjectName(u"select_daimond")
        self.select_daimond.setGeometry(QRect(800, 10, 161, 51))
        self.select_daimond.setFont(font1)
        self.select_line1 = QFrame(self.select_frame)
        self.select_line1.setObjectName(u"select_line1")
        self.select_line1.setGeometry(QRect(343, 0, 3, 67))
        self.select_line1.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.select_line1.setFrameShape(QFrame.Shape.VLine)
        self.select_line1.setFrameShadow(QFrame.Shadow.Sunken)
        self.select_infectioun = QRadioButton(self.select_frame)
        self.select_infectioun.setObjectName(u"select_infectioun")
        self.select_infectioun.setGeometry(QRect(81, 10, 181, 51))
        self.select_infectioun.setFont(font1)
        self.select_line2 = QFrame(self.select_frame)
        self.select_line2.setObjectName(u"select_line2")
        self.select_line2.setGeometry(QRect(686, 0, 3, 67))
        self.select_line2.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.select_line2.setFrameShape(QFrame.Shape.VLine)
        self.select_line2.setFrameShadow(QFrame.Shadow.Sunken)
        self.infectioun_frame = QFrame(self.Service_after_death_window)
        self.infectioun_frame.setObjectName(u"infectioun_frame")
        self.infectioun_frame.setGeometry(QRect(10, 170, 1031, 211))
        self.infectioun_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.infectioun_frame.setFrameShape(QFrame.Shape.Box)
        self.infectioun_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.infectioun_frame.setLineWidth(3)
        self.infectioun_tissues_checkBox = QCheckBox(self.infectioun_frame)
        self.infectioun_tissues_checkBox.setObjectName(u"infectioun_tissues_checkBox")
        self.infectioun_tissues_checkBox.setGeometry(QRect(10, 50, 251, 31))
        font2 = QFont()
        font2.setFamilies([u"TH Niramit AS"])
        font2.setPointSize(16)
        font2.setBold(True)
        self.infectioun_tissues_checkBox.setFont(font2)
        self.infectioun_neddle_checkBox = QCheckBox(self.infectioun_frame)
        self.infectioun_neddle_checkBox.setObjectName(u"infectioun_neddle_checkBox")
        self.infectioun_neddle_checkBox.setGeometry(QRect(10, 80, 231, 31))
        self.infectioun_neddle_checkBox.setFont(font2)
        self.infectioun_syringe_checkBox = QCheckBox(self.infectioun_frame)
        self.infectioun_syringe_checkBox.setObjectName(u"infectioun_syringe_checkBox")
        self.infectioun_syringe_checkBox.setGeometry(QRect(10, 110, 251, 31))
        self.infectioun_syringe_checkBox.setFont(font2)
        self.infectioun_other1_checkBox = QCheckBox(self.infectioun_frame)
        self.infectioun_other1_checkBox.setObjectName(u"infectioun_other1_checkBox")
        self.infectioun_other1_checkBox.setGeometry(QRect(10, 140, 21, 31))
        font3 = QFont()
        font3.setFamilies([u"TH Niramit AS"])
        font3.setPointSize(14)
        font3.setBold(True)
        self.infectioun_other1_checkBox.setFont(font3)
        self.infectioun_other2_checkBox = QCheckBox(self.infectioun_frame)
        self.infectioun_other2_checkBox.setObjectName(u"infectioun_other2_checkBox")
        self.infectioun_other2_checkBox.setGeometry(QRect(10, 170, 21, 31))
        self.infectioun_other2_checkBox.setFont(font3)
        self.infectioun_other1_lineEdit = QLineEdit(self.infectioun_frame)
        self.infectioun_other1_lineEdit.setObjectName(u"infectioun_other1_lineEdit")
        self.infectioun_other1_lineEdit.setGeometry(QRect(30, 140, 221, 31))
        self.infectioun_other1_lineEdit.setFont(font2)
        self.infectioun_other2_lineEdit = QLineEdit(self.infectioun_frame)
        self.infectioun_other2_lineEdit.setObjectName(u"infectioun_other2_lineEdit")
        self.infectioun_other2_lineEdit.setGeometry(QRect(30, 170, 221, 31))
        self.infectioun_other2_lineEdit.setFont(font2)
        self.infectioun_line1 = QFrame(self.infectioun_frame)
        self.infectioun_line1.setObjectName(u"infectioun_line1")
        self.infectioun_line1.setGeometry(QRect(2, 40, 1026, 3))
        self.infectioun_line1.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.infectioun_line1.setFrameShape(QFrame.Shape.HLine)
        self.infectioun_line1.setFrameShadow(QFrame.Shadow.Sunken)
        self.infectioun_type_label = QLabel(self.infectioun_frame)
        self.infectioun_type_label.setObjectName(u"infectioun_type_label")
        self.infectioun_type_label.setGeometry(QRect(90, 5, 171, 41))
        font4 = QFont()
        font4.setFamilies([u"TH Niramit AS"])
        font4.setPointSize(20)
        font4.setBold(True)
        self.infectioun_type_label.setFont(font4)
        self.infectioun_line2 = QFrame(self.infectioun_frame)
        self.infectioun_line2.setObjectName(u"infectioun_line2")
        self.infectioun_line2.setGeometry(QRect(343, 0, 3, 210))
        self.infectioun_line2.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.infectioun_line2.setFrameShape(QFrame.Shape.VLine)
        self.infectioun_line2.setFrameShadow(QFrame.Shadow.Sunken)
        self.infectioun_line3 = QFrame(self.infectioun_frame)
        self.infectioun_line3.setObjectName(u"infectioun_line3")
        self.infectioun_line3.setGeometry(QRect(470, 0, 3, 210))
        self.infectioun_line3.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.infectioun_line3.setFrameShape(QFrame.Shape.VLine)
        self.infectioun_line3.setFrameShadow(QFrame.Shadow.Sunken)
        self.infectioun_number_of_pack_label = QLabel(self.infectioun_frame)
        self.infectioun_number_of_pack_label.setObjectName(u"infectioun_number_of_pack_label")
        self.infectioun_number_of_pack_label.setGeometry(QRect(370, 5, 81, 41))
        self.infectioun_number_of_pack_label.setFont(font4)
        self.infectioun_weight_label = QLabel(self.infectioun_frame)
        self.infectioun_weight_label.setObjectName(u"infectioun_weight_label")
        self.infectioun_weight_label.setGeometry(QRect(483, 5, 101, 41))
        self.infectioun_weight_label.setFont(font4)
        self.number_pack_tissues_lineEdit = QLineEdit(self.infectioun_frame)
        self.number_pack_tissues_lineEdit.setObjectName(u"number_pack_tissues_lineEdit")
        self.number_pack_tissues_lineEdit.setGeometry(QRect(370, 50, 81, 31))
        self.number_pack_tissues_lineEdit.setFont(font2)
        self.number_pack_tissues_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.number_pack_needle_lineEdit = QLineEdit(self.infectioun_frame)
        self.number_pack_needle_lineEdit.setObjectName(u"number_pack_needle_lineEdit")
        self.number_pack_needle_lineEdit.setGeometry(QRect(370, 80, 81, 31))
        self.number_pack_needle_lineEdit.setFont(font2)
        self.number_pack_needle_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.number_pack_syringe_lineEdit = QLineEdit(self.infectioun_frame)
        self.number_pack_syringe_lineEdit.setObjectName(u"number_pack_syringe_lineEdit")
        self.number_pack_syringe_lineEdit.setGeometry(QRect(370, 110, 81, 31))
        self.number_pack_syringe_lineEdit.setFont(font2)
        self.number_pack_syringe_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.number_pack_other1_lineEdit = QLineEdit(self.infectioun_frame)
        self.number_pack_other1_lineEdit.setObjectName(u"number_pack_other1_lineEdit")
        self.number_pack_other1_lineEdit.setGeometry(QRect(370, 140, 81, 31))
        self.number_pack_other1_lineEdit.setFont(font2)
        self.number_pack_other1_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.number_pack_other2_lineEdit = QLineEdit(self.infectioun_frame)
        self.number_pack_other2_lineEdit.setObjectName(u"number_pack_other2_lineEdit")
        self.number_pack_other2_lineEdit.setGeometry(QRect(370, 170, 81, 31))
        self.number_pack_other2_lineEdit.setFont(font2)
        self.number_pack_other2_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infectioun_line4 = QFrame(self.infectioun_frame)
        self.infectioun_line4.setObjectName(u"infectioun_line4")
        self.infectioun_line4.setGeometry(QRect(585, 0, 3, 210))
        self.infectioun_line4.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.infectioun_line4.setFrameShape(QFrame.Shape.VLine)
        self.infectioun_line4.setFrameShadow(QFrame.Shadow.Sunken)
        self.weight_tissues_lineEdit = QLineEdit(self.infectioun_frame)
        self.weight_tissues_lineEdit.setObjectName(u"weight_tissues_lineEdit")
        self.weight_tissues_lineEdit.setGeometry(QRect(490, 50, 81, 31))
        self.weight_tissues_lineEdit.setFont(font2)
        self.weight_tissues_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.weight_needle_lineEdit = QLineEdit(self.infectioun_frame)
        self.weight_needle_lineEdit.setObjectName(u"weight_needle_lineEdit")
        self.weight_needle_lineEdit.setGeometry(QRect(490, 80, 81, 31))
        self.weight_needle_lineEdit.setFont(font2)
        self.weight_needle_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.weight_syringe_lineEdit = QLineEdit(self.infectioun_frame)
        self.weight_syringe_lineEdit.setObjectName(u"weight_syringe_lineEdit")
        self.weight_syringe_lineEdit.setGeometry(QRect(490, 110, 81, 31))
        self.weight_syringe_lineEdit.setFont(font2)
        self.weight_syringe_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.weight_other1_lineEdit = QLineEdit(self.infectioun_frame)
        self.weight_other1_lineEdit.setObjectName(u"weight_other1_lineEdit")
        self.weight_other1_lineEdit.setGeometry(QRect(490, 140, 81, 31))
        self.weight_other1_lineEdit.setFont(font2)
        self.weight_other1_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.weight_other2_lineEdit = QLineEdit(self.infectioun_frame)
        self.weight_other2_lineEdit.setObjectName(u"weight_other2_lineEdit")
        self.weight_other2_lineEdit.setGeometry(QRect(490, 170, 81, 31))
        self.weight_other2_lineEdit.setFont(font2)
        self.weight_other2_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infectioun_remark_label = QLabel(self.infectioun_frame)
        self.infectioun_remark_label.setObjectName(u"infectioun_remark_label")
        self.infectioun_remark_label.setGeometry(QRect(760, 5, 81, 41))
        self.infectioun_remark_label.setFont(font4)
        self.infectioun_remark_textEdit = QTextEdit(self.infectioun_frame)
        self.infectioun_remark_textEdit.setObjectName(u"infectioun_remark_textEdit")
        self.infectioun_remark_textEdit.setGeometry(QRect(592, 45, 431, 161))
        self.infectioun_remark_textEdit.setFont(font4)
        self.infectioun_remark_textEdit.setFrameShape(QFrame.Shape.Box)
        self.infectioun_remark_textEdit.setFrameShadow(QFrame.Shadow.Plain)
        self.infectioun_remark_label.raise_()
        self.infectioun_weight_label.raise_()
        self.infectioun_number_of_pack_label.raise_()
        self.infectioun_type_label.raise_()
        self.infectioun_tissues_checkBox.raise_()
        self.infectioun_neddle_checkBox.raise_()
        self.infectioun_syringe_checkBox.raise_()
        self.infectioun_other1_checkBox.raise_()
        self.infectioun_other2_checkBox.raise_()
        self.infectioun_other1_lineEdit.raise_()
        self.infectioun_other2_lineEdit.raise_()
        self.infectioun_line1.raise_()
        self.infectioun_line2.raise_()
        self.infectioun_line3.raise_()
        self.number_pack_tissues_lineEdit.raise_()
        self.number_pack_needle_lineEdit.raise_()
        self.number_pack_syringe_lineEdit.raise_()
        self.number_pack_other1_lineEdit.raise_()
        self.number_pack_other2_lineEdit.raise_()
        self.infectioun_line4.raise_()
        self.weight_tissues_lineEdit.raise_()
        self.weight_needle_lineEdit.raise_()
        self.weight_syringe_lineEdit.raise_()
        self.weight_other1_lineEdit.raise_()
        self.weight_other2_lineEdit.raise_()
        self.infectioun_remark_textEdit.raise_()
        self.infectioun_label = QLabel(self.Service_after_death_window)
        self.infectioun_label.setObjectName(u"infectioun_label")
        self.infectioun_label.setGeometry(QRect(20, 130, 101, 41))
        self.infectioun_label.setFont(font4)
        self.daimond_label = QLabel(self.Service_after_death_window)
        self.daimond_label.setObjectName(u"daimond_label")
        self.daimond_label.setGeometry(QRect(20, 380, 61, 41))
        self.daimond_label.setFont(font4)
        self.daimond_frame = QFrame(self.Service_after_death_window)
        self.daimond_frame.setObjectName(u"daimond_frame")
        self.daimond_frame.setGeometry(QRect(10, 415, 1031, 351))
        self.daimond_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.daimond_frame.setFrameShape(QFrame.Shape.Box)
        self.daimond_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.daimond_frame.setLineWidth(3)
        self.daimond_line1 = QFrame(self.daimond_frame)
        self.daimond_line1.setObjectName(u"daimond_line1")
        self.daimond_line1.setGeometry(QRect(2, 40, 1026, 3))
        self.daimond_line1.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line1.setFrameShape(QFrame.Shape.HLine)
        self.daimond_line1.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_type_label = QLabel(self.daimond_frame)
        self.daimond_type_label.setObjectName(u"daimond_type_label")
        self.daimond_type_label.setGeometry(QRect(65, 5, 141, 41))
        self.daimond_type_label.setFont(font4)
        self.daimond_carcass_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_carcass_checkBox.setObjectName(u"daimond_carcass_checkBox")
        self.daimond_carcass_checkBox.setGeometry(QRect(10, 50, 161, 31))
        self.daimond_carcass_checkBox.setFont(font2)
        self.daimond_bone_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_bone_checkBox.setObjectName(u"daimond_bone_checkBox")
        self.daimond_bone_checkBox.setGeometry(QRect(10, 80, 161, 31))
        self.daimond_bone_checkBox.setFont(font2)
        self.daimond_hair_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_hair_checkBox.setObjectName(u"daimond_hair_checkBox")
        self.daimond_hair_checkBox.setGeometry(QRect(10, 110, 161, 31))
        self.daimond_hair_checkBox.setFont(font2)
        self.daimond_other1_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_other1_checkBox.setObjectName(u"daimond_other1_checkBox")
        self.daimond_other1_checkBox.setGeometry(QRect(10, 140, 21, 31))
        self.daimond_other1_checkBox.setFont(font3)
        self.daimond_other1_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_other1_lineEdit.setObjectName(u"daimond_other1_lineEdit")
        self.daimond_other1_lineEdit.setGeometry(QRect(30, 140, 221, 31))
        self.daimond_other1_lineEdit.setFont(font2)
        self.daimond_other2_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_other2_checkBox.setObjectName(u"daimond_other2_checkBox")
        self.daimond_other2_checkBox.setGeometry(QRect(10, 170, 21, 31))
        self.daimond_other2_checkBox.setFont(font3)
        self.daimond_other2_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_other2_lineEdit.setObjectName(u"daimond_other2_lineEdit")
        self.daimond_other2_lineEdit.setGeometry(QRect(30, 170, 221, 31))
        self.daimond_other2_lineEdit.setFont(font2)
        self.daimond_line3 = QFrame(self.daimond_frame)
        self.daimond_line3.setObjectName(u"daimond_line3")
        self.daimond_line3.setGeometry(QRect(260, 3, 3, 210))
        self.daimond_line3.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line3.setFrameShape(QFrame.Shape.VLine)
        self.daimond_line3.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_line4 = QFrame(self.daimond_frame)
        self.daimond_line4.setObjectName(u"daimond_line4")
        self.daimond_line4.setGeometry(QRect(360, 0, 3, 210))
        self.daimond_line4.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line4.setFrameShape(QFrame.Shape.VLine)
        self.daimond_line4.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_line5 = QFrame(self.daimond_frame)
        self.daimond_line5.setObjectName(u"daimond_line5")
        self.daimond_line5.setGeometry(QRect(470, 0, 3, 210))
        self.daimond_line5.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line5.setFrameShape(QFrame.Shape.VLine)
        self.daimond_line5.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_number_label = QLabel(self.daimond_frame)
        self.daimond_number_label.setObjectName(u"daimond_number_label")
        self.daimond_number_label.setGeometry(QRect(285, 5, 61, 41))
        self.daimond_number_label.setFont(font4)
        self.daimond_weight_label = QLabel(self.daimond_frame)
        self.daimond_weight_label.setObjectName(u"daimond_weight_label")
        self.daimond_weight_label.setGeometry(QRect(366, 5, 101, 41))
        self.daimond_weight_label.setFont(font4)
        self.daimond_number_carcass_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_number_carcass_lineEdit.setObjectName(u"daimond_number_carcass_lineEdit")
        self.daimond_number_carcass_lineEdit.setGeometry(QRect(270, 50, 81, 31))
        self.daimond_number_carcass_lineEdit.setFont(font2)
        self.daimond_number_carcass_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_number_bone_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_number_bone_lineEdit.setObjectName(u"daimond_number_bone_lineEdit")
        self.daimond_number_bone_lineEdit.setGeometry(QRect(270, 80, 81, 31))
        self.daimond_number_bone_lineEdit.setFont(font2)
        self.daimond_number_bone_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_number_hair_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_number_hair_lineEdit.setObjectName(u"daimond_number_hair_lineEdit")
        self.daimond_number_hair_lineEdit.setGeometry(QRect(270, 110, 81, 31))
        self.daimond_number_hair_lineEdit.setFont(font2)
        self.daimond_number_hair_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_number_other1_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_number_other1_lineEdit.setObjectName(u"daimond_number_other1_lineEdit")
        self.daimond_number_other1_lineEdit.setGeometry(QRect(270, 140, 81, 31))
        self.daimond_number_other1_lineEdit.setFont(font2)
        self.daimond_number_other1_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_number_other2_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_number_other2_lineEdit.setObjectName(u"daimond_number_other2_lineEdit")
        self.daimond_number_other2_lineEdit.setGeometry(QRect(270, 170, 81, 31))
        self.daimond_number_other2_lineEdit.setFont(font2)
        self.daimond_number_other2_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_weight_carcass_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_weight_carcass_lineEdit.setObjectName(u"daimond_weight_carcass_lineEdit")
        self.daimond_weight_carcass_lineEdit.setGeometry(QRect(375, 50, 81, 31))
        self.daimond_weight_carcass_lineEdit.setFont(font2)
        self.daimond_weight_carcass_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_weight_bone_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_weight_bone_lineEdit.setObjectName(u"daimond_weight_bone_lineEdit")
        self.daimond_weight_bone_lineEdit.setGeometry(QRect(375, 80, 81, 31))
        self.daimond_weight_bone_lineEdit.setFont(font2)
        self.daimond_weight_bone_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_weight_hair_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_weight_hair_lineEdit.setObjectName(u"daimond_weight_hair_lineEdit")
        self.daimond_weight_hair_lineEdit.setGeometry(QRect(375, 110, 81, 31))
        self.daimond_weight_hair_lineEdit.setFont(font2)
        self.daimond_weight_hair_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_weight_other1_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_weight_other1_lineEdit.setObjectName(u"daimond_weight_other1_lineEdit")
        self.daimond_weight_other1_lineEdit.setGeometry(QRect(375, 140, 81, 31))
        self.daimond_weight_other1_lineEdit.setFont(font2)
        self.daimond_weight_other1_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_weight_other2_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_weight_other2_lineEdit.setObjectName(u"daimond_weight_other2_lineEdit")
        self.daimond_weight_other2_lineEdit.setGeometry(QRect(375, 170, 81, 31))
        self.daimond_weight_other2_lineEdit.setFont(font2)
        self.daimond_weight_other2_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_line2 = QFrame(self.daimond_frame)
        self.daimond_line2.setObjectName(u"daimond_line2")
        self.daimond_line2.setGeometry(QRect(3, 210, 470, 3))
        self.daimond_line2.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line2.setFrameShape(QFrame.Shape.HLine)
        self.daimond_line2.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_option_selection_label = QLabel(self.daimond_frame)
        self.daimond_option_selection_label.setObjectName(u"daimond_option_selection_label")
        self.daimond_option_selection_label.setGeometry(QRect(480, 5, 541, 41))
        self.daimond_option_selection_label.setFont(font4)
        self.daimond_option_selection_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_size_label = QLabel(self.daimond_frame)
        self.daimond_size_label.setObjectName(u"daimond_size_label")
        self.daimond_size_label.setGeometry(QRect(480, 40, 51, 31))
        self.daimond_size_label.setFont(font4)
        self.daimond_min_1carat_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_min_1carat_checkBox.setObjectName(u"daimond_min_1carat_checkBox")
        self.daimond_min_1carat_checkBox.setGeometry(QRect(480, 80, 161, 21))
        self.daimond_min_1carat_checkBox.setFont(font3)
        self.daimond_1carat_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_1carat_checkBox.setObjectName(u"daimond_1carat_checkBox")
        self.daimond_1carat_checkBox.setGeometry(QRect(660, 80, 161, 21))
        self.daimond_1carat_checkBox.setFont(font3)
        self.daimond_2carat_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_2carat_checkBox.setObjectName(u"daimond_2carat_checkBox")
        self.daimond_2carat_checkBox.setGeometry(QRect(850, 80, 161, 21))
        self.daimond_2carat_checkBox.setFont(font3)
        self.daimond_3carat_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_3carat_checkBox.setObjectName(u"daimond_3carat_checkBox")
        self.daimond_3carat_checkBox.setGeometry(QRect(480, 110, 181, 21))
        self.daimond_3carat_checkBox.setFont(font3)
        self.daimond_4carat_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_4carat_checkBox.setObjectName(u"daimond_4carat_checkBox")
        self.daimond_4carat_checkBox.setGeometry(QRect(660, 110, 171, 21))
        self.daimond_4carat_checkBox.setFont(font3)
        self.daimond_5carat_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_5carat_checkBox.setObjectName(u"daimond_5carat_checkBox")
        self.daimond_5carat_checkBox.setGeometry(QRect(850, 110, 171, 21))
        self.daimond_5carat_checkBox.setFont(font3)
        self.daimond_line6 = QFrame(self.daimond_frame)
        self.daimond_line6.setObjectName(u"daimond_line6")
        self.daimond_line6.setGeometry(QRect(470, 70, 70, 3))
        self.daimond_line6.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line6.setFrameShape(QFrame.Shape.HLine)
        self.daimond_line6.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_line7 = QFrame(self.daimond_frame)
        self.daimond_line7.setObjectName(u"daimond_line7")
        self.daimond_line7.setGeometry(QRect(540, 40, 3, 33))
        self.daimond_line7.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line7.setFrameShape(QFrame.Shape.VLine)
        self.daimond_line7.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_line11 = QFrame(self.daimond_frame)
        self.daimond_line11.setObjectName(u"daimond_line11")
        self.daimond_line11.setGeometry(QRect(470, 140, 558, 3))
        self.daimond_line11.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line11.setFrameShape(QFrame.Shape.HLine)
        self.daimond_line11.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_cutting_label = QLabel(self.daimond_frame)
        self.daimond_cutting_label.setObjectName(u"daimond_cutting_label")
        self.daimond_cutting_label.setGeometry(QRect(480, 140, 61, 31))
        self.daimond_cutting_label.setFont(font4)
        self.daimond_line9 = QFrame(self.daimond_frame)
        self.daimond_line9.setObjectName(u"daimond_line9")
        self.daimond_line9.setGeometry(QRect(470, 170, 70, 3))
        self.daimond_line9.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line9.setFrameShape(QFrame.Shape.HLine)
        self.daimond_line9.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_line8 = QFrame(self.daimond_frame)
        self.daimond_line8.setObjectName(u"daimond_line8")
        self.daimond_line8.setGeometry(QRect(540, 140, 3, 33))
        self.daimond_line8.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line8.setFrameShape(QFrame.Shape.VLine)
        self.daimond_line8.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_round_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_round_checkBox.setObjectName(u"daimond_round_checkBox")
        self.daimond_round_checkBox.setGeometry(QRect(560, 150, 101, 21))
        self.daimond_round_checkBox.setFont(font3)
        self.daimond_oval_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_oval_checkBox.setObjectName(u"daimond_oval_checkBox")
        self.daimond_oval_checkBox.setGeometry(QRect(670, 150, 71, 21))
        self.daimond_oval_checkBox.setFont(font3)
        self.daimond_princess_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_princess_checkBox.setObjectName(u"daimond_princess_checkBox")
        self.daimond_princess_checkBox.setGeometry(QRect(750, 150, 141, 21))
        self.daimond_princess_checkBox.setFont(font3)
        self.daimond_radiant_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_radiant_checkBox.setObjectName(u"daimond_radiant_checkBox")
        self.daimond_radiant_checkBox.setGeometry(QRect(480, 180, 161, 21))
        self.daimond_radiant_checkBox.setFont(font3)
        self.daimond_cushion_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_cushion_checkBox.setObjectName(u"daimond_cushion_checkBox")
        self.daimond_cushion_checkBox.setGeometry(QRect(890, 150, 137, 21))
        self.daimond_cushion_checkBox.setFont(font3)
        self.daimond_marquise_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_marquise_checkBox.setObjectName(u"daimond_marquise_checkBox")
        self.daimond_marquise_checkBox.setGeometry(QRect(650, 180, 161, 21))
        self.daimond_marquise_checkBox.setFont(font3)
        self.daimond_cutting_other_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_cutting_other_checkBox.setObjectName(u"daimond_cutting_other_checkBox")
        self.daimond_cutting_other_checkBox.setGeometry(QRect(810, 180, 51, 21))
        self.daimond_cutting_other_checkBox.setFont(font3)
        self.daimond_cutting_other_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_cutting_other_lineEdit.setObjectName(u"daimond_cutting_other_lineEdit")
        self.daimond_cutting_other_lineEdit.setGeometry(QRect(860, 175, 161, 31))
        self.daimond_cutting_other_lineEdit.setFont(font3)
        self.daimond_cutting_other_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_line10 = QFrame(self.daimond_frame)
        self.daimond_line10.setObjectName(u"daimond_line10")
        self.daimond_line10.setGeometry(QRect(470, 210, 558, 3))
        self.daimond_line10.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line10.setFrameShape(QFrame.Shape.HLine)
        self.daimond_line10.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_line16 = QFrame(self.daimond_frame)
        self.daimond_line16.setObjectName(u"daimond_line16")
        self.daimond_line16.setGeometry(QRect(360, 210, 3, 36))
        self.daimond_line16.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line16.setFrameShape(QFrame.Shape.VLine)
        self.daimond_line16.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_line15 = QFrame(self.daimond_frame)
        self.daimond_line15.setObjectName(u"daimond_line15")
        self.daimond_line15.setGeometry(QRect(0, 243, 1028, 3))
        self.daimond_line15.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line15.setFrameShape(QFrame.Shape.HLine)
        self.daimond_line15.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_accessories_label = QLabel(self.daimond_frame)
        self.daimond_accessories_label.setObjectName(u"daimond_accessories_label")
        self.daimond_accessories_label.setGeometry(QRect(70, 215, 231, 31))
        self.daimond_accessories_label.setFont(font4)
        self.daimond_ring_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_ring_checkBox.setObjectName(u"daimond_ring_checkBox")
        self.daimond_ring_checkBox.setGeometry(QRect(10, 260, 231, 21))
        self.daimond_ring_checkBox.setFont(font3)
        self.daimond_necklace_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_necklace_checkBox.setObjectName(u"daimond_necklace_checkBox")
        self.daimond_necklace_checkBox.setGeometry(QRect(10, 290, 231, 21))
        self.daimond_necklace_checkBox.setFont(font3)
        self.daimond_earing_checkBox = QCheckBox(self.daimond_frame)
        self.daimond_earing_checkBox.setObjectName(u"daimond_earing_checkBox")
        self.daimond_earing_checkBox.setGeometry(QRect(10, 320, 231, 21))
        self.daimond_earing_checkBox.setFont(font3)
        self.daimond_code_ring_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_code_ring_lineEdit.setObjectName(u"daimond_code_ring_lineEdit")
        self.daimond_code_ring_lineEdit.setGeometry(QRect(250, 250, 101, 31))
        self.daimond_code_ring_lineEdit.setFont(font2)
        self.daimond_code_ring_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_code_necklace_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_code_necklace_lineEdit.setObjectName(u"daimond_code_necklace_lineEdit")
        self.daimond_code_necklace_lineEdit.setGeometry(QRect(250, 280, 101, 31))
        self.daimond_code_necklace_lineEdit.setFont(font2)
        self.daimond_code_necklace_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_code_earing_lineEdit = QLineEdit(self.daimond_frame)
        self.daimond_code_earing_lineEdit.setObjectName(u"daimond_code_earing_lineEdit")
        self.daimond_code_earing_lineEdit.setGeometry(QRect(250, 310, 101, 31))
        self.daimond_code_earing_lineEdit.setFont(font2)
        self.daimond_code_earing_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_line12 = QFrame(self.daimond_frame)
        self.daimond_line12.setObjectName(u"daimond_line12")
        self.daimond_line12.setGeometry(QRect(150, 245, 3, 105))
        self.daimond_line12.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line12.setFrameShape(QFrame.Shape.VLine)
        self.daimond_line12.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_line13 = QFrame(self.daimond_frame)
        self.daimond_line13.setObjectName(u"daimond_line13")
        self.daimond_line13.setGeometry(QRect(240, 245, 3, 105))
        self.daimond_line13.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line13.setFrameShape(QFrame.Shape.VLine)
        self.daimond_line13.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_line14 = QFrame(self.daimond_frame)
        self.daimond_line14.setObjectName(u"daimond_line14")
        self.daimond_line14.setGeometry(QRect(360, 245, 3, 105))
        self.daimond_line14.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line14.setFrameShape(QFrame.Shape.VLine)
        self.daimond_line14.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_color_label = QLabel(self.daimond_frame)
        self.daimond_color_label.setObjectName(u"daimond_color_label")
        self.daimond_color_label.setGeometry(QRect(380, 215, 81, 31))
        self.daimond_color_label.setFont(font4)
        self.daimond_price_label = QLabel(self.daimond_frame)
        self.daimond_price_label.setObjectName(u"daimond_price_label")
        self.daimond_price_label.setGeometry(QRect(490, 215, 101, 31))
        self.daimond_price_label.setFont(font4)
        self.daimond_line19 = QFrame(self.daimond_frame)
        self.daimond_line19.setObjectName(u"daimond_line19")
        self.daimond_line19.setGeometry(QRect(470, 210, 3, 140))
        self.daimond_line19.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line19.setFrameShape(QFrame.Shape.VLine)
        self.daimond_line19.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_line18 = QFrame(self.daimond_frame)
        self.daimond_line18.setObjectName(u"daimond_line18")
        self.daimond_line18.setGeometry(QRect(600, 210, 3, 140))
        self.daimond_line18.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.daimond_line18.setFrameShape(QFrame.Shape.VLine)
        self.daimond_line18.setFrameShadow(QFrame.Shadow.Sunken)
        self.daimond_color_textEdit = QTextEdit(self.daimond_frame)
        self.daimond_color_textEdit.setObjectName(u"daimond_color_textEdit")
        self.daimond_color_textEdit.setGeometry(QRect(363, 246, 107, 103))
        self.daimond_color_textEdit.setFont(font2)
        self.daimond_color_textEdit.setFrameShape(QFrame.Shape.Box)
        self.daimond_color_textEdit.setFrameShadow(QFrame.Shadow.Plain)
        self.daimond_color_textEdit.setLineWidth(3)
        self.daimond_price_textEdit = QTextEdit(self.daimond_frame)
        self.daimond_price_textEdit.setObjectName(u"daimond_price_textEdit")
        self.daimond_price_textEdit.setGeometry(QRect(473, 246, 127, 103))
        self.daimond_price_textEdit.setFont(font4)
        self.daimond_price_textEdit.setFrameShape(QFrame.Shape.Box)
        self.daimond_price_textEdit.setFrameShadow(QFrame.Shadow.Plain)
        self.daimond_price_textEdit.setLineWidth(3)
        self.daimond_remark_label = QLabel(self.daimond_frame)
        self.daimond_remark_label.setObjectName(u"daimond_remark_label")
        self.daimond_remark_label.setGeometry(QRect(610, 215, 411, 31))
        self.daimond_remark_label.setFont(font4)
        self.daimond_remark_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.daimond_remark_textEdit = QTextEdit(self.daimond_frame)
        self.daimond_remark_textEdit.setObjectName(u"daimond_remark_textEdit")
        self.daimond_remark_textEdit.setGeometry(QRect(603, 246, 426, 103))
        self.daimond_remark_textEdit.setFont(font4)
        self.daimond_remark_textEdit.setFrameShape(QFrame.Shape.Box)
        self.daimond_remark_textEdit.setFrameShadow(QFrame.Shadow.Plain)
        self.daimond_remark_textEdit.setLineWidth(3)
        self.daimond_remark_label.raise_()
        self.daimond_price_label.raise_()
        self.daimond_color_label.raise_()
        self.daimond_accessories_label.raise_()
        self.daimond_line15.raise_()
        self.daimond_line16.raise_()
        self.daimond_cutting_label.raise_()
        self.daimond_size_label.raise_()
        self.daimond_option_selection_label.raise_()
        self.daimond_weight_label.raise_()
        self.daimond_number_label.raise_()
        self.daimond_type_label.raise_()
        self.daimond_line1.raise_()
        self.daimond_carcass_checkBox.raise_()
        self.daimond_bone_checkBox.raise_()
        self.daimond_hair_checkBox.raise_()
        self.daimond_other1_checkBox.raise_()
        self.daimond_other1_lineEdit.raise_()
        self.daimond_other2_checkBox.raise_()
        self.daimond_other2_lineEdit.raise_()
        self.daimond_line3.raise_()
        self.daimond_line4.raise_()
        self.daimond_line5.raise_()
        self.daimond_number_carcass_lineEdit.raise_()
        self.daimond_number_bone_lineEdit.raise_()
        self.daimond_number_hair_lineEdit.raise_()
        self.daimond_number_other1_lineEdit.raise_()
        self.daimond_number_other2_lineEdit.raise_()
        self.daimond_weight_carcass_lineEdit.raise_()
        self.daimond_weight_bone_lineEdit.raise_()
        self.daimond_weight_hair_lineEdit.raise_()
        self.daimond_weight_other1_lineEdit.raise_()
        self.daimond_weight_other2_lineEdit.raise_()
        self.daimond_line2.raise_()
        self.daimond_min_1carat_checkBox.raise_()
        self.daimond_1carat_checkBox.raise_()
        self.daimond_2carat_checkBox.raise_()
        self.daimond_3carat_checkBox.raise_()
        self.daimond_4carat_checkBox.raise_()
        self.daimond_5carat_checkBox.raise_()
        self.daimond_line6.raise_()
        self.daimond_line7.raise_()
        self.daimond_line11.raise_()
        self.daimond_line9.raise_()
        self.daimond_line8.raise_()
        self.daimond_round_checkBox.raise_()
        self.daimond_oval_checkBox.raise_()
        self.daimond_princess_checkBox.raise_()
        self.daimond_radiant_checkBox.raise_()
        self.daimond_cushion_checkBox.raise_()
        self.daimond_marquise_checkBox.raise_()
        self.daimond_cutting_other_checkBox.raise_()
        self.daimond_cutting_other_lineEdit.raise_()
        self.daimond_line10.raise_()
        self.daimond_ring_checkBox.raise_()
        self.daimond_necklace_checkBox.raise_()
        self.daimond_earing_checkBox.raise_()
        self.daimond_code_ring_lineEdit.raise_()
        self.daimond_code_necklace_lineEdit.raise_()
        self.daimond_code_earing_lineEdit.raise_()
        self.daimond_line12.raise_()
        self.daimond_line13.raise_()
        self.daimond_line14.raise_()
        self.daimond_line19.raise_()
        self.daimond_line18.raise_()
        self.daimond_color_textEdit.raise_()
        self.daimond_price_textEdit.raise_()
        self.daimond_remark_textEdit.raise_()
        self.laboratory_request_frame = QFrame(self.Service_after_death_window)
        self.laboratory_request_frame.setObjectName(u"laboratory_request_frame")
        self.laboratory_request_frame.setGeometry(QRect(1045, 5, 511, 541))
        self.laboratory_request_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.laboratory_request_frame.setFrameShape(QFrame.Shape.Box)
        self.laboratory_request_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.laboratory_request_frame.setLineWidth(3)
        self.laboratory_request_frame_label = QLabel(self.laboratory_request_frame)
        self.laboratory_request_frame_label.setObjectName(u"laboratory_request_frame_label")
        self.laboratory_request_frame_label.setGeometry(QRect(10, 10, 491, 21))
        self.laboratory_request_frame_label.setFont(font4)
        self.laboratory_request_frame_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.laboratory_line1 = QFrame(self.laboratory_request_frame)
        self.laboratory_line1.setObjectName(u"laboratory_line1")
        self.laboratory_line1.setGeometry(QRect(3, 35, 505, 3))
        self.laboratory_line1.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.laboratory_line1.setFrameShape(QFrame.Shape.HLine)
        self.laboratory_line1.setFrameShadow(QFrame.Shadow.Sunken)
        self.laboratory_request_incineration_checkBox = QCheckBox(self.laboratory_request_frame)
        self.laboratory_request_incineration_checkBox.setObjectName(u"laboratory_request_incineration_checkBox")
        self.laboratory_request_incineration_checkBox.setGeometry(QRect(10, 50, 491, 31))
        self.laboratory_request_incineration_checkBox.setFont(font2)
        self.weight_tissues_lineEdit_2 = QLineEdit(self.laboratory_request_frame)
        self.weight_tissues_lineEdit_2.setObjectName(u"weight_tissues_lineEdit_2")
        self.weight_tissues_lineEdit_2.setGeometry(QRect(280, 50, 81, 31))
        self.weight_tissues_lineEdit_2.setFont(font2)
        self.weight_tissues_lineEdit_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.laboratory_request_bone_checkBox = QCheckBox(self.laboratory_request_frame)
        self.laboratory_request_bone_checkBox.setObjectName(u"laboratory_request_bone_checkBox")
        self.laboratory_request_bone_checkBox.setGeometry(QRect(10, 90, 491, 31))
        self.laboratory_request_bone_checkBox.setFont(font2)
        self.laboratory_request_cremation_checkBox = QCheckBox(self.laboratory_request_frame)
        self.laboratory_request_cremation_checkBox.setObjectName(u"laboratory_request_cremation_checkBox")
        self.laboratory_request_cremation_checkBox.setGeometry(QRect(10, 130, 491, 31))
        self.laboratory_request_cremation_checkBox.setFont(font2)
        self.laboratory_date_and_time_label = QLabel(self.laboratory_request_frame)
        self.laboratory_date_and_time_label.setObjectName(u"laboratory_date_and_time_label")
        self.laboratory_date_and_time_label.setGeometry(QRect(30, 170, 321, 21))
        self.laboratory_date_and_time_label.setFont(font2)
        self.laboratory_date_and_time_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.laboratory_dateEdit = QDateEdit(self.laboratory_request_frame)
        self.laboratory_dateEdit.setObjectName(u"laboratory_dateEdit")
        self.laboratory_dateEdit.setGeometry(QRect(120, 165, 141, 31))
        self.laboratory_dateEdit.setFont(font2)
        self.laboratory_dateEdit.setDateTime(QDateTime(QDate(2020, 1, 1), QTime(0, 0, 0)))
        self.laboratory_dateEdit.setCalendarPopup(True)
        self.laboratory_timeEdit = QTimeEdit(self.laboratory_request_frame)
        self.laboratory_timeEdit.setObjectName(u"laboratory_timeEdit")
        self.laboratory_timeEdit.setGeometry(QRect(350, 165, 151, 31))
        self.laboratory_timeEdit.setFont(font2)
        self.laboratory_timeEdit.setCurrentSection(QDateTimeEdit.Section.HourSection)
        self.laboratory_timeEdit.setTimeSpec(Qt.TimeSpec.UTC)
        self.laboratory_request_daimond_checkBox = QCheckBox(self.laboratory_request_frame)
        self.laboratory_request_daimond_checkBox.setObjectName(u"laboratory_request_daimond_checkBox")
        self.laboratory_request_daimond_checkBox.setGeometry(QRect(10, 195, 491, 31))
        self.laboratory_request_daimond_checkBox.setFont(font2)
        self.laboratory_carcass_label = QLabel(self.laboratory_request_frame)
        self.laboratory_carcass_label.setObjectName(u"laboratory_carcass_label")
        self.laboratory_carcass_label.setGeometry(QRect(10, 237, 491, 21))
        self.laboratory_carcass_label.setFont(font4)
        self.laboratory_carcass_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.laboratory_line2 = QFrame(self.laboratory_request_frame)
        self.laboratory_line2.setObjectName(u"laboratory_line2")
        self.laboratory_line2.setGeometry(QRect(3, 230, 505, 3))
        self.laboratory_line2.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.laboratory_line2.setFrameShape(QFrame.Shape.HLine)
        self.laboratory_line2.setFrameShadow(QFrame.Shadow.Sunken)
        self.laboratory_line3 = QFrame(self.laboratory_request_frame)
        self.laboratory_line3.setObjectName(u"laboratory_line3")
        self.laboratory_line3.setGeometry(QRect(3, 260, 505, 3))
        self.laboratory_line3.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.laboratory_line3.setFrameShape(QFrame.Shape.HLine)
        self.laboratory_line3.setFrameShadow(QFrame.Shadow.Sunken)
        self.laboratory_carcass_fresh_checkBox = QCheckBox(self.laboratory_request_frame)
        self.laboratory_carcass_fresh_checkBox.setObjectName(u"laboratory_carcass_fresh_checkBox")
        self.laboratory_carcass_fresh_checkBox.setGeometry(QRect(10, 270, 131, 31))
        self.laboratory_carcass_fresh_checkBox.setFont(font2)
        self.laboratory_carcass_aytolysus_checkBox = QCheckBox(self.laboratory_request_frame)
        self.laboratory_carcass_aytolysus_checkBox.setObjectName(u"laboratory_carcass_aytolysus_checkBox")
        self.laboratory_carcass_aytolysus_checkBox.setGeometry(QRect(170, 270, 151, 31))
        self.laboratory_carcass_aytolysus_checkBox.setFont(font2)
        self.laboratory_carcass_unknow_checkBox = QCheckBox(self.laboratory_request_frame)
        self.laboratory_carcass_unknow_checkBox.setObjectName(u"laboratory_carcass_unknow_checkBox")
        self.laboratory_carcass_unknow_checkBox.setGeometry(QRect(350, 270, 151, 31))
        self.laboratory_carcass_unknow_checkBox.setFont(font2)
        self.laboratory_carcass_other_checkBox = QCheckBox(self.laboratory_request_frame)
        self.laboratory_carcass_other_checkBox.setObjectName(u"laboratory_carcass_other_checkBox")
        self.laboratory_carcass_other_checkBox.setGeometry(QRect(10, 310, 131, 31))
        self.laboratory_carcass_other_checkBox.setFont(font2)
        self.laboratory_carcass_other_lineEdit = QLineEdit(self.laboratory_request_frame)
        self.laboratory_carcass_other_lineEdit.setObjectName(u"laboratory_carcass_other_lineEdit")
        self.laboratory_carcass_other_lineEdit.setGeometry(QRect(70, 305, 421, 31))
        self.laboratory_carcass_other_lineEdit.setFont(font2)
        self.laboratory_carcass_other_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.laboratory_place_label = QLabel(self.laboratory_request_frame)
        self.laboratory_place_label.setObjectName(u"laboratory_place_label")
        self.laboratory_place_label.setGeometry(QRect(10, 357, 491, 21))
        self.laboratory_place_label.setFont(font4)
        self.laboratory_place_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.laboratory_line4 = QFrame(self.laboratory_request_frame)
        self.laboratory_line4.setObjectName(u"laboratory_line4")
        self.laboratory_line4.setGeometry(QRect(3, 350, 505, 3))
        self.laboratory_line4.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.laboratory_line4.setFrameShape(QFrame.Shape.HLine)
        self.laboratory_line4.setFrameShadow(QFrame.Shadow.Sunken)
        self.laboratory_line5 = QFrame(self.laboratory_request_frame)
        self.laboratory_line5.setObjectName(u"laboratory_line5")
        self.laboratory_line5.setGeometry(QRect(3, 380, 505, 3))
        self.laboratory_line5.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.laboratory_line5.setFrameShape(QFrame.Shape.HLine)
        self.laboratory_line5.setFrameShadow(QFrame.Shadow.Sunken)
        self.laboratory_place_necropy_checkBox = QCheckBox(self.laboratory_request_frame)
        self.laboratory_place_necropy_checkBox.setObjectName(u"laboratory_place_necropy_checkBox")
        self.laboratory_place_necropy_checkBox.setGeometry(QRect(10, 400, 311, 31))
        self.laboratory_place_necropy_checkBox.setFont(font2)
        self.laboratory_place_other1_checkBox = QCheckBox(self.laboratory_request_frame)
        self.laboratory_place_other1_checkBox.setObjectName(u"laboratory_place_other1_checkBox")
        self.laboratory_place_other1_checkBox.setGeometry(QRect(10, 440, 131, 31))
        self.laboratory_place_other1_checkBox.setFont(font2)
        self.laboratory_place_other1_lineEdit = QLineEdit(self.laboratory_request_frame)
        self.laboratory_place_other1_lineEdit.setObjectName(u"laboratory_place_other1_lineEdit")
        self.laboratory_place_other1_lineEdit.setGeometry(QRect(30, 440, 471, 31))
        self.laboratory_place_other1_lineEdit.setFont(font2)
        self.laboratory_place_other1_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.laboratory_place_other2_lineEdit = QLineEdit(self.laboratory_request_frame)
        self.laboratory_place_other2_lineEdit.setObjectName(u"laboratory_place_other2_lineEdit")
        self.laboratory_place_other2_lineEdit.setGeometry(QRect(30, 490, 471, 31))
        self.laboratory_place_other2_lineEdit.setFont(font2)
        self.laboratory_place_other2_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.laboratory_place_other2_checkBox = QCheckBox(self.laboratory_request_frame)
        self.laboratory_place_other2_checkBox.setObjectName(u"laboratory_place_other2_checkBox")
        self.laboratory_place_other2_checkBox.setGeometry(QRect(10, 490, 121, 31))
        self.laboratory_place_other2_checkBox.setFont(font2)
        self.laboratory_place_other2_checkBox.raise_()
        self.laboratory_place_other1_checkBox.raise_()
        self.laboratory_request_frame_label.raise_()
        self.laboratory_line1.raise_()
        self.laboratory_request_incineration_checkBox.raise_()
        self.weight_tissues_lineEdit_2.raise_()
        self.laboratory_request_bone_checkBox.raise_()
        self.laboratory_request_cremation_checkBox.raise_()
        self.laboratory_date_and_time_label.raise_()
        self.laboratory_dateEdit.raise_()
        self.laboratory_timeEdit.raise_()
        self.laboratory_request_daimond_checkBox.raise_()
        self.laboratory_carcass_label.raise_()
        self.laboratory_line2.raise_()
        self.laboratory_line3.raise_()
        self.laboratory_carcass_fresh_checkBox.raise_()
        self.laboratory_carcass_aytolysus_checkBox.raise_()
        self.laboratory_carcass_unknow_checkBox.raise_()
        self.laboratory_carcass_other_checkBox.raise_()
        self.laboratory_carcass_other_lineEdit.raise_()
        self.laboratory_place_label.raise_()
        self.laboratory_line4.raise_()
        self.laboratory_line5.raise_()
        self.laboratory_place_necropy_checkBox.raise_()
        self.laboratory_place_other1_lineEdit.raise_()
        self.laboratory_place_other2_lineEdit.raise_()
        self.service_after_death_save_button = QPushButton(self.Service_after_death_window)
        self.service_after_death_save_button.setObjectName(u"service_after_death_save_button")
        self.service_after_death_save_button.setGeometry(QRect(1390, 580, 161, 81))
        self.service_after_death_save_button.setFont(font)
        self.service_after_death_save_button.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.service_after_death_cancle_button = QPushButton(self.Service_after_death_window)
        self.service_after_death_cancle_button.setObjectName(u"service_after_death_cancle_button")
        self.service_after_death_cancle_button.setGeometry(QRect(1390, 680, 161, 81))
        self.service_after_death_cancle_button.setFont(font)
        self.service_after_death_cancle_button.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.note_frame = QFrame(self.Service_after_death_window)
        self.note_frame.setObjectName(u"note_frame")
        self.note_frame.setGeometry(QRect(1045, 550, 331, 215))
        self.note_frame.setStyleSheet(u"background:rgb(255, 255, 255)")
        self.note_frame.setFrameShape(QFrame.Shape.Box)
        self.note_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.note_frame.setLineWidth(3)
        self.note_label = QLabel(self.note_frame)
        self.note_label.setObjectName(u"note_label")
        self.note_label.setGeometry(QRect(10, 10, 311, 21))
        self.note_label.setFont(font4)
        self.note_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.note_line = QFrame(self.note_frame)
        self.note_line.setObjectName(u"note_line")
        self.note_line.setGeometry(QRect(0, 35, 330, 3))
        self.note_line.setStyleSheet(u"background:rgb(0, 0, 0)")
        self.note_line.setFrameShape(QFrame.Shape.HLine)
        self.note_line.setFrameShadow(QFrame.Shadow.Sunken)
        self.note_textEdit = QTextEdit(self.note_frame)
        self.note_textEdit.setObjectName(u"note_textEdit")
        self.note_textEdit.setGeometry(QRect(3, 37, 325, 174))
        font5 = QFont()
        font5.setFamilies([u"TH Niramit AS"])
        font5.setPointSize(18)
        font5.setBold(True)
        self.note_textEdit.setFont(font5)
        self.note_textEdit.setFrameShape(QFrame.Shape.Box)
        self.note_textEdit.setFrameShadow(QFrame.Shadow.Plain)
        self.note_textEdit.setLineWidth(3)
        Service_after_death.setCentralWidget(self.Service_after_death_window)
        self.daimond_label.raise_()
        self.infectioun_label.raise_()
        self.Main_header_label.raise_()
        self.select_frame.raise_()
        self.infectioun_frame.raise_()
        self.daimond_frame.raise_()
        self.laboratory_request_frame.raise_()
        self.service_after_death_save_button.raise_()
        self.service_after_death_cancle_button.raise_()
        self.note_frame.raise_()

        self.retranslateUi(Service_after_death)

        QMetaObject.connectSlotsByName(Service_after_death)
    # setupUi

    def retranslateUi(self, Service_after_death):
        Service_after_death.setWindowTitle(QCoreApplication.translate("Service_after_death", u"MainWindow", None))
        self.Main_header_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e07\u0e32\u0e19\u0e1a\u0e23\u0e34\u0e01\u0e32\u0e23\u0e2b\u0e25\u0e31\u0e07\u0e04\u0e27\u0e32\u0e21\u0e15\u0e32\u0e22", None))
        self.select_carcass.setText(QCoreApplication.translate("Service_after_death", u"\u0e40\u0e1c\u0e32\u0e0b\u0e32\u0e01", None))
        self.select_daimond.setText(QCoreApplication.translate("Service_after_death", u"\u0e2d\u0e31\u0e0d\u0e21\u0e13\u0e35", None))
        self.select_infectioun.setText(QCoreApplication.translate("Service_after_death", u"\u0e02\u0e22\u0e30\u0e15\u0e34\u0e14\u0e40\u0e0a\u0e37\u0e49\u0e2d", None))
        self.infectioun_tissues_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e40\u0e19\u0e37\u0e49\u0e2d\u0e40\u0e22\u0e37\u0e49\u0e2d\u0e15\u0e34\u0e14\u0e40\u0e0a\u0e37\u0e49\u0e2d(Infectioun Tissues)", None))
        self.infectioun_neddle_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e40\u0e02\u0e47\u0e21\u0e15\u0e34\u0e14\u0e40\u0e0a\u0e37\u0e49\u0e2d(Infectioun Needle)", None))
        self.infectioun_syringe_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e44\u0e0b\u0e23\u0e34\u0e07\u0e04\u0e4c\u0e15\u0e34\u0e14\u0e40\u0e0a\u0e37\u0e49\u0e2d(Infectioun Syringe)", None))
        self.infectioun_other1_checkBox.setText("")
        self.infectioun_other2_checkBox.setText("")
        self.infectioun_type_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e1b\u0e23\u0e30\u0e40\u0e20\u0e17\u0e02\u0e22\u0e30\u0e15\u0e34\u0e14\u0e40\u0e0a\u0e37\u0e49\u0e2d", None))
        self.infectioun_number_of_pack_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e08\u0e33\u0e19\u0e27\u0e19\u0e16\u0e38\u0e07", None))
        self.infectioun_weight_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01(KG)", None))
        self.infectioun_remark_label.setText(QCoreApplication.translate("Service_after_death", u"REMARK", None))
        self.infectioun_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e02\u0e22\u0e30\u0e15\u0e34\u0e14\u0e40\u0e0a\u0e37\u0e49\u0e2d", None))
        self.daimond_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e2d\u0e31\u0e0d\u0e21\u0e13\u0e35", None))
        self.daimond_type_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e1b\u0e23\u0e30\u0e40\u0e20\u0e17\u0e15\u0e31\u0e27\u0e2d\u0e22\u0e48\u0e32\u0e07", None))
        self.daimond_carcass_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e0b\u0e32\u0e01\u0e2a\u0e31\u0e15\u0e27\u0e4c(Carcass)", None))
        self.daimond_bone_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e01\u0e23\u0e30\u0e14\u0e39\u0e01\u0e2a\u0e31\u0e15\u0e27\u0e4c(Bone)", None))
        self.daimond_hair_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e02\u0e19\u0e2a\u0e31\u0e15\u0e27\u0e4c(Hair/feather)", None))
        self.daimond_other1_checkBox.setText("")
        self.daimond_other2_checkBox.setText("")
        self.daimond_number_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e08\u0e33\u0e19\u0e27\u0e19", None))
        self.daimond_weight_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e19\u0e49\u0e33\u0e2b\u0e19\u0e31\u0e01(KG)", None))
        self.daimond_option_selection_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e07\u0e32\u0e19\u0e1a\u0e23\u0e34\u0e01\u0e32\u0e23\u0e08\u0e32\u0e01\u0e04\u0e27\u0e32\u0e21\u0e23\u0e31\u0e01\u0e2a\u0e39\u0e48\u0e2d\u0e31\u0e0d\u0e21\u0e13\u0e35(Daimond of the memory)", None))
        self.daimond_size_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e02\u0e19\u0e32\u0e14", None))
        self.daimond_min_1carat_checkBox.setText(QCoreApplication.translate("Service_after_death", u"<1 carat (4700)", None))
        self.daimond_1carat_checkBox.setText(QCoreApplication.translate("Service_after_death", u"1 carat 6.4 mm (5800)", None))
        self.daimond_2carat_checkBox.setText(QCoreApplication.translate("Service_after_death", u"2 carat 8.1 mm (6800)", None))
        self.daimond_3carat_checkBox.setText(QCoreApplication.translate("Service_after_death", u"3 carat 9.3 mm (7900)", None))
        self.daimond_4carat_checkBox.setText(QCoreApplication.translate("Service_after_death", u"4 carat 10.2 mm (9000)", None))
        self.daimond_5carat_checkBox.setText(QCoreApplication.translate("Service_after_death", u"5 carat 11.0 mm (10100)", None))
        self.daimond_cutting_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e23\u0e39\u0e1b\u0e17\u0e23\u0e07", None))
        self.daimond_round_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e01\u0e25\u0e21(round)", None))
        self.daimond_oval_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e23\u0e35(oval)", None))
        self.daimond_princess_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e2a\u0e35\u0e48\u0e40\u0e2b\u0e25\u0e35\u0e48\u0e22\u0e21(princess)", None))
        self.daimond_radiant_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e2a\u0e35\u0e48\u0e40\u0e2b\u0e25\u0e35\u0e48\u0e22\u0e21\u0e1c\u0e37\u0e19\u0e1c\u0e49\u0e32(radiant)", None))
        self.daimond_cushion_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e17\u0e23\u0e07\u0e2b\u0e21\u0e2d\u0e19(cushion)", None))
        self.daimond_marquise_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e17\u0e23\u0e07\u0e21\u0e32\u0e23\u0e4c\u0e04\u0e35\u0e22\u0e4c(marquise)", None))
        self.daimond_cutting_other_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e2d\u0e37\u0e48\u0e19\u0e46", None))
        self.daimond_accessories_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e40\u0e04\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e1b\u0e23\u0e30\u0e14\u0e31\u0e1a(Accessories)", None))
        self.daimond_ring_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e41\u0e2b\u0e27\u0e19 (ring)               \u0e23\u0e2b\u0e31\u0e2a(CODE)", None))
        self.daimond_necklace_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e2a\u0e23\u0e49\u0e2d\u0e19\u0e04\u0e2d (necklace)    \u0e23\u0e2b\u0e31\u0e2a(CODE)", None))
        self.daimond_earing_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e15\u0e48\u0e32\u0e07\u0e2b\u0e39 (earing)            \u0e23\u0e2b\u0e31\u0e2a(CODE)", None))
        self.daimond_color_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e2a\u0e35(color)", None))
        self.daimond_price_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e23\u0e32\u0e04\u0e32(price)", None))
        self.daimond_remark_label.setText(QCoreApplication.translate("Service_after_death", u"REMARK", None))
        self.laboratory_request_frame_label.setText(QCoreApplication.translate("Service_after_death", u"LABORATORY REQUEST", None))
        self.laboratory_request_incineration_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e40\u0e1c\u0e32\u0e0b\u0e32\u0e01(Incineration) \u0e23\u0e32\u0e04\u0e32 400/40x                   KG", None))
        self.laboratory_request_bone_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e40\u0e01\u0e47\u0e1a\u0e01\u0e23\u0e30\u0e14\u0e39\u0e01 (Incineration and bone/ash storage)(200)", None))
        self.laboratory_request_cremation_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e17\u0e33\u0e1e\u0e34\u0e18\u0e35\u0e17\u0e32\u0e07\u0e28\u0e32\u0e2a\u0e19\u0e32(Cremation ceramony)", None))
        self.laboratory_date_and_time_label.setText(QCoreApplication.translate("Service_after_death", u"\u0e27\u0e31\u0e19\u0e17\u0e35\u0e48(DATE)                               \u0e40\u0e27\u0e25\u0e32(TIME)", None))
        self.laboratory_dateEdit.setDisplayFormat(QCoreApplication.translate("Service_after_death", u"d/M/yyyy", None))
        self.laboratory_request_daimond_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e17\u0e33\u0e2d\u0e31\u0e0d\u0e21\u0e13\u0e35 (Daimond of memory)", None))
        self.laboratory_carcass_label.setText(QCoreApplication.translate("Service_after_death", u"CARCASS CONDITION", None))
        self.laboratory_carcass_fresh_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e0b\u0e32\u0e01\u0e2a\u0e14 (Fresh)", None))
        self.laboratory_carcass_aytolysus_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e0b\u0e32\u0e01\u0e40\u0e19\u0e48\u0e32 (Autolysis)", None))
        self.laboratory_carcass_unknow_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e44\u0e21\u0e48\u0e17\u0e23\u0e32\u0e1a (Unknown)", None))
        self.laboratory_carcass_other_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e2d\u0e37\u0e48\u0e19\u0e46", None))
        self.laboratory_place_label.setText(QCoreApplication.translate("Service_after_death", u"PLACE OF CARCASS", None))
        self.laboratory_place_necropy_checkBox.setText(QCoreApplication.translate("Service_after_death", u"\u0e40\u0e01\u0e47\u0e1a\u0e0b\u0e32\u0e01\u0e17\u0e35\u0e48\u0e2b\u0e49\u0e2d\u0e07\u0e1c\u0e48\u0e32\u0e0b\u0e32\u0e01 (-20 Necropsy Hall)", None))
        self.laboratory_place_other1_checkBox.setText("")
        self.laboratory_place_other2_checkBox.setText("")
        self.service_after_death_save_button.setText(QCoreApplication.translate("Service_after_death", u"\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01", None))
        self.service_after_death_cancle_button.setText(QCoreApplication.translate("Service_after_death", u"\u0e22\u0e01\u0e40\u0e25\u0e34\u0e01", None))
        self.note_label.setText(QCoreApplication.translate("Service_after_death", u"NOTE", None))
    # retranslateUi

# if __name__ == "__main__":
#     app = QApplication([])
#     specimen_UI = QMainWindow()
#     ui = Ui_Service_after_death()
#     ui.setupUi(specimen_UI)
#     specimen_UI.show()
#     app.exec()